### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#100]
Have logs been implemented in version 1? We're really struggling to debug this at the moment as there does not appear to be any logs within the plugin or within BC.

Any chance of some visibility of what's going wrong with the plugin?

Thank you!

:)

**Comment by 5874** [comment]
Anyone?

**Comment by topher1kenobe** [comment]
We don't have logging implemented yet, but it's on the roadmap.

**Comment by 5874** [comment]
Thanks for the reply @topher1kenobe. Any rough idea of time?

**Comment by 5874** [comment]
@topher1kenobe ?

**Comment by topher1kenobe** [comment]
I haven't heard any discussion of timeline, BUT, in the most recent release I saw there's code for a logging area in the BC WP admin page.  I'll see if I can find more info.

**Comment by topher1kenobe** [comment]
Looks like we're shooting for the 5 Dec release.
