### ISSUE TITLE
Products being imported in to the "bin"

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#101]
After deleting all the products (due to #99), emptying the bin, deactivating the plugin, dropping all bc specific tables, removing bc related rows in wp_options, reactivating the plugin, connecting account & channel and clicking sync, the plugin is now importing all products in to the trash......

<img width="447" alt="screenshot 2018-11-12 at 13 17 30" src="https://user-images.githubusercontent.com/22817625/48349914-7e5b1900-e67d-11e8-9135-859e672d884c.png">

Why?

Would really appreciate at least a reply on this one please!!

Thank you

@karen-white @becomevocal (sorry to tag you nate but I can't tag topeher or eric anymore???)

**Comment by 5874** [comment]
Resyncing does not restore the products published status. 

We now have 252 draft products. Ordinarily, I would remove them all and resync. However it seems that with the latest release, if I do that, they will all resync in to the trash. 

How can I sync the products?

Please could somebody help us with this?

Thank you

**Comment by karen-white** [comment]
We're just arriving at the office (it's early in the AM in our time zone). Taking a look and will reply back as soon as we've had a chance to investigate.

**Comment by 5874** [comment]
Thanks for the reply @karen!!!!

Looking forward to your response shortly. We're a bit stuck here!

**Comment by 5874** [comment]
We deleted the plugin (which caused a warning, see #102) and installed 1.0 from scratch. It is now importing all of the products as draft status.

<img width="365" alt="screenshot 2018-11-12 at 16 50 56" src="https://user-images.githubusercontent.com/22817625/48362348-5da1bc00-e69b-11e8-8415-7bc75d3bf956.png">

We are completely stuck and unable to use the (> 0.12.0) plugin at all. Some help would be appreciated, but, in the absence of that, we will have to stick with version 0.12.0 indefinitely.

**Comment by 5874** [comment]
@karen-white Did you take a look and investigate?

**Comment by karen-white** [comment]
@5874 Yes, Nate and I were checking it out and we think it may be related to channel listings. Did you get a chance to run through the diagnostics that Nate suggested [here](https://github.com/bigcommerce/bigcommerce-for-wordpress/issues/99#issuecomment-437962947)?

**Comment by 5874** [comment]
Yep, I have now. How does a channel listing determine whether or not a product should be in draft? Presumably, now they are listed as (once taken out of the bin) draft for that channel, they will always be draft in that channel? So they only way to get them out of draft is to change the channel or manually go through each product and publish if appropriate?

**Comment by becomevocal** [comment]
When you create a product, the plugin will import it and create a listing in active status. Then you can change the status, which the plugin will respect during next import.

Right now you have to alter the listing status via the API, however by the end of this week we are looking to ship UI in the BC control panel that enables control over the listings:

![image 1](https://user-images.githubusercontent.com/2677921/48508141-674e2f80-e813-11e8-8e21-4b8dd9f16bc6.png)

**Comment by annuweb** [comment]
I have facing issue into your plugins : BigCommerce Wordpress
please let me know , from where i can send these issue to your developer
team
have account on bigcommerce-community . But here is no option for this

This plugis is under development . I have found some issue.

1) when I add product , It's increase counter . But not show products like
mini cart on hover like woocommerce .
2) when I add product , Then it redirect to site cart page. I have need to
back from cart to add another
product.

3) when I remove products from cart page is not decrease cart counter
number.

For this. I have created video for you . Please check this.

https://drive.google.com/file/d/1gEK5FbkC80t0uM1T307AHjyboiK0Me5M/view

Please let me know is this right place to contact you regrading plugins
issue.

**Comment by 5874** [comment]
@becomevocal Thanks but I'm unclear what the advice is to get the products out of draft without going through each one?

**Comment by becomevocal** [comment]
@annuweb we're looking into the ajax cart functionality you describe in an upcoming release. Can you add your comment onto the existing issue here? https://github.com/bigcommerce/bigcommerce-for-wordpress/issues/45

That would help us keep track of who wants that feature.

@5874 i'm suggesting waiting till we release the BC UI to list / de-list WP products as that will enable you to update the status of up to 250 products at once. When the plugin sees the new listing status it should update the products from draft to published in WP. Now, I'm saying that coming from what a default install should be and since you're upgrading from a previous version it might not work that way... the reality is we probably need a look at your WP instance to be sure. 

Outside of GH (email?), if you could get me secure admin access to the site you are hitting this issue on I can dive in and see what's different about it.

**Comment by 5874** [comment]
Thanks @becomevocal but we've decided to stick with version 0.12.0 for the foreseeable future now. Too much time was being spent debugging and writing fixes (in our add-on plugin) for the plugin. 0.12.0 is working for C's and is stable. We can't see much value add in pushing on with further releses when weighing in the inevitable and lengthy support process when it doesn't work as expected. It's a very young product. When it's grown up a bit we'll have at it again ;)

**Comment by becomevocal** [comment]
Yep, that makes sense. We've been optimizing for net-new onboarding with the latest release so the upgrade path is difficult at the moment. If they are stable, no need to push on it.

FYI, in the next few releases we aim to add more diagnostic tools to aid with issues like this.

I'm going to close this one out for the moment. Offer still stands if you want me to take a look at the site config in the future.

**Comment by 5874** [comment]
> When you create a product, the plugin will import it and create a listing in active status. Then you can change the status, which the plugin will respect during next import.
> 
> Right now you have to alter the listing status via the API, however by the end of this week we are looking to ship UI in the BC control panel that enables control over the listings:
> 
> ![image 1](https://user-images.githubusercontent.com/2677921/48508141-674e2f80-e813-11e8-8e21-4b8dd9f16bc6.png)

@karen-white @becomevocal Did this ever happen? We are in desperate need of it now....

**Comment by becomevocal** [comment]
@5874 it did! it's in production now and should activate when a store creates a WP channel via the API (the plugin does this POST for you).

**Comment by 5874** [comment]
That's great. Where might we find that?

**Comment by becomevocal** [comment]
It should be added into the products screen. When you select one or more
products on the list via the checkbox on the left hand side, you will see
bulk actions. One of the actions will be 'list products to channel'.
