### ISSUE TITLE
Not Seeing Products' option-types on Single Product Pages.

### ISSUE THREAD

**Issue by floorbroker** [bigcommerce/bigcommerce-for-wordpress#105]
### Expected behavior
On a single product page I am unable to see any of the option-types integrated on it's original Bigcommerce functionality.

BigCommerce.com Product Link (Original):
http://floor-broker-xviii.mybigcommerce.com/copy-of-revotec-ethos/

WordPress.com Site Direct Product View:
https://floorbroker.com/products/copy-of-revotec-ethos/

Wordpress.com Site Shortcode Product View:
https://floorbroker.com/0test-bigcom-wp/

I opened up the Console on the page(s) and there isn't any pull requests being blocked from what I'm seeing. This is possibly a quick fix, but without changing numerous .php files do you have any suggestions?

**Comment by topher1kenobe** [comment]
@floorbroker I'm going to dig into this and see what I can find. You shouldn't have to change any templates.

**Comment by 5874** [comment]
@topher1kenobe More than likely related and unanswered: #50

**Comment by floorbroker** [comment]
I really appreciate it @topher1kenobe . I am doing some digging as well and will keep this post updated if I find any issues.

**Comment by topher1kenobe** [comment]
Can you try making SKUs for each of the options and try the import again?

**Comment by floorbroker** [comment]
Sorry @topher1kenobe , yesterday I wasn't at my primary work computer. I just imported the products again, adding SKUs to both the individual product itself + each individual radio option.

I now see the radio option list on each page, thank you so much for diagnosing & resolving my issue for that. There are separate issues/notes now presenting themselves I can list below that if you want to notate them for a patch.

##Actual Product Page VIA Bigcommerce Plugin Extension:
https://floorbroker.com/products/copy-of-revotec-ethos/

Notes:
- **!** Radio option/option set Rules set in BigCommerce are not communicating with selections. (No errors in the console log when selecting any.)
- Layout differs from shortcode (unless this is on purpose).

##Shortcode Product:
https://floorbroker.com/0test-bigcom-wp/

Notes:
- **!** Radio option/option set Rules set in BigCommerce are not communicating with selections. (No errors in the console log when selecting any.)
- Specifications / Custom Fields Not Showing
- SKU not showing, but it shows on the product page.

Again, thank you so much for helping out.

- Mark Trombley / Head of Web Design at Floor Broker

**Comment by topher1kenobe** [comment]
Thanks for this great feedback, I'll let the dev team know!

**Comment by topher1kenobe** [comment]
@floorbroker it would be helpful if you could separate the above issues into their own github tickets.  It'll make it a lot easier to track and assign to developers.

Thanks!
