### ISSUE TITLE
The order history page: dates aren't displayed correctly

### ISSUE THREAD

**Issue by vitaliyreznikov** [bigcommerce/bigcommerce-for-wordpress#107]
Instead of correct dates "January 1, 1970 is dispayed"
I looked at the code, Client::getOrder returns date as "string(31) "Thu, 15 Nov 2018 13:25:29 +0000"", but template waits date as "Y-m-d h:i:s"
Also, I think if the date doesn't determine (for example shipping date) it's better don't show it.

![image](https://user-images.githubusercontent.com/7270718/48558837-ec5c4600-e8f2-11e8-9365-90bdfa4c5ddc.png)

**Comment by becomevocal** [comment]
Thanks @vitaliyreznikov, we're seeing this as well. Added a PR that fixed it on my end: https://github.com/bigcommerce/bigcommerce-for-wordpress/pull/111

We're going to look into why the originally used built-in WP function doesn't work. Preference would be to use that.

**Comment by karen-white** [comment]
Fixed in [1.4.0](https://github.com/bigcommerce/bigcommerce-for-wordpress/releases/tag/1.4.0). Closing this out 👍
