### ISSUE TITLE
Upgrade process and/or cannot setup channels in dashboard.

### ISSUE THREAD

**Issue by textivia** [bigcommerce/bigcommerce-for-wordpress#108]
### Expected behavior
Update plugin, and it works - or - delete current beta plugin, and all BC settings,products, etc are removed from dashboard.

### Actual behavior
Neither of those , and there are no clear "upgrade from beta to production" plugin directions.

---

Are there upgrade directions for the plugin?
Should there be a new API user setup in the BC account?
I cannot set a channel - and when I go to setup a new channel on the site - it just says there was an error creating a channel.

**Comment by karen-white** [comment]
@textivia We'll have more detailed update instructions emailed out shortly, but in the meantime, these are the steps to upgrade from a previous version of the plugin:

1. Deactivate and delete the old plugin
2. Install the new plugin
3. Follow the onboarding flow and sign in to your store to authenticate
4. Reimport all products (will happen automatically)

There's no need to create a new API account--the latest version of the plugin automatically creates a new token with all of the updates scopes needed to create channel listings.

**Comment by textivia** [comment]
I have tried this option - or deactivate, and delete., Install, Activate, and then i navigate to the "bigcomm > welcome" screen and this is all i see:

https://www.dropbox.com/s/y4og6helnertzum/Screenshot%202018-11-16%2010.51.56.png?dl=0

And when creating a new channel - this error happens: 

https://www.dropbox.com/s/yj2dkoap05eorfu/Screenshot%202018-11-16%2010.53.28.png?dl=0

**Comment by karen-white** [comment]
Do you have any other old versions of the plugin installed?

**Comment by textivia** [comment]
No, the plugin has been removed from the website.

**Comment by vabori** [comment]
I am also experiencing this issue.

In addition, the Checkout Page does not load. I add products to cart then press proceed to checkout and the checkout page heading loads, but no content loads.

Note, I updated from 0.12.0 to 1.0.2 via WordPress built in update plug in feature.

**Comment by karen-white** [comment]
@vabori Could you try upgrading the plugin using the instructions I outlined above (deleting old and then installing new)?

@textivia If you're being taken to the channels screen, it suggests that the plugin is still connected via the old API credentials that were entered manually. The old credentials didn't include a scope for creating channel listings, which is why the process gets hung up on that step. We'll continue to look into it on our end.

**Comment by karen-white** [comment]
@textivia Are you using a multi-site setup, or connecting to a single WordPress instance?

**Comment by textivia** [comment]
Yes @karen-white this is a multi-site setup

**Comment by karen-white** [comment]
Thanks @textivia. Unfortunately multi-site is not working at the moment, but we hope to have this fixed shortly. I'll keep you posted.

**Comment by textivia** [comment]
We are looking for a store per microsite.  We have one sub-directory microsite, with 30 sites.  we have 30 stores through BC that we'd like to map one store per site.

Is this a possibility in the roadmap?

**Comment by becomevocal** [comment]
@textivia if you want to connect each multi-site instance to a different BC store, you should be able to do that now, by connecting an a different existing store each site in the network. We just resolved the existing store connection issue so maybe try again?

**Comment by karen-white** [comment]
@textivia Following up here. Are you still seeing the issue?

**Comment by textivia** [comment]
Here is what we see - we cannot reauthorize, we cannot create a channel, etc... 

https://www.dropbox.com/s/qcfdrv7z9gieb7h/sm-recording.mov?dl=0
