### ISSUE TITLE
Unable to "Connect to Account" - v1.0.2

### ISSUE THREAD

**Issue by civicpath** [bigcommerce/bigcommerce-for-wordpress#110]
### Expected behavior
Install & activate the plugin from the Wordpress plugin store. Connect the BC for Wordpress plugin to my BC account. See the connection to the store in my BC account under Apps. 

### Actual behavior
With a fresh Wordpress install 4.9.8, Ubuntu 18.04.1, HTTPS, I installed BC for WP directly from the Wordpress plugin store. I activated the plugin, clicked "Welcome", and clicked to "Connect My Account". The plugin is stuck spinning on 

**We’re Getting Your Account Ready**
Bear with us just a moment while we gather information about your account."

### Screenshot/Video (if applicable)

Nothing in the Apache ERROR log.
The Apache ACCESS log shows this entry ever few seconds.... 

 [16/Nov/2018:20:48:48 +0000] "GET /wp-admin/admin-ajax.php?_wpnonce=6c6d9512a2&action=bigcommerce_account_status HTTP/1
.1" 502 771 "https://dev2.truframe.com/wp-admin/edit.php?page=bigcommerce_pending_account&post_type=bigcommerce_product" "Mozilla/5.0 (W
indows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"

### Workaround or possible solution

Browsing to the URL (/wp-admin/admin-ajax.php?_wpnonce=6c6d9512a2&action=bigcommerce_account_status) from that access log entry, I see this message:

{"success":false,"data":{"code":"bad_gateway","message":"There was an error retrieving your account status.","data":"Unauthorized.","response_code":403}}

The action references a function from:
/src/BigCommerce/Merchant/Account_Status.php

This file has not been updated in a few weeks - not sure if the recent Wordpress "sanitizing" affected any expected variables in this file.

**Comment by becomevocal** [comment]
@civicpath thanks for filing this. We can replicate this and are looking into it. Hope to have more info tomorrow.

In the meantime, you can connect an existing store without going through this process by adding it the API credentials into the wp_options table. If the plugin sees those settings, if won't need to go through the connection process you are stuck on. These are the option_name rows you need to add with the corresponding values available via the BC Store's API Account section:
bigcommerce_store_url
bigcommerce_client_secret
bigcommerce_client_id
bigcommerce_access_token

If you don't see Channel, Sites & Routes scopes on your account, let me know the BC Store url and I can turn them on.

**Comment by kalwiggins** [comment]
I'm getting the same error on a fresh install for the last 24 hours.

"We’re Getting Your Account Ready
Bear with us just a moment while we gather information about your account."

**Comment by civicpath** [comment]
Thanks @becomevocal. The store ID I'm working with is `store-ksty8p5i1g`. 

I created an API V3 user in BC and added those rows to the Wordpress wp_options table. 

Once those database fields were created, the Wordpress admin pages produce a Server 500 error. 

Here's a sample Apache error log:

`[Mon Nov 19 15:11:42.086407 2018] [php7:error] [pid 30440] [client 12.8.243.226:64277] PHP Fatal error:  Uncaught Error: Call to undefined function BigCommerce\\Api\\v3\\curl_init() in /opt/wordpress/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/ApiClient.php:161\nStack trace:\n#0 /opt/wordpress/wp-content/plugins/bigcommerce/src/BigCommerce/Api/Caching_Client.php(57): BigCommerce\\Api\\v3\\ApiClient->callApi('/channels', 'GET', Array, '', Array, '\\\\BigCommerce\\\\Ap...', '/channels')\n#1 /opt/wordpress/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/Api/ChannelsApi.php(605): BigCommerce\\Api\\Caching_Client->callApi('/channels', 'GET', Array, '', Array, '\\\\BigCommerce\\\\Ap...', '/channels')\n#2 /opt/wordpress/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/Api/ChannelsApi.php(560): BigCommerce\\Api\\v3\\Api\\ChannelsApi->listChannelsWithHttpInfo()\n#3 /opt/wordpress/wp-content/plugins/bigcommerce/src/BigCommerce/Merchant/Channel_Connector.php(37): BigCommerce\\Api\\v in /opt/wordpress/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/ApiClient.php on line 161, referer: https://%%WORDPRESS_URL%%/channels`

**Comment by stoneroadmedia** [comment]
We are have the same problems, it just sits and spins at at the welcome screen.
Steve

**Comment by constephen** [comment]
Same problem. I'll keep an eye on this page for a solution.

**Comment by stoneroadmedia** [comment]
do we need to install new files?  we tried to add the 1.0.2 and it still just spins?

**Comment by stoneroadmedia** [comment]
also the plugin directory in wp is bigcommerce, the new directory in the zip is bicommerce5 ?

**Comment by stoneroadmedia** [comment]
![image](https://user-images.githubusercontent.com/41306470/48779362-70248280-eca5-11e8-9680-f96c37e0519f.png)

**Comment by kalwiggins** [comment]
Awesome. The plugin didn't update on it's own, but when I deleted it and reinstalled it, the problem seems to be resolved.

**Comment by stoneroadmedia** [comment]
We did the same thing, I could only delete it with FTP and put the new in "bicommerce5" and it did the same thing (screen shot above)

**Comment by becomevocal** [comment]
@stoneroadmedia you should try deleting then adding from the plugin repository, since it's live there now.

**Comment by stoneroadmedia** [comment]
We did that this AM and its still 1.0.2 and it did not work.   Is there something I am missing?

**Comment by stoneroadmedia** [comment]
Nothing shows today? 
![image](https://user-images.githubusercontent.com/41306470/48791744-6eb48380-ecc0-11e8-80b3-c2ffcfd04bec.png)

**Comment by becomevocal** [comment]
@stoneroadmedia I meant delete the plugin and then go through the Plugins -> Add New flow in WP to add our plugin, like this:

<img width="1440" alt="screen shot 2018-11-20 at 11 42 57 am" src="https://user-images.githubusercontent.com/2677921/48793028-5726cc00-ecbb-11e8-9e81-d0aedf1765f4.png">

I just ran through this process and connected my store successfully. One thing to note is that you need to let the pop-up show when it's waiting to connect so you can log into your existing store.

<img width="1236" alt="screen shot 2018-11-20 at 11 43 24 am" src="https://user-images.githubusercontent.com/2677921/48793093-89382e00-ecbb-11e8-9ee7-a4a8562d5d29.png">

In that above screen, you'd allow the pop-up.

<img width="1216" alt="screen shot 2018-11-20 at 11 43 59 am" src="https://user-images.githubusercontent.com/2677921/48793133-a2d97580-ecbb-11e8-8e86-c77b21721623.png">

Then in this pop-up click log in.

**Comment by stoneroadmedia** [comment]
We tried all that and it still just sits there and rotates: "We’re Getting Your Account Ready
Bear with us just a moment while we gather information about your account."

Also we cant delete it once we deactivate it...we have to FTP kill it.

Steve

**Comment by stoneroadmedia** [comment]
We also installed it locally on a dev server we have and it broke the install bad.  Still seeing major issue.

**Comment by stoneroadmedia** [comment]
when you install from wp market you get a bigcommerce directory, when you manually install from download you get bigcommerce5 too.

**Comment by civicpath** [comment]
Ok, I think I found out what was happening. 

**PHP7.2-CURL**

I noticed that a lot my 500 server error issues are related to CURL commands in the API. 

When I went to verify that my Ubuntu 18.04.1 instance with PHP7.2 had php-curl... I found out that no **it did not**. 

Turns out the default install of Ubuntu 18.04 with php7.2 and php7.2-common might be incompatible with php7.2-curl. 

I removed all PHP packages. Installed php7.2-curl. Then installed php7.2, php7.2-common, etc etc


I'm back to my instance with php7.2-curl, and no more 500 server errors. I go to BigCommerce -> Welcome, and I see Channel Settings -> Select Channel. 

I'm going to scrub my Wordpress instance and start from the beginning.

**Comment by civicpath** [comment]
**RESOLVED**

Now with php7.2-curl installed, started with a fresh Wordpress install. 
Installed the BigCommerce plugin (now **version 1.1.0**)
All went smooth. 
From Wordpress, I can select my BC Channel

**Comment by civicpath** [comment]
Just for fun, I removed php7.2-curl, wiped the WP instance, and started again with a fresh install of WP and BC 1.1.0

I got through connecting my WP instance to BC, but back to 500 server error for the BC Channel selection. 

I reinstalled php7.2-curl and that resolved the 500 Server error again. I set the channel and am ready to sync & use the plugin

**Comment by civicpath** [comment]
@stoneroadmedia  - No php7.2 is not required. But you may find it as the default PHP for some distributions. I think you just need to have at least php5.6.

In my case, my Ubuntu 18.04 instance was pre-installed with php7.2 (AWS / Lightsail). This default installation had a dependency problem with php7.2-curl conflicting with php7.2-common. I had to remove the php packages, install php7.2-curl first, then install the other php7.2 packages. When php7.2-common was installed through apt-get, a different (older) version was installed so that it was compatible with php7.2-curl.

**Comment by stoneroadmedia** [comment]
1.1.0 fixed it all and it now works!  Thank you

**Comment by stoneroadmedia** [comment]
Update all works and installs and brings in products.  When you click VIEW to look at one it just redirects to the homepage.  Any thoughts?

**Comment by civicpath** [comment]
@stoneroadmedia - This appears to be a separate issue. 

Is the product listed as a Draft? If so, Publish the item to your Wordpress.  

Your web server configuration, .htaccess file, or Wordpress Permalink settings could also be a factor.

**Comment by stoneroadmedia** [comment]
No it is a live product.

Thanks
Steve

**Comment by stoneroadmedia** [comment]
All of our site were working great until we tried to go to 1.1.0

**Comment by civicpath** [comment]
When you 'mouse over' the VIEW link, what type of URL do you see? 

The default URL structure is something like:

`https://**WORDPRESS_URL**/?p=123`

Settings -> Permalink and use "Post Name", so this is the type of structure see:

`https://**WORDPRESS_URL**/products/PRODUCT_NAME`



In any event, the .htaccess file or web server config file may be interfering with proper redirection. 

These are the Apache2 site directory settings I'm using on Ubuntu 18.04.1 LTS. 

`        <Directory /opt/wordpress>
                Options +FollowSymLinks 
                AllowOverride All
                Require all granted
        </Directory>`

In the Wordpress directory, the .htaccess file looks like this:

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>`

**Comment by annuweb** [comment]
This plugis is under development . I have found some issue.

1) when I add product , It's increase counter . But not show products like mini cart on hover like woocommerce plugins in wordpress
2) when I add product , Then it redirect to site cart page. I have need to back from cart to add another
 product.
3) when I remove prouct from cart page is not decrease cart counter number. 
For this. I have created video for you . Please check this.

**Comment by becomevocal** [comment]
@annuweb, the #1 and #2 issues you list are more feature requests? And good news is we have an update slated for December that includes the option to have an 'ajax cart' which does what you explain. So that's coming soon!

For the cart page not decreasing the cart number when a product is removed, that should be functional. This is what is happening for me:

![ezgif-1-b345ccf88124](https://user-images.githubusercontent.com/2677921/48921723-50d55300-ee67-11e8-9a3c-c971e1c8b643.gif)

I'm using the most recent version of the plugin, version 1.1.0, which is also in the plugin repository.

Also just wanted to say Happy Thanksgiving to everyone! I'm thankful to see you on here helping each other. : )

**Comment by civicpath** [comment]
I'm closing this issue since the original bug is resolved. Some users were unable to connect to their stores, and now they can as of version 1.1.0. 

If any of the additional questions regarding product listings, displaying stock levels, or cart behavior, please open a new issue for each of those specific topics. 

Thank you @becomevocal for your responsiveness and support in getting this resolved for us.

**Comment by jecalderon** [comment]
> @civicpath thanks for filing this. We can replicate this and are looking into it. Hope to have more info tomorrow.
> 
> In the meantime, you can connect an existing store without going through this process by adding it the API credentials into the wp_options table. If the plugin sees those settings, if won't need to go through the connection process you are stuck on. These are the option_name rows you need to add with the corresponding values available via the BC Store's API Account section:
> bigcommerce_store_url
> bigcommerce_client_secret
> bigcommerce_client_id
> bigcommerce_access_token
> 
> If you don't see Channel, Sites & Routes scopes on your account, let me know the BC Store url and I can turn them on.

Where xatly thes etabel is found? I foudn an option table but there is no lines with these settings. I assume that I have to entere the in. But.  what I add in th enext 2 columns?

**Comment by jecalderon** [comment]
> @civicpath thanks for filing this. We can replicate this and are looking into it. Hope to have more info tomorrow.
> 
> In the meantime, you can connect an existing store without going through this process by adding it the API credentials into the wp_options table. If the plugin sees those settings, if won't need to go through the connection process you are stuck on. These are the option_name rows you need to add with the corresponding values available via the BC Store's API Account section:
> bigcommerce_store_url
> bigcommerce_client_secret
> bigcommerce_client_id
> bigcommerce_access_token
> 
> If you don't see Channel, Sites & Routes scopes on your account, let me know the BC Store url and I can turn them on.

Where are these lines copy and paste to?

**Comment by becomevocal** [comment]
@jecalderon to use set BigCommerce API credentials directly, you can do one of these things which don't require using the wp_options table:

**1 )When installing the plugin, choose the 'Enter your API Credentials' option**

<img width="804" alt="Screen Shot 2020-01-26 at 2 59 27 PM" src="https://user-images.githubusercontent.com/2677921/73141739-283d8000-404d-11ea-9ab9-24e957cc6be3.png">

That will show a screen where you add your API credentials:

<img width="835" alt="Screen Shot 2020-01-26 at 2 59 43 PM" src="https://user-images.githubusercontent.com/2677921/73141755-5327d400-404d-11ea-92bc-b7cac766e2b7.png">

**2) Go to the Settings screen after installing the plugin and set them within the API Credentials section**

The same form as above will show there.

**If you are looking for the values in your wp_options database table, you can use the following query to get all bigcommerce option values:**

`SELECT * FROM wp_options WHERE option_name LIKE '%bigcommerce_%'`

It'll return something like this as the entries:

<img width="742" alt="Screen Shot 2020-01-26 at 3 03 40 PM" src="https://user-images.githubusercontent.com/2677921/73141791-bca7e280-404d-11ea-93fa-18f79d4765b9.png">

**If you want to access the values programmatically you would use get_option():**

https://developer.wordpress.org/reference/functions/get_option/

`get_option('bigcommerce_store_url')`
`get_option('bigcommerce_client_secret')`
`get_option('bigcommerce_client_id')`
`get_option('bigcommerce_access_token')`

_Hopefully this helps you out! _
