### ISSUE TITLE
BigCommerce\Cart\Cart method get_cart_id() can return old value

### ISSUE THREAD

**Issue by vitaliyreznikov** [bigcommerce/bigcommerce-for-wordpress#112]
https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/d3f4733cdd80e549e4a069ea9256c3040912ab84/src/BigCommerce/Cart/Cart.php#L58

If cookie changes in the above-mentioned line, variable $_SESSION keeps the old value.
It's better to add
`$_SESSION[self::CART_COOKIE] = $cart_id;`

**Comment by karen-white** [comment]
Hey @vitaliyreznikov , thanks for raising this. We'll include a fix in the next release 👍

**Comment by topher1kenobe** [comment]
Resolved
