### ISSUE TITLE
Possible PHP 7 Compatibility Error

### ISSUE THREAD

**Issue by emaildano** [bigcommerce/bigcommerce-for-wordpress#115]
### Behavior

I get the following error running PHP 7

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/web/wp/wp-content/plugins/bigcommerce/src/BigCommerce/Checkout/Requirements_Notice.php on line 118
```

References in use:
- http://php.net/manual/en/migration72.incompatible.php
- https://github.com/Automattic/jetpack/issues/8420

**Comment by carsonreinke** [comment]
@emaildano Count on a `null` probably [here](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/src/BigCommerce/Checkout/Requirements_Notice.php#L118)

**Comment by topher1kenobe** [comment]
@emaildano can you tell me which version of 7?

**Comment by emaildano** [comment]
@topher1kenobe PHP 7.3

**Comment by topher1kenobe** [comment]
Resolved.
