### ISSUE TITLE
Set A Default Customer Group

### ISSUE THREAD

**Issue by civicpath** [bigcommerce/bigcommerce-for-wordpress#118]
ENHANCEMENT
Similar to #66 which deals with ability to map with multiple groups. Though this is more about setting a default group for the WordPress site to establish a baseline for all new WP accounts. 

### Expected behavior
When creating a WordPress site with the BC plugin alongside a BC store, site admins should have the ability to set the default customer group for accounts created on the WordPress store. 

### Actual behavior
Users are created according to the default customer group settings in BC. 

### Work Around
While store admins can always go into BC and manually change the groups of customers, the WordPress stores would suffer a chicken-and-egg scenario where they cannot apply a customer group to new customers until they've signed up. This often happens within minutes of completing their first purchase. Unless you have someone monitoring this 24/7, a default group selection for the WordPress store would be the way to ensure that store specific pricing can be applied. 

###

A common reason why BigCommerce customers will maintain both a BC and WP store would be from a desire to segment customer experiences. Examples include separating B2B from B2C, creating country specific variants, or using WP stores for brand specific versions of a larger BC catalog. 

In each of these cases, it would be ideal to map new customers from WP stores to a specific BC customer group. 

Some benefits to automatically applying the customer group include:
- Store specific product offerings can be displayed (and hidden from the BC catalog)
- Store specific pricing can be offered
- Back end customer management improves with ability to easily see the origin of new accounts
- Back end order management improves with increased visibility of the origin of each order

**Comment by bookernath** [comment]
Thanks for your feedback @civicpath , we'll take a look at this. You could argue this is a bug in the Customers API (which backs the plugin).

**Comment by bookernath** [comment]
Thanks; that's a good idea as well. We'll discuss with the team.

**Comment by bookernath** [comment]
As a small update, we've improved the behavior of our Customers API to respect the default customer group on the store, which will also result in this plugin respecting it.

We can further refine the plugin later to allow each WP installation to have its own default customer group for new customers.

**Comment by yuenvision** [comment]
This is handled in the BC admin under Customers > Manage Customer Groups; Channels can be assigned default customer groups for new customers created. At that point, the customer group meta is delivered via the Customer API and BC4WP respects that group's price lists and permissions/restrictions.
