### ISSUE TITLE
Customize Email Messages by Store (or Group)

### ISSUE THREAD

**Issue by civicpath** [bigcommerce/bigcommerce-for-wordpress#119]
ENHANCEMENT
This might actually be a feature request for BigCommerce instead of the WP plugin

### Expected behavior
When a customer places an order from the WordPress store, admins should have the ability to configure store specific email replies. 

### Actual behavior
All customers in both BC and WP get the same email replies. For WP stores that have a different customer experience that the main BC store, using the default Email Templates might create confusion for customers.  

### Workaround 
Disable the BC Email Templates. Use a custom/third party integration to segment orders originating from each store and create/send email templates based on those origins. 

### Possible Solution
This might best be handled entirely within BigCommerce. BigCommerce could allow admins of Plus, Pro, and Enterprise accounts to extend "Storefront -> Email Templates". Like having product specific pricing based on Customer Groups, BC could support Email Template variants by Customer Group.  

This would allow the BC store admin to customize messaging for B2C and B2B customers. And in conjunction with #118 (Set A Default Customer Group), this allows WP store admins to maintain store specific branding and messaging to customers of the WP store. 

This enhancement would also improve messaging for all BC stores that rely on customer segmentation.

**Comment by karen-white** [comment]
@civicpath Hey Greg, this is great feedback. We're working on some advances within our APIs and email templates that should pave the way for this kind of segmentation in the future. Stay tuned!

**Comment by yuenvision** [comment]
Transactional emails are now customizable within the BC admin from Marketing > Transactional Emails; From there, selecting the appropriate storefront and modifying the email messaging/template can be done on a per Storefront level or at a global level for all storefronts.
