### ISSUE TITLE
On order history page show subtotal_ex_tax as subtotal, not subtotal_inc_tax

### ISSUE THREAD

**Issue by vitaliyreznikov** [bigcommerce/bigcommerce-for-wordpress#123]
I offer change subtotal_inc_tax to subtotal_ex_tax to order history page, otherwise, it's hard to figure out if there are both taxes and a discount.
https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/src/BigCommerce/Templates/Order_Summary.php#L73

![image](https://user-images.githubusercontent.com/7270718/49651463-ebbd5800-fa37-11e8-8af6-1428bd3c37e4.png)

**Comment by karen-white** [comment]
Thanks for the suggestion @vitaliyreznikov ! That's good feedback. We'll discuss it with the team and keep you updated.

**Comment by karen-white** [comment]
Quick update @vitaliyreznikov --we'd like to address this down the road, but in the meantime, we'd welcome any suggestions or PRs, if you've got ideas on how best to handle the subtotal in the template. :)

**Comment by tyla-taylor** [comment]
Addressed in v4.16.0
