### ISSUE TITLE
skus required for all option permutations

### ISSUE THREAD

**Issue by kalwiggins** [bigcommerce/bigcommerce-for-wordpress#127]
I have a product with 10 picklist options attached to it.

### Expected behavior
The product should show up in WordPress with all available options

### Actual behavior
The product shows up in WordPress with no available options
This is because a SKU is seemingly required for all options in order for them to show and to validate on the WordPress side. If I create a sku for the base product plus each picklist item (total of 10 skus) then all the picklist items show up on the WordPress side, BUT if you try to add 2 of the picklist items to cart, validation prevents you from adding it to the cart, because there is no sku for the current permutation. I believe 3.6m skus would be created to make all combinations available which massively exceeds  BigCommerce's sku max, even if this made sense to input.

### Steps to reproduce behavior

1. create product
2. add 10 picklist addons to it
3. sync to WordPress

### Workaround or possible solution
Is there a way to disable sku validation or is this really a requirement? It seems like you should only need product ids to push the orders to BC?

**Comment by tyla-taylor** [comment]
Addressed in v3.5.0
