### ISSUE TITLE
Category Import Support for Products

### ISSUE THREAD

**Issue by scottxtensive** [bigcommerce/bigcommerce-for-wordpress#128]
Trying to understand how to properly manage categories with this plugin. At the moment we are setting up a new page for each category and adding in a customised Gutenberg block to filter categories. 

Another method was to use the url parameters taken from the /products/ dropdown. However this isn't particularly great for SEO slugs. 

`/products/?s=&bc-sort=title_asc&bigcommerce_category=garden&bigcommerce_brand=0`

Would it not be better to sync product categories over to WP like the products currently do and make use of Wordpress's built in category function to output product categories like - 

`/products/garden`

Then for the actual product page the slug could be - 

`/products/garden/product-title`

Thanks!

**Comment by scottxtensive** [comment]
**Update:** I have discovered that these already exist under - `/products/categories/coats-jackets/` categories slug. Would be nice to document that after spending hours working out!

**Comment by topher1kenobe** [comment]
Resolved
