### ISSUE TITLE
Improve AJAX add to cart on 1.4.0

### ISSUE THREAD

**Issue by scottxtensive** [bigcommerce/bigcommerce-for-wordpress#130]
Following the 1.4.0 release of the plugin, we noticed AJAX support was added! There could be some improvement as suggested below:

 1. Either add a loading spinner or change text on the button to show the entry is being processed. At the moment the button just blinks and has made customers spam the button thinking it's not working.

2. If a product requires an option variant to be selected (E.g - color swatch) there needs to be a message directing the user to enter the option. At the moment you can click "Add to cart" with an option selected and nothing happens.

3. Performance - Speed could be increased adding items to cart compared to the normal BC experience. Almost more than 4-5 seconds on WP.
 
PS: Would appreciate adding the changelog entry to the WordPress plugin directory tab 👍

**Comment by karen-white** [comment]
Hey @scottxtensive , Thanks for opening this. I'm creating a ticket on our end to investigate the issue with swatch options--that's definitely not intended. And we'll continue to look into speeding up the Add-to-cart function as we iterate.

**Comment by scottxtensive** [comment]
Thanks @karen-white , The add-to-cart time is a critical request on our side. Even while using the usual "non-ajax" cart process we are seeing times of +10 seconds which as you can imagine isn't great for customer experience. I have passed my thoughts onto our partner manager. Thanks 👍

**Comment by karen-white** [comment]
Thanks @scottxtensive . 10+ seconds seems far beyond what we're seeing on our tests. Could you share steps to replicate, or a URL where you're seeing this?

**Comment by scottxtensive** [comment]
Hi @karen-white thanks for the quick response! Please find a link to the development domain in question - https://stuartrt.co.uk/glitterbug/products/product-example/ When comparing with https://www.carluccios.com/products/olio-e-olive-gift-set/ as an example the add to cart time is much quicker. All we can think is if trial accounts are throttled on the API? If you need further debugging info do you have an email we can contact?

**Comment by karen-white** [comment]
Appreciate the example @scottxtensive . That's definitely unusually slow. I've opened a tracking ticket and shared the URL with our dev team. We'll keep you posted with any updates, or if further details are needed. Thanks!

**Comment by karen-white** [comment]
Hi @scottxtensive , one more quick detail--could you share the URL for the BigCommerce store that's connected to the plugin?

**Comment by scottxtensive** [comment]
Hi @karen-white yes sure - http://glitterbug.mybigcommerce.com/ (Note: the store is currently just expired. We will be getting this sorted today so hopefully back up by the time you read this!)

**Comment by scottxtensive** [comment]
Morning @karen-white we have managed to solve the problem! I think we had an issue with that trial store. I wiped the plugin and reconnected to another and the request url has changed when adding to cart - not sure why but speed it much quicker! Many thanks for the help. 

If you can let us know when the colour swatch bug is sorted that would be super!

**Comment by karen-white** [comment]
That's great news @scottxtensive ! Thanks for following up, and thanks for providing us with info to investigate why it was happening. We'll keep you posted on the color swatch bug!

**Comment by karen-white** [comment]
@scottxtensive Wanted to let you know the swatch bug is now fixed--thanks again for reporting that. I'm going to close out this issue, but let us know if you're still seeing any problems!
