### ISSUE TITLE
1.4.0 disables click through to cart on add to cart

### ISSUE THREAD

**Issue by kalwiggins** [bigcommerce/bigcommerce-for-wordpress#133]
### Expected behavior
when you click add to cart it should put something into your cart, and forward you to the cart

### Actual behavior
it puts something in cart, makes the add to cart button flash a couple times like something is wrong, then you stay on the product page

### Steps to reproduce behavior

1.upgrade to 1.4
2.go to product page
3.add anything to cart

### Screenshot/Video (if applicable)
https://www.useloom.com/share/4616366e896b4f249ca3a68ea84afb23

**Comment by karen-white** [comment]
Hey @kalwiggins , we just pushed a fix for this in version 1.4.2. Could you let us know if you're still seeing the issue after updating to that version? Thanks!

**Comment by karen-white** [comment]
@kalwiggins Great news! I'll close this for now, but let us know if anything comes up while testing.
