### ISSUE TITLE
Abandoned Cart functionality with WP?

### ISSUE THREAD

**Issue by scottxtensive** [bigcommerce/bigcommerce-for-wordpress#134]
Is the Abandoned Cart Saver feature planned to be implemented with WordPress at any stage? This is has been a big seller feature to our clients and would be great to sync data across to the BC analytics dashboard!

**Comment by becomevocal** [comment]
@scottxtensive it is! We're planning on enabling that by the time we have our April release of the plugin.

**Comment by garrisons** [comment]
@becomevocal any update on this?

**Comment by scottxtensive** [comment]
@becomevocal +1 - any updates if this has been added yet? We have a client looking to move to a WP version of their store but need this feature.

**Comment by becomevocal** [comment]
@scottxtensive the team is working on enabling an abandoned cart 'route' to be defined and respected by the emails we send out now, in the current sprint. So it's definitely in the near term we'll enable this.

**Comment by topher1kenobe** [comment]
Abandoned Cart functionality has been working for many versions now.
