### ISSUE TITLE
Allowing saved cards to be shown on the Wordpress side

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#135]
We have a feeling that this will be far more complicated than simply implementing this, due to the way that the saved cards feature works and the sensitive nature of the data involved. 

However it would be great if we could at least display the customer's saved cards in their account, and have the ability to remove them (doesn't necessarily need the ability to add them, as the checkout can handle that part of the flow, and this would add a lot of complication from a PCI perspective).

**Comment by topher1kenobe** [comment]
Card information shouldn't be sent to WordPress for security reasons.
