### ISSUE TITLE
Load all products

### ISSUE THREAD

**Issue by mardukian** [bigcommerce/bigcommerce-for-wordpress#136]
Is there any way to use the shortcode and to load all products, not have the "Load more Products". I set it to 99 in the customizer but it doesn't let us have more than that. The client has 400 products and wants them to all load but I can't see a workaround for this.

Have tried setting paged to 0 and this just disable pagination, it doesn't load all the products.

**Comment by karen-white** [comment]
Hey @mardukian ,
The number of products per page is capped in the shortcode for performance reasons, but there are a couple of approaches you could take to override that behavior:
1. You could use a plugin or JS to create an endless scroll effect on the category page. This would give you the illusion that all of the products are loaded on the page at once, without the performance issues.
2. You can filter the shortcode query args to make the shortcode output every product. That filter lives in Query_Mapper.php: 
https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/src/BigCommerce/Post_Types/Product/Query_Mapper.php#L139

And can be filtered this way to output every product:
```
`add_filter( 'bigcommerce/shortcode/products/query_args', function( $args ) {
  $args[ 'posts_per_page' ] = -1;
} );`
```

**Comment by mardukian** [comment]
Sounds like that could work, thanks heaps for your help.
