### ISSUE TITLE
Search uses a custom $wpdb query to return post IDs and is not filterable

### ISSUE THREAD

**Issue by brandwaffle** [bigcommerce/bigcommerce-for-wordpress#138]
### Expected behavior
During a search, I would expect the 's' parameter to perform a search which could be overridden by other search engines (such as ElasticPress) to provide faster search for large product databases.

### Actual behavior
The BigCommerce plugin overrides the 's' parameter and performs a lookup that attempts to connect to specific posts, first by directly querying with LIKE across the posts table, then adding in some custom BC attributes such as the SKU. While some of this data is stored in meta, the SKU is not. We were able to rewrite the function to use WP_Query except for searching the SKU. If possible, we'd love to have this added into the plugin to support filtering the search through ElasticPress.

As an additional note, the function that connects the products to post IDs empties the 's' parameter rather than removing it, which causes ElasticPress to actually override the query for returning specific post IDs (as it still contains an empty 's' parameter). Unless there's a reason that this query should appear to be a search, I would recommend removing the 's' parameter entirely from the query.

### Steps to reproduce behavior

1. Install BC plugin and ElasticPress
2. Attempt to search on the front end

### Screenshot/Video (if applicable)
N/A

### Workaround or possible solution
This function enables search across all the parameters except the SKU, which is not stored in meta like the bigcommerce_id. Again, unless there's a compelling reason _not_ to store the SKU in meta, we'd highly recommend doing so to achieve consistency with the handling of bigcommerce_id and to enable better WP_Query compatibility.

```
function ep_bc_search_to_post_ids( $search_phrase ) {
    // ID search
    if ( is_numeric( $search_phrase ) ) {
        $search = new WP_Query( array(
            's'          => $search_phrase,
            'fields' => 'ids',
            'meta_query' => array(
                array(
                    'key'   => 'bigcommerce_id',
                    'value' => $search_phrase,
                ),
            ),
        ) );
        return $search->posts;
    }

    // title search
    $search = new WP_Query( array(
        's'      => $search_phrase,
        'fields' => 'ids',
    ) );

    return $search->posts;
}

add_filter( 'bigcommerce/query/search_post_ids', 'ep_bc_search_to_post_ids' );```

**Comment by karen-white** [comment]
Hey @brandwaffle , Thanks for raising this and sharing your solution! This is a good suggestion. We'll get this ticketed for our dev team :)

**Comment by jbrinley** [comment]
@brandwaffle: Could you help me clarify this request?

> As an additional note, the function that connects the products to post IDs empties the 's' parameter rather than removing it, which causes ElasticPress to actually override the query for returning specific post IDs (as it still contains an empty 's' parameter). Unless there's a reason that this query should appear to be a search, I would recommend removing the 's' parameter entirely from the query.

What, precisely, do you need unset, `$query->query_vars[ 's' ]` or `$query->query[ 's' ]`?

The former is set to an empty string for all queries by `WP_Query::fill_query_vars()`. The latter is not, so far as I can tell, used by ElasticPress.

Or do you need `$query->is_search` set to `false`?

I appreciate your help to make sure I get this right.

**Comment by brandwaffle** [comment]
@jbrinley sorry for the delayed reply! It looks like you're correct about the 's' parameter. Let me double-check what exactly is causing EP to take over that query and I'll let you know if any other changes are necessary. It might be that EP is simply taking over the default query on the homepage.

**Comment by topher1kenobe** [comment]
@brandwaffle how did this end up?
