### ISSUE TITLE
Checkout Will Not Load (503)

### ISSUE THREAD

**Issue by Bullseye-Surplus** [bigcommerce/bigcommerce-for-wordpress#139]
### Expected behavior
Checkout to load

### Actual behavior
Blank page

### Steps to reproduce behavior

1. Add product to cart
2. proceed to checkout

### Screenshot/Video (if applicable)
![image](https://user-images.githubusercontent.com/47565132/52640886-95d8b680-2ea5-11e9-882b-c5ff803bbeaa.png)

![image](https://user-images.githubusercontent.com/47565132/52640893-9b360100-2ea5-11e9-832a-c824a39ab336.png)

https://bullseyesurplus.com/products/christensen-arms-ridgeline/?sku=SKU-35874DD2

My first GitHub post :D

**Comment by topher1kenobe** [comment]
Hey there, official support for stuff like this is handled over at https://support.bigcommerce.com/s/group/0F91B000000922sSAA/bigcommerce-for-wordpress

That said, I recently wrote a plugin to fix your specific issue, and I'm curious to see if it works.  I've tested enough to know it doesn't break anything, but you're the first non-working site I've had the chance to fix.

Can you download this plugin: https://drive.google.com/open?id=11dD8055sFwZG5q58r4cfi1qemOIo2xcM

Then go to your homepage and put ?reset_bc_api=yes at the end of your URL?  Then test the cart again.  If I built it right then the cart should be working.  If the cart is NOT working after the plugin, please let me know.

**Comment by Bullseye-Surplus** [comment]
I gave it a shot, no luck.

![image](https://user-images.githubusercontent.com/47565132/52643729-a12ee080-2eab-11e9-9f23-10de13fb2209.png)

**Comment by topher1kenobe** [comment]
Well rats. You should do an official support request at that URL I posted above and we'll figure out if it's the same problem I was working on.

Tell them I think it's an issue with the API losing its connection because of a URL or protocol change.

**Comment by topher1kenobe** [comment]
I suppose I should ask, you also Activated my plugin, right?

**Comment by Bullseye-Surplus** [comment]
Yes, a fair question. I just deactivated it and deleted it though. Did you need it for more testing?

**Comment by topher1kenobe** [comment]
Nope, that was enough, thanks.

**Comment by Bullseye-Surplus** [comment]
https://support.bigcommerce.com/s/question/0D51B000055Mr0rSAC/checkout-will-not-load

Here is the post on the forum you mentioned I should use.

**Comment by topher1kenobe** [comment]
I think I steered you wrong on support, you should post here: https://support.bigcommerce.com/s/contact

Sorry about that!

**Comment by Bullseye-Surplus** [comment]
That page is blank for me lol

![image](https://user-images.githubusercontent.com/47565132/52652663-8e70d780-2ebc-11e9-9007-93b8586faee6.png)

**Comment by topher1kenobe** [comment]
What browser is that?  It's working for me in Chrome and Firefox.  Anything in the console?

**Comment by Bullseye-Surplus** [comment]
Chrome on a Macbook Pro

![image](https://user-images.githubusercontent.com/47565132/52652888-e9a2ca00-2ebc-11e9-8177-b133f57c2a19.png)

**Comment by topher1kenobe** [comment]
Try clicking the Contact link in the top right of that page and see what happens.

**Comment by Bullseye-Surplus** [comment]
Looks like a flyout menu. I've used their chat support many times. The issue is that you cannot directly contact anyone in Tier 2 support (read: the only people who know anything technical about the WordPress integration).

I have several tickets going.

**Comment by topher1kenobe** [comment]
Make a ticket if you can and give me the case number and I'll get it to the right place pronto.

**Comment by Bullseye-Surplus** [comment]
Thanks Topher.

Case Number | 03644480
![image](https://user-images.githubusercontent.com/47565132/52654111-53bc6e80-2ebf-11e9-9d57-b2aed5df10b9.png)


![image](https://user-images.githubusercontent.com/47565132/52654091-4a330680-2ebf-11e9-9c21-a403e28d4437.png)

**Comment by topher1kenobe** [comment]
This was related to WORD-16 and has been resolved.
