### ISSUE TITLE
Hidden Products are imported

### ISSUE THREAD

**Issue by civicpath** [bigcommerce/bigcommerce-for-wordpress#14]
### Expected behavior
Products with 'hidden' visibility in the BigCommerce store should not import through the Wordpress plugin. 

### Actual behavior
All products regardless of visibility are importing. 

### Steps to reproduce behavior

1. Hide a product in BigCommerce
2. Import products in Wordpress. 
3. Note that all products are imported

### Workaround or possible solution
All products imported to Wordpress are initially left in an unpublished state. 
- Not a high priority. 
- May be desired functionality of the developer.

**Comment by karen-white** [comment]
@civicpath Quick update--We're adding a new feature to the BigCommerce UI in the next few days that will allow you to select on a product-by-product basis which products to list to your WordPress channel(s). Closing this out, but please feel free to open a new issue if you have any feature requests related to the new product import process!
