### ISSUE TITLE
Excessive CSS output causing AMP validation error in AMP plugin's Classic mode

### ISSUE THREAD

**Issue by westonruter** [bigcommerce/bigcommerce-for-wordpress#144]
As reported in https://wordpress.org/support/topic/amp-issues-detected/ when in the AMP plugin's Classic mode, BigCommerce is adding 46KB of CSS on its own. The AMP plugin's classic post template has 6 KB, and thus results in a total CSS of 52KB. This is 2KB more than the 50KB limit imposed by AMP, and the result is an AMP validation error.

**Comment by karen-white** [comment]
Thanks for reporting this @westonruter ! (and thanks for the PR :) We'll get this reviewed by the dev team.

**Comment by karen-white** [comment]
After discussing with the dev team, we feel that the best way forward is to drop official support for Classic (reader) mode. Based on articles like [this one from XWP](https://xwp.co/what-you-need-to-know-before-you-amp/), we'd like to steer users toward Native or Paired. We also notice that the error goes away if you aren't logged in or if you hide the admin banner while logged in. We can look at reducing the CSS weight over time, but the admin banner seems like it's just enough additional CSS to cause the error. Closing this in favor of noting this in our documentation for now.

**Comment by westonruter** [comment]
Guiding users to the Native/Transitional modes is what we recommend as well.

Aside: There are some big improvements coming to CSS handling in the plugin:

* https://github.com/ampproject/amp-wp/issues/2326 Discontinue excluding excessive CSS by default on Native mode sites
* https://github.com/ampproject/amp-wp/issues/2322 Prioritize stylesheets to decide which are concatenated and which are excluded
* https://github.com/ampproject/amp-wp/issues/1801 Show notice on frontend when there is excessive CSS
* https://github.com/ampproject/amp-wp/issues/1921 Ignore admin bar for AMP validation purposes

Also, we're considering running the Reader mode templates through the full-page sanitizer which should also fix this issue, as it would include tree-shaking: https://github.com/ampproject/amp-wp/issues/2202
