### ISSUE TITLE
These might be helpful :)

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#15]
We have added a few bits and bobs to the current functionality of the plugin. Most of it I'm sure will be added as dev continues but in the mean time, I thought it might be useful for others to share what we've done.

Just a small, additional plugin to drop in next to the current BC plugin.

The functionality this adds is as follows:

- Adds a UI for the taxonomies imported from BC (probably intentionally left out due to not having the two way sync yet but we needed to use them)
- Remove "category" from the product archive page title
- Adds product options as taxonomies and terms on import/update
- Adds previous terms of taxonomies to the filters available on front end archive page
- Fixes the product option swatch issue when using images as swatches (currently hard coded to #999999)
- Adds a $permalink variable available to the product-card component
- Option to send import debug info via wp_mail()
- Adds further settings to BigCommerce settings page for:
   - Whether or not to show sizes and colours 
    - Username and password for sites behind Basic Auth (BC wont sync products to sites behind basic auth without this)
    - Specify how many products should be assigned to a term to warrant showing it in the filters
    - Automatically set the permalink structure required for BC plugin to work

You can find it here: https://github.com/5874/5874-bigcommerce

:)

**Comment by karen-white** [comment]
Thanks @5874 ! We've bookmarked this and shared your feedback with the dev team.
