### ISSUE TITLE
User Defined Account Sign Up form fields do not show on WordPress register page

### ISSUE THREAD

**Issue by helms** [bigcommerce/bigcommerce-for-wordpress#151]
### Expected behavior
Creating user defined account sign up form fields in BigCommerce should show on the Register page of the WordPress site.

### Actual behavior
The user defined fields are not showing up.

### Steps to reproduce behavior

1.Create users defined fields on the account sign up form in BigCommerce
2.Check Register page in WordPress website

### Screenshot/Video (if applicable)

n/a

### Workaround or possible solution

n/a

**Comment by karen-white** [comment]
Hey @helms , thanks for raising the issue. We'll do some discovery on adding support for custom account signup fields and keep you updated.

**Comment by yuenvision** [comment]
No BC API or webhook exists to support this request at this time. Closing ticket. We may revisit if API support is developed in the future.
