### ISSUE TITLE
issue on Cart-Level Discounts

### ISSUE THREAD

**Issue by kevinmatter** [bigcommerce/bigcommerce-for-wordpress#152]
### Expected behavior
After changing Qty on the cart page, correct pricing show.

### Actual behavior
After changing Qty on the cart page, show "Free"

### Steps to reproduce behavior

1. Add cart-level discounts from BC - Buy one get one free
2. Add product to the cart
3. go to cart page
4. change product Qty

### Screenshot/Video (if applicable)

![Screen Shot 2019-04-09 at 2 17 45 pm](https://user-images.githubusercontent.com/40257373/55777613-c6268500-5ae3-11e9-8749-1ddbe1cfe331.png)

### Workaround or possible solution
N/A

**Comment by karen-white** [comment]
Thanks for reporting the issue @kevinmatter ! We'll get a ticket in to investigate.

**Comment by cpalacio-seeed** [comment]
Hi team, any update of this error?

**Comment by tyla-taylor** [comment]
Addressed in v4.28
