### ISSUE TITLE
Price does not update for Variation Selection

### ISSUE THREAD

**Issue by DigitlDavid** [bigcommerce/bigcommerce-for-wordpress#155]
### Expected behavior
When a variation is selected the price changes accordingly 

### Actual behavior
Price does not change on selection

### Steps to reproduce behavior

1. Assign Variations to a product
2. Select Variations on Product Page

### Screenshot/Video (if applicable)

https://snag.gy/ZTr7oU.jpg

### Workaround or possible solution
There isn't one.

**Comment by karen-white** [comment]
Hi @DigitlDavid , could you confirm that you're on version 2.2.1 of the plugin (the latest version)?

**Comment by DigitlDavid** [comment]
Yes it happened when the update was made

**Comment by karen-white** [comment]
Thanks for following up @DigitlDavid --we're having a tough time replicating the issue. Is there anything in the theme that might be blocking an AJAX call, or any console errors that you can see? Could you provide any details on how the pricing adjustment for that product is structured?

**Comment by sime990** [comment]
Hi @DigitlDavid 
I had a similar issue, it may not be the same for your case but I'll share anyway.

Try to update something else on the product in big commerce i.e. change description THEN re-sync your product to your Wordpress site.  For some reason my product variation prices weren't updating in Wordpress until another change triggered a full re-sync for the products affected.  Quickest way I found was export all products to CSV >> add a space to the start of each description >> re-import to Bigcommerce >> sync to Wordpress.  I do this every time I update option sets / variations to force Wordpress to also update.

**Comment by tyla-taylor** [comment]
Addressed in v4.13.0
