### ISSUE TITLE
Product Limitation Error

### ISSUE THREAD

**Issue by mardukian** [bigcommerce/bigcommerce-for-wordpress#156]
### Expected behavior
When a product has a maximum purchase quantity set in Bigcommerce and a customer tries to add more than the maximum of that product to the cart the customer should receive an error that says "You can only purchase a maximum of <insert maximum product quantity> of the <Insert Product Name here> per order."

### Actual behavior
Customer gets an error that says "There was an error adding this product to your cart" 

The console gives an error POST 502 bad gateway

### Steps to reproduce behavior

1. Limit a product to a maximum amount
2. try to add more than the product limit to the cart

**Comment by karen-white** [comment]
Hey @mardukian , thanks for reporting this. It looks like the BC Cart API that the plugin consumes is returning a 500 in the case that a product doesn't meet min/max purchase requirements, when the API should really be returning a 409 and a more descriptive error message. We've created a ticket under the Checkout engineering team so we can handle that scenario with the proper API response.

**Comment by mardukian** [comment]
Hey There, do we have an ETA on this one, I have a site ready to go live and this affects most of the products in the store. If there is a workaround can you let me know?

**Comment by karen-white** [comment]
Hey @mardukian , we've recently deployed the change on the BigCommerce platform side (to return the proper error code). The last step is to update the behavior of the plugin. I'll follow up when I have an update on that side of things!

**Comment by lukeacl** [comment]
Hey @karen-white, do you have a timeline yet of when this will be fixed? The fault still exists in version 3.1.0.

**Comment by karen-white** [comment]
Hi @lukeacl , during QA, we ran into an edge case where the API would still return a 500 instead of the proper error messaging, and it's setting back our timeline a bit. We're addressing that now, but I'll keep you posted when the update is due to be released in an upcoming version.

**Comment by topher1kenobe** [comment]
@lukeacl @mardukian are you still seeing this behavior?

**Comment by tyla-taylor** [comment]
Addressed in v3.2.0
