### ISSUE TITLE
Missing Products After Import Completed

### ISSUE THREAD

**Issue by mardukian** [bigcommerce/bigcommerce-for-wordpress#157]
### Expected behavior
All products to be imported (Product Count 1460)

### Actual behavior
Missing some products (Actual Products imported 750)

Mostly I'm just wondering if theres an easy way to find out which products weren't imported so I can see what they have in common.

NB: My two largest Categories have 590 and 576 Products in them, both of them capped out at 199. The next largest category is 415 products and it capped out at 176

I have run multiple syncs and get the same results, I suspect theres a reason as to why they're not importing I just can't figure out what that reason is.

**Comment by yuenvision** [comment]
Issue addressed in v3.0.0 release
