### ISSUE TITLE
Avalara Tax not working

### ISSUE THREAD

**Issue by dvrs-brad** [bigcommerce/bigcommerce-for-wordpress#159]
### Expected behavior
Activate and setup Avalara on BigCommerce.  Taxes are now working and no errors messages in the WordPress site.

### Actual behavior
Warning on BigCommerce for WordPress plugin settings stating Checkout functionality will not work until this has been configured in BigCommerce. Taxes have not been set up.  

### Steps to reproduce the behavior

1. Login to the back end of the website
2. Choose the BigCommerce from plugins.
3. The message appears at top of the page.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by dvrs-brad** [comment]
Yes, we have it set up in our big commerce account. However, when I log in to the back end of wordpressr it tells me taxes have not been configured.

**Comment by topher1kenobe** [comment]
This was a bug and has been resolved.
