### ISSUE TITLE
Product Titles Won't Update After Initial Sync

### ISSUE THREAD

**Issue by garrisons** [bigcommerce/bigcommerce-for-wordpress#163]
### Expected behavior
Title on products to be updated after the sync

### Actual behavior
Titles are not updated after the initial sync

### Steps to reproduce the behavior

1. Do initial sync
2. Change the title of a product in big commerce
3. Sync from the WordPress admin panel
4. Product titles aren't updated on the custom post but are updated in the custom field: `bigcommerce_source_data`.

### Workaround or a possible solution
Change the product's title in WordPress manually

**Comment by becomevocal** [comment]
@garrisons Once there is listing overrides for name and description, the core catalog data is ignored. However, in 3.1.0, you can now reset the listing to use the core catalog data if you didn't mean to do that:
<img width="552" alt="Screen Shot 2019-06-06 at 11 25 13 AM" src="https://user-images.githubusercontent.com/2677921/59049577-ec4f7380-884d-11e9-8124-743788d7058d.png">

The action will only show if there is listing overrides.

Could you let me know if this is the case and the action helps fix the issue?

**Comment by garrisons** [comment]
Yes that did address my issue thanks so much!
