### ISSUE TITLE
Cannot Import Products

### ISSUE THREAD

**Issue by mardukian** [bigcommerce/bigcommerce-for-wordpress#164]
### Expected behavior
Should be able to import products after updating the plugin to Version 3.1.0

### Actual behavior
After updating the plugin I get the following error AH01071: Got error 'PHP message: PHP Fatal error: Uncaught BigCommerce\\Exceptions\\No_Task_Found_Exception: No task found to handle state fetching_listing_ids

### Troubleshooting done:
Have already tried removing the plugin and reinstalling, have tried removing all products and reimporting. Have tried connecting with the API as well as with the oAuth login. Get the same error. I do login and choose the channel and then I get the error. If I create a new channel I no longer get the error instead I get sent in a loop and if I go to products I get the error: The site is experiencing technical difficulties.

**Comment by becomevocal** [comment]
@mardukian do you know if you updated the plugin while an import was already running? Looking into this more but this may be the reason based on what I've seen before.

**Comment by mardukian** [comment]
I couldn't say for sure, but its likely. Do we know what the fix is? Is there a way to set it up as new, just dump what was in there and reimport form scratch?

**Comment by becomevocal** [comment]
Yep, if this is the case there are three ways to solve:

1. Deleting the option `bigcommerce_current_import_status_log` manually from the WP DB would clear the state and let it start over.
2. From WP-CLI: `wp option delete bigcommerce_current_import_status_log`
3. Add the following to a functions file then delete that code after loading the admin once:
```
add_action( 'admin_init', function() {
  delete_option( 'bigcommerce_current_import_status_log' );
}, 0, 0 );
```

Let me know if this helps the process!

**Comment by topher1kenobe** [comment]
@mardukian How did this turn out for you?
