### ISSUE TITLE
Issue with NEW Products not syncing

### ISSUE THREAD

**Issue by garrisons** [bigcommerce/bigcommerce-for-wordpress#165]
### Expected behavior
New products successfully sync with WordPress

### Actual behavior
New products don't successfully sync with WordPress

### Steps to reproduce behavior

1. Create a new product in big commmerce
2. Attempt to sync it with WordPress site

### Additional Info
We have two "WordPress channels" in big commerce. Not sure if that could be affecting that?

**Comment by becomevocal** [comment]
@garrisons is your setting in BC4WP for 'automatic sync' under product sync settings set to 'yes'? If it's not, you'll need to use the product list in BC to list those products to the WP site. You can do that by bulk selecting the products using the checkbox and then select the 'list products to channels' bulk action. They'll then be picked up when the site syncs again.

**Comment by garrisons** [comment]
Yes it sure is and the product that won't sync is added to that "channel" and has been. Any thoughts on why this could be happening? We're wanting to launch 10-20 sites with the plugin and are a little concerned by sync not working correctly.

**Comment by becomevocal** [comment]
@garrisons did you end up being able to get this working the way you wanted?

**Comment by garrisons** [comment]
I was able to get this working - It seemed that it had something to do with malformed descriptions? It was all in the error logs, just had to kind of parse it product by product to fix the issues.

It's working now!
