### ISSUE TITLE
Google Analytics Tracking Broken (Cross-Domain Tracking)

### ISSUE THREAD

**Issue by amenityhealth** [bigcommerce/bigcommerce-for-wordpress#167]
### Expected behavior
Prior to switching to the plugin, Google Analytics tracked all visitors and conversions properly by source/medium/campaign. This is clearly important for any online retailer to understand the impact of each digital acquisition channel

### Actual behavior
Even though we have the same GA IN installed (and now sync'd via version 3.1.0) all conversions are being attributed to Direct traffic. GA is tracking all visits properly until the person gets to checkout. GA thinks that all referrals to mystore.mybigcommerce.com/checkout are direct traffic. This is broken with both embedded checkout and non-embedded

### Workaround or possible solution
We have implemented all of GA's instructions on how to handle cross-domain tracking, but it still doesn't work. 

Was cross-domain revenue tracking been tested prior to the release of the plugin? I am not aware of any customizations to our BigCommerce backend or to GA that would have broken this. This is a CRITICAL functionality that nearly all e-commerce companies. need.

**Comment by karen-white** [comment]
Hey @amenityhealth , thanks for reporting the issue--we can create a ticket to investigate. Can you please share your WordPress and BigCommerce URLs?

**Comment by amenityhealth** [comment]
My URLs are:


WP: medcline dot com

BigCommerce: medcline dot mybigcommerce dot com


Aaron Clark

Co-Founder/CEO
aclark@amenityhealth.com<mailto:aclark@amenityhealth.com>
M: 858-232-0012

[email-logo-1502.jpg]
O: 858-605-1747
F: 858-836-5750
www.MedCline.com

________________________________

**Comment by karen-white** [comment]
Thanks @amenityhealth -- I see you have an existing support case for this issue. We'll continue the conversation with you via case 03871813 👍

**Comment by amenityhealth** [comment]
Karen, I know we have an open support case. However, I am wondering if cross-domain tracking is working for any BC4WP sites so I can know if this is a global plugin issue or just with select sites like ours.

**Comment by karen-white** [comment]
Thanks @amenityhealth -- for visibility, we have an engineering ticket where we're tracking reports of inconsistency with analytics tracking, and the support agent you worked with linked your case to that ticket. Our team is in the process of testing to better understand the problem and the best approach to address it. We'll keep you posted on the progress.

**Comment by amenityhealth** [comment]
@karen-white I changed my store name from mystore.mybigcommerce.com to a subdomain of my main site. Now that checkout is on checkout.mystore.com, cross-domain tracking is working.

**Comment by karen-white** [comment]
Thank you for sharing your solution @amenityhealth ! I'll make sure we get that documented. I'm going to close out this issue for now, although we are still tracking an open ticket for improvements to analytics overall. Glad you were able to resolve things on your end!
