### ISSUE TITLE
Add to Cart button disabled upon page load on all products 

### ISSUE THREAD

**Issue by sime990** [bigcommerce/bigcommerce-for-wordpress#168]
### Expected behavior
When a product page is loaded, Add to Card button should NOT be disabled

### Actual behavior
When a product page is loaded, Add to Card button is Disabled

### Steps to reproduce behavior

1. Open any product page e.g. https://peakeatsfood.com/products/vegan-chili/
2. Try to click "Add to Cart"

### Screenshot/Video (if applicable)

http://prntscr.com/o6a338

### Workaround or possible solution
Current workaround is to select a product option, which then enables the "Add to Cart" button.  This is extremely frustrating for users.

Bigcommerce plugin version 3.2.0

**Comment by sime990** [comment]
To anyone else out there that comes across this issue..

`jQuery('.bc-product-form .bc-btn--add_to_cart').prop('disabled', false);`

Will apply a working band-aid,

**Comment by karen-white** [comment]
Thanks for reporting this and sharing your workaround @sime990 . We've got this ticketed as a regression in 3.2.0, and we'll keep you posted on a fix.

**Comment by karen-white** [comment]
Following up on this @sime990 -- we've rolled out a fix with the latest plugin version, 3.4.0. I'm going to go ahead and close this out, but please feel free to re-open if you're still seeing the problem. Thanks again for reporting it, and for posting your workaround in the meantime!
