### ISSUE TITLE
Javascript overrides the theme override back into original product card component when in frontend

### ISSUE THREAD

**Issue by masserra** [bigcommerce/bigcommerce-for-wordpress#169]
### Expected behavior
Javascript should respect the override made at the theme level under the bigcommerce/respective/folder/structure. When doing any sort of filtering and ajax request's it should check for any theme template override.

### Actual behavior
After a lot of time trying to understand why the theme overrides were not working, I came to the conclusion that the javascript is changing everything back to the original component template inside the plugin. After chrome inspecting with view-source:website I saw that it was actually being changed in the end.

### Steps to reproduce behavior
1.  Add the file product-card.php inside /bigcommerce/components/products/ as you would for the usual overriding
2. Remove certain markup for testing
3. Visit your-website.com/products/categories/shop-all/ and see it hasn't changed
4. Now visit url view-source:your-website.com/products/categories/shop-all/ to see exactly the markup that we receive before javascript has had time to do anything and see your changes

**Comment by karen-white** [comment]
@masserra Could you give us a few more details on step 2, 'Remove certain markup for testing'? What markup is being removed? What does the finished template look like?

**Comment by masserra** [comment]
@karen-white Really what I should have said here was: to remove, add or modify. 

So, BigCommerce gives the ability of overriding the original plugin templates. We do so by duplicating the same files in "/our-theme/bigcommerce" folder. Precisely, when I modify the component product-card.php under this folder /components, I found out it seems to be changing when I check under the view-source, just as Googlebot would see, although if viewed normally (/products/categories/shop-all/), the javascript filter function quickly goes and restores back to the product card version from the plugin, so no overrides being respected under the ajax request.

**Comment by michaeldhopkins** [comment]
We have this issue as well. We aren't able to make changes to display of category discounts to line-items (adding strikethroughs of the initial price) because updating quantities will reset the view to the out-of-the-box version, which doesn't have them. It'd be nice to have more control over the template.

**Comment by jayclockwork** [comment]
We have the same issue. We updated the display of line items to support promotions/discounts. The AJAX processing does not honor the override. It would be nice if there was a line item override that was used by both the main template and the AJAX processing.

**Comment by topher1kenobe** [comment]
@masserra @michaeldhopkins @jayclockwork are you still seeing this issue?

**Comment by yuenvision** [comment]
Addressed in v3.14.0 when we enhanced the templates for product cards.
