### ISSUE TITLE
Wishlists & Product Comparisons

### ISSUE THREAD

**Issue by dschwint** [bigcommerce/bigcommerce-for-wordpress#17]
Will wishlists & product comparisons be part of the Wordpress plugin?   These are important to customers.   Thank you!

**Comment by karen-white** [comment]
Following up on this issue--we've delivered Wish Lists in the plugin as of 3.4.0. Will keep this open as a feature request for product comparisons. Thanks again for the suggestions!

**Comment by kaylima** [comment]
Closing this issue as we will not be pursuing product comparisons at this time. Will be revisited in the future if there are additional requests.
