### ISSUE TITLE
Changing categories in BC doesn't change slugs / permalinks in WP after synch

### ISSUE THREAD

**Issue by masserra** [bigcommerce/bigcommerce-for-wordpress#170]
### Expected behavior
When changing the name or erasing a category it should change the slug / permalink or delete it accordingly. And if, only if, it doesn't have the slug available create a category-slug-2.

### Actual behavior
When changing the category's name and synching it changes the name but not the slug. If you try to erase the category in BC it doesn't erase from WP. And when adding it back we end up now with a category-slug-2 / ..-3 / ..-4 etc...

### Steps to reproduce behavior
1. Change category in BC
2. Synch everything
3. Check category's permalink wherever you have a link to that category on the website.
4. Now to try what could be the workaround but it's not, erase the same category on BC
5.  Synch everything
6. Add it back
7. Synch everything 
8. See category slug / permalink not only unchanged but with a new slug-2

**Comment by karen-white** [comment]
Thanks for opening the issue @masserra ! We've created a ticket to address it 👍

**Comment by karen-white** [comment]
@masserra Following up here--this was fixed in the latest version of the plugin, 3.4.0. I'm going to go ahead and close this out, but please feel free to reopen if you're still seeing the problem. And thanks again for letting us know!
