### ISSUE TITLE
Registration form not updating wordpress users "First name" & "Last name"

### ISSUE THREAD

**Issue by projoomexperts** [bigcommerce/bigcommerce-for-wordpress#182]
### Expected behavior
When a visitor register on the website using bigcommerce plugins registration form, the plugin creates a wordpress user using  email and password only.

### Actual behavior
 It does not update the first name and last name of the user from the registration form submission

### Workaround or possible solution

Adding the codes below to 

\wp-content\plugins\bigcommerce\src\BigCommerce\Forms\Registration_Handler.php  line number 51

make sure to sanitize properly.

if ( !empty( $submission[ 'bc-register' ][ 'first_name' ] ) ) {
			update_user_meta( $user_id, "first_name",  $submission[ 'bc-register' ][ 'first_name' ] ) ;
		}
		if ( !empty( $submission[ 'bc-register' ][ 'last_name' ] ) ) {
			update_user_meta( $user_id, "last_name",  $submission[ 'bc-register' ][ 'last_name' ] ) ;
		}

**Comment by tyla-taylor** [comment]
Addressed in v3.7.0
