### ISSUE TITLE
Option to remove login_url redirect

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#19]
We have updated our drop in plugin to include a setting to remove the BC login_url redirect. Reason for this is we want to be able to control whether this is in place or not. Particularly in theme development, forcing admins to log in via the login front end page can be a pain at least and prevent us from logging in at worst (depending on where we are at with the theme dev).

https://github.com/5874/5874-bigcommerce

:)

**Comment by karen-white** [comment]
@5874 Sounds like a good idea for a "developer mode" setting. Thanks for the suggestion!

**Comment by amckemie** [comment]
Thanks for the suggestion! After investigating this, we will not be adding to the core plugin as there are many 3rd party Wordpress plugins that handle this.
