### ISSUE TITLE
Embedded checkout not loading on safari. Issues loading afterpay gateway in chrome

### ISSUE THREAD

**Issue by tcobfitzroy** [bigcommerce/bigcommerce-for-wordpress#190]
### Expected behavior
Embedded checkout to actually work

### Actual behavior
Embedded checkout doesn't load in Safari (across devices).
Console:
Failed to load resource: the server responded https://mydomain.mybigcommerce.com/embedded-checkout with a status of 403 ()

Embedded checkout loads in Chrome however fails to redirect to Afterpay when trying to complete payment. Console returns https://portalapi.afterpay.com/portal/consumers/persistent-login/enforce Failed to load resource: the server responded with a status of 403 ()
{
  "errorCode" : "method_not_allowed",
  "errorId" : "cb6f2163b1a840cf",
  "message" : "Method Not Allowed",
  "httpStatusCode" : 405
}

**Comment by becomevocal** [comment]
@tcobfitzroy the latest version of the plugin should resolve this for you. It's working on a demo store I just setup, on Safari using a Mac and iPhone: https://demo2.cloudwp.dev/trial-zw3449u5

For Afterpay in Embedded Checkout, there is some additional work on our platform side we have to do to support it. Over time we will be working to enable more alternative payment methods within embedded checkout, however If that's key to your flow _now_ I'd suggest redirecting to the full BC checkout under a subdomain of checkout.yourdomain.com, as Afterpay is supported in that environment. Setting up a CNAME for your BC store is how you'd do that and the instructions are here: https://support.bigcommerce.com/s/article/Changing-Domains#point
