### ISSUE TITLE
Webhook Destinations Not Exposed 

### ISSUE THREAD

**Issue by samproc119** [bigcommerce/bigcommerce-for-wordpress#192]
### Expected behavior
Destination urls for receiving  webhooks from BigCommerce store should be exposed when plugin is installed

### Actual behavior
Destination urls are not exposed, and return a 404 error when queried. Inventory updates are therefore not flowing from BigCommerce store -> Wordpress

### Steps to reproduce behavior

1. Fresh install of Wordpress
2. Install BigCommerce plugin
3. Register to store using API Credentials 
4. Allow initial sync to complete
5. Query destination urls which should be available
    a. ex: https://bigcommercewebhooktest.cloudaccess.host/bigcommerce/webhook/inventory_update
6. Error returned in Postman: The requested URL /bigcommerce/webhook/inventory_update was not found on this server.

**Comment by tyla-taylor** [comment]
Addressed in v4.28
