### ISSUE TITLE
Issue with Product Sync

### ISSUE THREAD

**Issue by timpioneermedia** [bigcommerce/bigcommerce-for-wordpress#194]
### Expected behavior
Expecting when product sync occurs that it goes through all 12 steps and displays any new products

### Actual behavior
Stuck on Stage 9 of 12: Fetching product data from the BigCommerce API. Then after 10-20 minutes displays error saying "server is sending an unexpected response"

### Steps to reproduce behavior

1. I've yet to see this issue anywhere in terms of solving it.
2. BigCommerce Display store was shut down for maintenance briefly before error occured and now can't seem to get it back up and running

**Comment by yuenvision** [comment]
Added better sync timeout messaging in v3.21.0
