### ISSUE TITLE
Empty Attachment in Gift Certificate

### ISSUE THREAD

**Issue by tmulry** [bigcommerce/bigcommerce-for-wordpress#197]
### Expected behavior

Order a gift certificate via the BigCommerce store. Your test user should receive an email with an attachment containing the certificate.

### Actual behavior

The email is sent with an attachment.  The attachment is a zero byte file.

### Steps to reproduce behavior

See Above.  Note this bug was found on a production BC store, not in a sandbox environment. It's untested if the API has changed from Prod to the sandbox

### Workaround or possible solution

Gift certificate attachments are populated when ordered via the bigcommerce interface but not via wordpress.

The reason this fails is that the BC for WP plugin is sending the wrong template name to the Cart API. It should be `General.html` not just `General`  
From wp-content/plugins/bigcommerce/src/BigCommerce/Forms/Purchase_Gift_Certificate_Handler.php
```
		$theme  = apply_filters( 'bigcommerce/gift_certificates/theme', 'General' );

```

The workaround is to add a filter 'bigcommerce/gift_certificates/theme' to set the correct template name.

**Comment by yuenvision** [comment]
This was addressed in v4.0.0
