### ISSUE TITLE
?bc-sort=sales does not match product sales rankings in BigCommerce

### ISSUE THREAD

**Issue by michaeldhopkins** [bigcommerce/bigcommerce-for-wordpress#203]
### Expected behavior

I'm expecting that when I visit a product category archive (components/catalog/product-archive.php) with a URL that ends in /?bc-sort=sales, or when I select Best Selling in the dropdown, the products will be ordered from best to least best selling to match the best selling rankings viewable at /manage/analytics/merchandising inside the BigCommerce storefront.

To clarify, these are rendering in the `$posts` loop, not via shortcode.

### Actual behavior

The actual behavior is that the Best Selling view (/?bc-sort=sales) shows a product order that we can't find in BigCommerce. We are unable to find a URL parameter that lists the products in best selling order.

What can we do to troubleshoot this, or is there a workaround available? We are happy to let BigCommerce support look at the account and the site to compare the rankings, and have been talking to them, but we're also pursuing a potential solution here.

We are able to get the correct listing with an API call as well. `https://api.bigcommerce.com/stores/storehashgoeshere/v3/catalog/products?categories:in=68&direction=desc&sort=total_sold`

And we see the same incorrect order when using a shortcode, e.g.:
`[bigcommerce_product category="homemade-in-minutes" order="desc" orderby="sales"]`

**Comment by topher1kenobe** [comment]
This has been proven as a bug and there should be a fix in 3.19.

**Comment by yuenvision** [comment]
Addressed in v3.19.0
