### ISSUE TITLE
AJAX Add to Cart broken in 3.18.1

### ISSUE THREAD

**Issue by jonht** [bigcommerce/bigcommerce-for-wordpress#211]
### Expected behavior
AJAX Add to Cart function is enabled, and should enable products to be added to cart without redirecting to cart page. 

### Actual behavior
Users are redirected to cart page after adding items to the cart.

### Steps to reproduce behavior

1. Choose options and add products to cart here: https://bywordofmouth.co.uk/at-home
2. Note you are redirected to the cart page.

Please can this be fixed ASAP?

**Comment by topher1kenobe** [comment]
Hey @jonht , could you confirm what you have for this setting?

<img width="1341" alt="Screen Shot 2020-05-05 at 10 17 37 AM" src="https://user-images.githubusercontent.com/341412/81076568-c72e0f80-8eb9-11ea-85e0-6747fbb288ab.png">

**Comment by jonht** [comment]
Hi Topher, Thanks for getting back to me so quickly.

See attached, same as your example:
<img width="1128" alt="bc-ajax" src="https://user-images.githubusercontent.com/41949671/81076898-24d75180-8ee4-11ea-9d55-3f8776cebef0.PNG">

**Comment by topher1kenobe** [comment]
Are you running 3.18.1?  I'm seeing proper behavior.  Could you try it with the console open and see if you catch any JS errors?

**Comment by jonht** [comment]
Hi Topher,

Yes we're using 3.18.1, and testing on different machines/browsers. Which browser are you using for proper behaviour?

The only console error is related to CSS, not JS: 

DevTools failed to load SourceMap: Could not load content for https://bywordofmouth.co.uk/wp-content/themes/bwom/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by topher1kenobe** [comment]
I'm using Firefox on MacOS.  Could you try switching the setting, saving, and switching back? I'm wondering if the setting is showing the wrong info because of an old option.

**Comment by jonht** [comment]
I wondered the same, had tried that before, but just tried again and no luck.

Just to be clear, this is specifically for Quick View which is all we're using really. 

I've also disabled all other plugins and tested, with no change.

I've also tried disabling all component overrides, and no luck there either.

Quite a head scratcher.

**Comment by topher1kenobe** [comment]
This won't solve your quick view problem, but are you able to go to a single product page and see if it happens there as well?  Just trying to rule out options.

**Comment by jonht** [comment]
Sure, I meant to say before that the AJAX seems to work fine on a single product page, e.g. this one: https://bywordofmouth.co.uk/products/city-harvest-donation/

**Comment by jonht** [comment]
Hi Topher,

Did you have any luck on your side with this issue?

I've just noticed that in the code, the data-variants attribute string on the product-variants-object div within the form on quickview, seems to have issues escaping the " around the keys and values. An example of what it's currently outputting is: 
`[{&quot;variant_id&quot;:144,&quot;options&quot;:[{&quot;option_display_name&quot;:&quot;Portion Size&quot;,&quot;label&quot;:&quot;2 Portions&quot;,&quot;id&quot;:146,&quot;option_id&quot;:136}],&quot;option_ids&quot;:[146],&quot;inventory&quot;:30,&quot;disabled&quot;:false,&quot;disabled_message&quot;:&quot;&quot;,&quot;sku&quot;:&quot;BWOM-5004-2&quot;,&quot;price&quot;:7,&quot;formatted_price&quot;:&quot;\u00a37.00&quot;,&quot;image&quot;:{&quot;url&quot;:&quot;&quot;,&quot;width&quot;:0,&quot;height&quot;:0},&quot;zoom&quot;:{&quot;url&quot;:&quot;&quot;,&quot;width&quot;:0,&quot;height&quot;:0}},{&quot;variant_id&quot;:165,&quot;options&quot;:[{&quot;option_display_name&quot;:&quot;Portion Size&quot;,&quot;label&quot;:&quot;1 Portion&quot;,&quot;id&quot;:158,&quot;option_id&quot;:136}],&quot;option_ids&quot;:[158],&quot;inventory&quot;:74,&quot;disabled&quot;:false,&quot;disabled_message&quot;:&quot;&quot;,&quot;sku&quot;:&quot;BWOM-5004-1&quot;,&quot;price&quot;:4,&quot;formatted_price&quot;:&quot;\u00a34.00&quot;,&quot;image&quot;:{&quot;url&quot;:&quot;&quot;,&quot;width&quot;:0,&quot;height&quot;:0},&quot;zoom&quot;:{&quot;url&quot;:&quot;&quot;,&quot;width&quot;:0,&quot;height&quot;:0}}]`

Any ideas on how to resolve this?

**Comment by jonht** [comment]
Ignore the above, I now understand that this the escaped template for the quickview.

We were hoping to launch this week, but without this fix I'm not sure.

Any help is greatly appreciated.

**Comment by topher1kenobe** [comment]
I'm tapped out on this one, I'm going to escalate to the engineering team.

**Comment by jonht** [comment]
I understand Topher, thank you. If you could try to mark this as urgent, it'd be really helpful. Thanks

**Comment by topher1kenobe** [comment]
It looks like the template has changed for the archive page, did you make a custom one?  Could you try it with the default and see if it fixes it?

**Comment by jonht** [comment]
Hi Topher, 

Do you mean the catalog/product-archive.php file?

The only difference between our version and the latest was " * @version 1.0.0" in the commented section at the top of the latest template file.

**Comment by topher1kenobe** [comment]
Ugh, different theme too?

**Comment by topher1kenobe** [comment]
Ok, a better ask. Can you try it with the TwentyTwenty theme activated and all other plugins off?

**Comment by jonht** [comment]
No luck with that either I'm afraid!

It seems to be that the plugin ajax add to cart javascript is not picking up that ajax is enabled, on the shortcode grid view only.

The network activity triggered by the button click seems to match the activity shown when it is disabled. 

Hope that helps you and the team.

**Comment by topher1kenobe** [comment]
We can't make it break, could it be you have a bad copy of the plugin? You wouldn't have to Uninstall and Reinstall, if you simply use FTP copy a new version over the old one that would work.

**Comment by jonht** [comment]
I will try that, but seeing as the other site I replicated it on downloaded the plugin from the WP directory, seems unlikely.

**Comment by jonht** [comment]
I've just downloaded the version uploaded here to github, and used it to overwrite the plugin via FTP. No change.

Just to confirm, when you visit https://bywordofmouth.co.uk/at-home/#menu-anchor - click on 'Choose Options' on a product, select an option, and then click 'Add to Cart' - you see it wrongly redirects to the cart page, right?

It's doing that for us on all browsers deviecs and OSs we have.

**Comment by topher1kenobe** [comment]
That is correct, I see the wrong behavior. We'll keep trying to think of a solution. So far it's only you.  :)

**Comment by jonht** [comment]
Agh, how strange... fingers crossed.

**Comment by topher1kenobe** [comment]
Do you happen to have a local dev environment?  Local or DesktopServer? If you could do a quick install on there of a totally fresh version I'd be curious to see if you find it again.

**Comment by jonht** [comment]
I've 'fixed' it.

When I added a new test product that didn't have product options, to the page (with a new shortcode) - either the fact that it didn't have options, or that it displayed the single product view instead of a card, seems to have unstuck something. 

I can now even remove the product, and things seem to keep working.

Any ideas why that is?

VERY relieved to have some form of solution!

**Comment by topher1kenobe** [comment]
That is really weird. I'm assuming you've been logged in at some point and caching wasn't an issue?

**Comment by topher1kenobe** [comment]
Upon further review, I'll bet a LOT there was a caching problem. The code being presented in the browser had a problem, but wasn't being refreshed from the real codebase, so stayed broken.  When you added a new product it probably flushed the cache and we got good code.  What caching solution are you using?

**Comment by jonht** [comment]
AFAIK, there is no server-side caching - not using any plugins or anything. The site is on WP Engine, so not sure if that has something.

However, on further testing it certainly seems that as soon as you have no products on a page that are simple (no-option) products, the ajax functionality stops entirely. Can you pass this on to the team?

I've simply included a dummy simple product and hidden it for now, which does the trick. Would be good to find a real fix though.

Thanks for all your support though!

**Comment by topher1kenobe** [comment]
WP Engine does have built-in server side caching, you should see if you need to whitelist your cart and checkout page.  I'll bet not, because we use the same naming as Woo, but also check the Account page if you're using it.

That's super good info about the product, that's absolutely something we can test and patch.

**Comment by topher1kenobe** [comment]
Could you shoot me an email at topher@bigcommerce.com? I have some unrelated info for you.

**Comment by jonht** [comment]
Done!

**Comment by jonht** [comment]
Hi Topher,

Just a quick note to add that the issue seems to also present itself on the products archive page (which luckily we're not really using). Definitely related to the product options, as page one has no products without options, the ajax doesn't work. Page two does, and so it does work. 

https://bywordofmouth.co.uk/products/

Thanks

**Comment by yuenvision** [comment]
This issue was addressed in [v3.20.0](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/CHANGELOG.md#4191)
