### ISSUE TITLE
Allowing WP Users to Post a Review

### ISSUE THREAD

**Issue by chrishappy** [bigcommerce/bigcommerce-for-wordpress#212]
I am trying show an "Add a Review" on the product single page.

In the settings, we have "Moderation and management of product reviews within WordPress is scoped for future development. Manage reviews in BigCommerce." While we wait, is there any way to implement this with custom code?

In the pull request [Package version 3.12.0 #196](https://github.com/bigcommerce/bigcommerce-for-wordpress/pull/196), we read:

> Fixed the product review form handler to respect the value of the
> bigcommerce/product/reviews/show_form filter that is used when
> displaying the form.

Would this be helpful in showing a reviews form on my Wordpress Site?

**Comment by chrishappy** [comment]
I tried using this code in my template override "single-bigcommerce_product.php" but nothing appeared:

```
echo 'Hello world'; // this shows
echo apply_filters( 'bigcommerce/product/reviews/show_form', '', get_the_ID() ); // Nothing shows
```

**Comment by topher1kenobe** [comment]
Hey @chrishappy, reviews are implemented right now.  Only logged in users can leave reviews. If you'd like to open it up for all people to be able to leave reviews, check this out: https://github.com/becomevocal/bc4wp-turn-on-reviews-for-all

**Comment by chrishappy** [comment]
@topher1kenobe Wow! Thank you for the quick response.

Just to confirm, is the reason why I (the admin) am not seeing a review form is because I am not a verified purchaser?

**Comment by topher1kenobe** [comment]
Yeah, you're not a "customer". If you set up the test payment gateway and buy something then you will be.

**Comment by chrishappy** [comment]
Okay, thank you!

**Comment by topher1kenobe** [comment]
@chrishappy if you don't mind, could you shoot me an email at topher@bigcommerce.com?
