### ISSUE TITLE
Embedded checkout not loading on Safari - Version 3.20.0

### ISSUE THREAD

**Issue by vandyks** [bigcommerce/bigcommerce-for-wordpress#215]
### Expected behavior
Embedded checkout iframe loads on page.

### Actual behavior
Embedded checkout iframe fails to loads.

### Steps to reproduce behavior

Using the Safari browser:
1. Add product to cart
2. Go to cart page
3. Click Proceed to checkout button

### Screenshot/Video (if applicable)

![image](https://user-images.githubusercontent.com/3478184/84326206-0d723080-ab42-11ea-97dd-b835583192c8.png)

**Comment by amckemie** [comment]
@vandyks Can you share a few more details please? Including which version of Safari this was occurring on and if you reached out to BigCommerce support? Thanks!

**Comment by vandyks** [comment]
I have not reached out to BigCommerce support directly about this.

This is actually an issue on two separate websites, with two different BigCommerce stores, using two different hosts, one of which we removed any sort of caching and the other has caching disabled for any user specific pages (account, cart, checkout, etc.).

The Safari version is Version 13.1.1 and the issue occurs for everyone I've had test the issue. In Chrome, the embedded checkout works without issue.

**Comment by yuenvision** [comment]
Since Webkit browsers stopped supporting 3rd party cookies, embedded checkout across different domains stopped working. A subdomain for embedded checkout will resolve this. More info here: https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#subdomain-setup
