### ISSUE TITLE
Issues overwriting templates using the Sage theme

### ISSUE THREAD

**Issue by Shehzad-Abdulcadir** [bigcommerce/bigcommerce-for-wordpress#217]
### Expected behavior
Templates should be overridden.

### Actual behavior
The customised templates default back to the plugin templates

### Steps to reproduce behavior

1. Create new instance of WordPress on local machine.
2. Follow steps [here](https://roots.io/sage/) to generate the Sage starter theme.
3. Install dependancies, activate theme, install BigCommerce Plugin.
4. Create a `bigcommerce` folder in `resources/views/`.
5. Import `archive-bigcommerce_product.php` & `single-bigcommerce_product.php` to folder.
6. Rename files to have the `.blade.php` file extension
7. The templates should be overridden for those two templates.
8. Create `/components/products/` folders
9. Import `product-single.php` & give it the `.blade.php` file extension
10. Make changes to template, the changes will NOT be reflected on the page.

### Workaround or possible solution
Edit theme files directly from the plugin directory.
Store updated template files within theme folder, replace plugin template files after any plugin updates.

Hello,

I hope everyone is keeping safe.

I am currently in the process of creating a headless BigCommerce site using the WordPress plugin and the [Roots](https://roots.io/) stack.

I am aware that the starter theme does things very differently as compared to regular starter themes such as Underscores.

At the moment it seems I can override the templates inside the `/templates/public/` folder in the plugin but not anything inside the `/components/` folder.

Would anyone with a bit more experience with the plugin be able to advise on this please?

Many thanks.

**Comment by topher1kenobe** [comment]
Hi Shez, thanks for writing. Sage isn't supported at this time, but we've created an internal ticket specifically to research this and at least provide guidance on how it can be done.
