### ISSUE TITLE
Cannot update/sync new channel url

### ISSUE THREAD

**Issue by zdlldz** [bigcommerce/bigcommerce-for-wordpress#219]
### Expected behavior

Update channel url in BigCommerce backend by clicking "Sync site url" button within BC4WP plugin settings (/wp-admin/edit.php?page=bigcommerce&post_type=bigcommerce_product) > Diagnostics.

### Actual behavior

Channel url is not updated. 

Proposed solutions in BigCommerce community forums also do not work (ie saving new primary Wordpress site/home url, as mentioned recently in [this post](https://support.bigcommerce.com/s/question/0D54O00006UieZ8SAJ/i-originally-connected-to-bigcommerce-via-the-wp-plugin-while-i-was-designing-this-site-so-it-was-on-a-temporary-url-now-that-we-are-live-im-trying-to-change-the-wp-site-url-in-the-bigcommerce-channel-manager-and-it-will-not-take-the-change), does not update the channel url in BC backend.)

_Possibly related errors/behaviors:_

- User cannot update site url manually in BigCommerce backend's Channel Manager -- the system will allow you to edit and save, but the updates are not actually saved.
- User is unable to actually delete a channel within Bigcommerce backend Channel Manager.
- User is unable to update/add additional channel to any products.

... this all smells related/due to some significant issues with the Channel Manager system.

### Use case

Attempting to take localhost site live onto staging/production servers. Site will continue to sync, but frontend js will throw errors and embedded checkout will not load due to domain mismatch/CORS error.

### Steps to reproduce behavior

1. Go to BigCommerce > Settings
2. Click "Sync site url" button
3. Check BigCommerce backend Channel Manager -- _url will not be updated_.

### Workaround or possible solution

_BigCommerce support has informed me that this (or related) issue is being tracked internally by BigCommerce development team in engineering ticket **word-27**. I'm posting here in an effort to be notified when this issue is fixed._

Fyi several solutions have been mentioned in the community forums. Neither solution has worked for me:

- https://support.bigcommerce.com/s/question/0D54O00006UieZ8SAJ/i-originally-connected-to-bigcommerce-via-the-wp-plugin-while-i-was-designing-this-site-so-it-was-on-a-temporary-url-now-that-we-are-live-im-trying-to-change-the-wp-site-url-in-the-bigcommerce-channel-manager-and-it-will-not-take-the-change
- https://support.bigcommerce.com/s/question/0D54O00006MqthhSAB/channel-url-not-updating-in-channel-manager

**Comment by zdlldz** [comment]
Adding more info/context to help others looking into the same issue.

BC support was able to manually update the channel url via api PUT:

```
PUT https://api.bigcommerce.com/stores/store_hash/v3/channels/channel_id/site

{
	"url": "https://my-new-domain.com"
}

```
Also fyi support indicated:

> This was actually caused by the engineering ticket word-16, and we are working on improving the workflow of changing a channel URL to resolve this.

**Comment by yuenvision** [comment]
BC handled on their end via Channel Management remediation
