### ISSUE TITLE
Option to remove search bar on archive pages

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#22]
We have updated our plugin to include the option to remove the search from the refinery on archive pages. We found that sometimes a theme we have developed already contained a search (in the header for example) and we had no need for another one in the body.

Option in BigCommerce->Settings

https://github.com/5874/5874-bigcommerce

**Comment by karen-white** [comment]
@5874 Thanks for the suggestion! Sounds like a useful enhancement that you've added to your plugin utility.

**Comment by amckemie** [comment]
We will be adding the option to remove the search field from the plugin in an upcoming release.

**Comment by tyla-taylor** [comment]
Added a new customizer option to hide search bar from product archive in v4.4.0
