### ISSUE TITLE
bigcommerce_product shortcode fills the web page with images

### ISSUE THREAD

**Issue by Pleiades** [bigcommerce/bigcommerce-for-wordpress#221]
### Expected behavior

The bigcommerce_product shortcode should display a thumbnail image, product name, brand name, and a link to the product page in a grid format.

### Actual behavior

The images are displayed full page width, all of the alternate images are also displayed, as are the product options and the full product description. 

(See: https://outdoordivas.staging.wpengine.com/ )

### Steps to reproduce behavior

1. Place the shortcode `[bigcommerce_product featured="1" per_page="3" order="ASC" paged="0"]` in a widget area.

### Screenshot/Video (if applicable)

Expected (and previous) appearance: 

http://outdoordivas.staging.wpengine.com/wp-content/uploads/2020/08/Home-outdoor-DIVAS-2020-08-10-12-46-15-scaled.jpg

Current appearance: 

http://outdoordivas.staging.wpengine.com/wp-content/uploads/2020/08/Home-outdoor-DIVAS-2020-08-10-12-39-00-2.jpg

### Workaround or possible solution

None so far.

**Comment by yuenvision** [comment]
We were not able to reproduce this issue on our end across several different themes and I'm seeing what appears to be the correct behavior on https://outdoordivas.staging.wpengine.com/ now. Has this been resolved?
