### ISSUE TITLE
SKU not visible on product page

### ISSUE THREAD

**Issue by rmykolas** [bigcommerce/bigcommerce-for-wordpress#223]
### Expected behavior
If I have a product with variations, I expect to see the SKU on the single product template page, output by the **$sku** variable in product-single.php. It should probably show up only when I selected all the variations because only those exact variations have SKUs set in the BC backend.

### Actual behavior
There is no SKU on the single product page. The **$sku** variable only prints an empty 
`<span class="bc-product__sku"></span> `
element on the page.

### Steps to reproduce behavior

1. Set up a variable product with SKUs on the variations
2. Check the single product page on any BC4WP install

### Screenshot/Video (if applicable)

A quick screen recording of the issue can be found [here](https://gyazo.com/9136661033dd7dea48f5a0812b0eb568).

### Workaround or possible solution
I tried to grab the SKU from the URL since it changes to /products/product-page/?sku=XXXXXXXX on the variation selection, but seemingly due to some browser quirks, only the previous SKU is printed on the page. You can read about this exact issue [on StackOverflow here](https://stackoverflow.com/questions/48239662/javascript-window-location-search-does-not-update).

BC's documentation seems to not have anything specific to this. The closest I could get was [this documentation section on Variations](https://developer.bigcommerce.com/bigcommerce-for-wordpress/extending-the-plugin/customization-guide) - it looks like you're able to access the variation data in some way, but I'm not sure how to proceed to show it on the site.

I wonder if anyone ran into this issue before and had any ideas on how to fix it or at least point me in the right direction? 

Thanks in advance!

**Comment by yuenvision** [comment]
Products that don't have SKU set show an empty span: `<span class="bc-product__sku"></span>`
Selecting variants does not change the SKU display.

In your example, it seems that you're referring to variant SKU not showing with an expectation that the SKU is refreshed on variant change.

Variant SKUs are auto generated and are available in the JS data so this needs to be manipulated via JS.
