### ISSUE TITLE
Visible on storefront BC setting not working properly in WP

### ISSUE THREAD

**Issue by dabrosch** [bigcommerce/bigcommerce-for-wordpress#228]
### Expected behavior
Product does not show on Wordpress storefront when set to not visible in BigCommerce.

### Actual behavior
Product shows on storefront

### Steps to reproduce behavior

1. Have a product visible on the WP side.
2. Go to BigCommerce and make the product not visible for any storefronts.
3. Ensure a product sync occurs on WP and that all caching is off.
4. Go to the product on the WP side and see that it is there (but is not able to be bought).

### Workaround or possible solution
Specifically re-synching that product does nothing, but you can manually unpublish the "post" to hide the product.

**Comment by dabrosch** [comment]
This now appears to be fixed.... odd they didn't reference it when fixing it.

**Comment by topher1kenobe** [comment]
This issue remains unfixed.

**Comment by yuenvision** [comment]
Addressed in v4.3.0
