### ISSUE TITLE
Customer Address Update in WordPress fails to update BigCommerce

### ISSUE THREAD

**Issue by Pleiades** [bigcommerce/bigcommerce-for-wordpress#229]
### Expected behavior

Editing a customer address in WordPress should update that customer's address in BigCommerce. 

### Actual behavior

The information entered at the time of creation remains mostly in effect.

- What displays in the admin archive Customer-->View, and Customer Details is wrong.
- What displays in Customer Address Book and in Customer Address Details is correct.

### Steps to reproduce behavior

1. Using the BigCommerce plugin, create a New Account 
2. Enter company, address and phone detail
3. Under the Addresses tab, click edit. 
4. Change the company, address, and phone detail, then Save.

### Screenshot/Video (if applicable)

![Screen Shot 2020-09-10 at 3 27 01 PM](https://user-images.githubusercontent.com/976543/92808157-1c56c200-f381-11ea-8830-b71b299d2b0d.png)
![Screen Shot 2020-09-10 at 3 46 38 PM](https://user-images.githubusercontent.com/976543/92808186-22e53980-f381-11ea-9ae8-4142db01a9a4.png)
![Screen Shot 2020-09-10 at 3 32 16 PM](https://user-images.githubusercontent.com/976543/92808212-2a0c4780-f381-11ea-9c87-612c10b1b044.png)
![Screen Shot 2020-09-10 at 3 32 48 PM](https://user-images.githubusercontent.com/976543/92808235-30022880-f381-11ea-879f-0f6b93f180fd.png)
![Screen Shot 2020-09-10 at 3 33 13 PM](https://user-images.githubusercontent.com/976543/92808263-37293680-f381-11ea-95d1-8c226e37509f.png)

https://screencast-o-matic.com/watch/cYQ6YoJcG5

### Workaround or possible solution

None

**Comment by topher1kenobe** [comment]
Thanks Nick, I'll run some tests and then make a ticket!

**Comment by tyla-taylor** [comment]
Addressed ini v1.5.0
