### ISSUE TITLE
BC4WP Query Issue: Taxonomies/Product_Cat/Query_Filter.php

### ISSUE THREAD

**Issue by RayeEThompson** [bigcommerce/bigcommerce-for-wordpress#237]
### Expected behavior
Customer Groups should return 200 status codes when listing products to a logged in Customer of a Group

### Actual behavior
Customer Groups return 404 because non-strings are not converted to strings. 

### Steps to reproduce behavior

1.
<img width="640" alt="Screen Shot 2020-10-30 at 9 59 35 AM" src="https://user-images.githubusercontent.com/40927942/98005283-7b9be600-1db6-11eb-8da6-938886e1d9a9.png">

2.

### Screenshot/Video (if applicable)
<img width="640" alt="Screen Shot 2020-10-30 at 9 59 35 AM" src="https://user-images.githubusercontent.com/40927942/98005320-83f42100-1db6-11eb-9ee1-50d150029e78.png">

### Workaround or possible solution
Convert all non-strings to strings

**Comment by tyla-taylor** [comment]
We addressed this in v4.15.0.
