### ISSUE TITLE
Separate components for quick view gallery and single product page gallery

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#24]
Is there going to be the option to have different html for the gallery that appears in the quick view pop up and the gallery on the single product page?

Currently struggling to squeeze the same components in to bootstrap when parent elements are opened and closed in different component files.

I'm sure we can find a way to make it work but it may be helpful to be able to adapt the code depending on where it is displayed.

(also, any update on the gallery bug?)

**Comment by topher1kenobe** [comment]
@5874 This is an excellent question, we're going to look into whether it's already been changed or not, and if not make some suggestions.

Would you actually want a whole new template, or would better css classes be enough to let you manipulate the output with CSS?

**Comment by topher1kenobe** [comment]
Closed due to lack of communication
