### ISSUE TITLE
Shipping Calculator appears when it should not

### ISSUE THREAD

**Issue by topher1kenobe** [bigcommerce/bigcommerce-for-wordpress#243]
### Expected behavior
If the setting in the customizer says the Shipping Calculator is not visible, it should NEVER be visible.

### Actual behavior
When I open the customizer, it appears, regardless of the setting in the customizer.

### Steps to reproduce behavior

1. Go to Cart page with the Shipping Calculator not showing
2. Open the customizer
3. Observe the calculator appear with no further action having been taken

**Comment by yuenvision** [comment]
Thanks! We've ticketed this item for remediation.

**Comment by yuenvision** [comment]
This will be addressed in v4.10.0

**Comment by yuenvision** [comment]
This was addressed in v4.10.0 release
