### ISSUE TITLE
Shipping Claculator cannot be removed

### ISSUE THREAD

**Issue by topher1kenobe** [bigcommerce/bigcommerce-for-wordpress#244]
### Expected behavior
When the Customizer for the Shipping Calculator is set to not display, the shipping calculator should not be displayed.

### Actual behavior
Once the shipping calculator is set to display, it cannot be removed, the setting has no impact.  NOTE: I've observed that the option value is changing properly in the database, the page itself is not respecting the setting.

### Steps to reproduce behavior

1. With the shipping calculator showing, open the customizer
2. Choose the option to remove the calculator
3. Observe it not going away.

### Screenshot/Video (if applicable)

![calculator_not_hiding](https://user-images.githubusercontent.com/341412/100926030-c772a580-34b0-11eb-8fe3-57708a4a43d6.gif)

**Comment by yuenvision** [comment]
Thanks! We've ticketed this item for remediation.

**Comment by yuenvision** [comment]
This will be addressed in v4.10.0

**Comment by yuenvision** [comment]
This was addressed in v4.10.0 release
