### ISSUE TITLE
Shipping Calculator Does Not Pull Correct Shipping Information

### ISSUE THREAD

**Issue by sarahswiftotter** [bigcommerce/bigcommerce-for-wordpress#245]
### Expected behavior
When the shipping calculator is on, it should give the proper options.

### Actual behavior
It is not pulling the correct shipping information. It gives free shipping when the product in the cart doesn't meet the minimum requirements. 

### Steps to reproduce behavior

1. Add an item to the cart. 
2. Click Calculate Shipping.
3. Go into the BigCommerce panel, to Store Setup > Shipping. Under Static shipping quotes, compare those to what show in the cart.
<img width="1126" alt="Screen Shot 2020-12-01 at 10 11 40 AM" src="https://user-images.githubusercontent.com/66274180/100937896-613e5080-34b9-11eb-8af6-20a4a89c6ede.png">
<img width="776" alt="Screen Shot 2020-12-02 at 4 07 00 PM" src="https://user-images.githubusercontent.com/66274180/100937932-6d2a1280-34b9-11eb-96e8-1c7f1be06447.png">
<img width="797" alt="Screen Shot 2020-12-02 at 4 06 53 PM" src="https://user-images.githubusercontent.com/66274180/100937936-6e5b3f80-34b9-11eb-8451-172eab69c040.png">

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by topher1kenobe** [comment]
@amckemie This seems like it should be a blocker for all releases. If it breaks all checkouts then every store is broken.

**Comment by yuenvision** [comment]
Thanks for reporting this! We've ticketed it and will investigate in the upcoming sprint.

**Comment by yuenvision** [comment]
This was addressed in v4.11.0 release
