### ISSUE TITLE
Embedded shopping cart not working after WP 5.6 update

### ISSUE THREAD

**Issue by tr-sean** [bigcommerce/bigcommerce-for-wordpress#246]
### Expected behavior
For the embedded cart to show up.

### Actual behavior
It doesn't show up after updating to WP 5.6

### Steps to reproduce behavior

1. Add product and can view checkout in WP 5.5.3
2. Update to WP 5.6
3. Refresh cart and does not load. Happens on three separate sites, in different browsers, so not a one-off.

Not sure if the new application password feature WP just rolled out has an effect on the embedded cart. Thankfully all of my shops are still in development, but this might be an issue to those who have live stores.

**Comment by topher1kenobe** [comment]
I do not get this behavior, it works swimmingly for me. WP 5.6, Kadence theme, no theme changes. These plugins active:

Add BigCommerce Image Sizes To Media Settings
BigCommerce for WordPress
BigCommerce Product Feature
Featured BigCommerce Product
Get BC4WP Scripts
Simple Menu Delete
Sugar Calendar (Lite)
WP Events Import

**Comment by amckemie** [comment]
It's possible this is related to a bug in BigCommerce, rather than the plugin. @tr-sean do you have multi-currency set up on any of the storefronts you tested this on?

**Comment by tr-sean** [comment]
@topher1kenobe, you're right. It's definitely just me (and probably a few others). I forgot that WP was updating their jQuery and I had de-registered the WP Migrate. Removing that has everything working as it should.

Sorry for the mini-panic!
