### ISSUE TITLE
Getting order info after checkout is completed

### ISSUE THREAD

**Issue by tr-sean** [bigcommerce/bigcommerce-for-wordpress#247]
Is there a way to hook into the `onComplete` method in `EmbeddedCheckoutOptions` function? Or hook into the `EmbeddedCheckoutCompleteEvent` function? I'm looking to gather the order information after a checkout is completed to store data from a specific product (if ordered) under the users information.

I've come across the [Checkout_Complete_Webhook.php](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/216731268865857c0b48d5ef7a07d0a1ba604f6a/src/BigCommerce/Webhooks/Checkout_Complete_Webhook.php) file and not sure how to hook into that after the embedded checkout is completed, if possible.

Also, I've noticed this issue on the community board, but it seems that the order confirmation page when using the embedded checkout is returning a "Cannot start a checkout session with an empty cart" error. Not sure what would be causing this issue or if there's a solution.

Thank you.

**Comment by tyla-taylor** [comment]
This was addressed in v4.11.0 release.
