### ISSUE TITLE
"This product cannot be purchased in my online store"

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#25]
products marked as "This product cannot be purchased in my online store" in BC are being pulled through to WP with the "default price" field and are available to be purchased. Will the plugin respect this setting and either display the specified message (contact our team for pricing etc) or hide the add to cart button, depending on how it's set up in BC?

**Comment by topher1kenobe** [comment]
This is unknown right now, but we'll figure it out and respond as soon as we can.

**Comment by topher1kenobe** [comment]
That switch should not be used for WordPress sites.  Products should be restricted by channel.
