### ISSUE TITLE
Categories do not sync new hierarchy

### ISSUE THREAD

**Issue by ehwarren** [bigcommerce/bigcommerce-for-wordpress#252]
### Expected behavior
Sync Products  - Taxonomy updates in WP.
Move top level categories to be subcategories in BC
Re-Sync Products - Previously created categories should have new updated hierarchy

### Actual behavior
Sync Products  - Taxonomy updates in WP.
Move top level categories to be subcategories in BC
Re-Sync Products - Previously created categories do NOT reflect hierarchy changes in BC.

### Steps to reproduce behavior

1. Create category in BC
2. Sync Products in WP
3. Move category in BC to be a subcateogy
4. Sync Products in WP
5. Note that hierarchy is NOT updated

### Workaround or possible solution
Delete affected categories in WP and then Re-sync Products

**Comment by tophatcc** [comment]
Same problem with importing BC to WP. Products are categorised however the sub categories are not able to be listed in a menu correctly without a lot of work.

**Comment by tyla-taylor** [comment]
Addressed in v4.18
