### ISSUE TITLE
Google Analytics Tracking

### ISSUE THREAD

**Issue by snoroozi** [bigcommerce/bigcommerce-for-wordpress#253]
We have tried everything to get cross domain tracking between our bc4wp and our bigcommerce checkout page.  The problem is that you load the checkout page with script, which doesn't add the tracking parameters to the checkout page url.

This is effectively killing our AdWords conversion data in which we bid via roas, so it is a big problem.

**Comment by tyla-taylor** [comment]
This was addressed in v4.11.0 release.

**Comment by snoroozi** [comment]
@tyla-taylor how was it addressed please.  Should I go back to using default bc analytics integration where you just enter account number?  Google did all kinds of stuff with custom tracking code to try to fix this before so I need to know what was addressed and best implementation.

**Comment by topher1kenobe** [comment]
Additionally, I would like to blog about this.  :)

**Comment by snoroozi** [comment]
@tyla-taylor further I don't see anything in 4.11 release notes.  I see some stuff regarding embedded checkout only which I have no idea why anyone would use if it doesn't work on IPhone safari still. People like losing IPhone customers?

**Comment by topher1kenobe** [comment]
@snoroozi It should work fine on iphone safari, have you seen this? https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#embedded-checkout

It skirts the 3rd party cookie issue that kills Safari.

**Comment by snoroozi** [comment]
@topher1kenobe I don't see anything in that article referencing a fix for the safari issue?
