### ISSUE TITLE
Meta Tags

### ISSUE THREAD

**Issue by snoroozi** [bigcommerce/bigcommerce-for-wordpress#254]
Meta Tags are synced between our bigcommerce and bc4wp.  This needs an option to disable. Even with toast installed only duplicate meta are generated rather than overwriting what has been imported from bigcommerce.

My current solution is to comment out the meta Tags from the plugin with each update which is a pain.

**Comment by yuenvision** [comment]
Hi, @snoroozi,
Can you provide some clarification to which meta tags you're referring to that you're commenting out? 

Also, you mentioned "toast," but we're unfamiliar with that plugin. Can you also provide more context around that?

**Comment by snoroozi** [comment]
@yuenvision Yoast, autocorrect sorry.  I sell same products on my main bc url and wp4bc,  and on my wp4bc site I can't mention certain words for marketing reasons in my meta tags.  So my main site meta tags have to be commented out.  But in general, people need different meta tags for their bigcommerce main url and bc4wp anyway.

Here is the steps I do after every update. 

File public_html/wp-content/plugins/bigcommerce/src/BigCommerce/Post_Types/Product/Seo.php

Simplest solution so far AFTER EVERY UPGRADE

comment this line:

//printf( '<meta name="description" content="%s" />' . "\n", esc_attr( $description ) );

**Comment by tyla-taylor** [comment]
Addressed in v4.31
