### ISSUE TITLE
Image Swap on variation selection not working.

### ISSUE THREAD

**Issue by captivation** [bigcommerce/bigcommerce-for-wordpress#256]
### Expected behavior
When a user selects a different variation (small, medium) a different image should appear as the active slide.

### Actual behavior
On changing the variation, nothing happens.

### Steps to reproduce behavior

1. go to product single
2. select a size
3. image should slide to the image set in my option in bigcommerce.

### Screenshot/Video (if applicable)
I can share a video, however, I don't wish to share that information publicly. 
![Example Image](http://placehold.it/300x200)

**Comment by tyla-taylor** [comment]
Addressed in v4.12.0
