### ISSUE TITLE
BC4WP Categories

### ISSUE THREAD

**Issue by tophatcc** [bigcommerce/bigcommerce-for-wordpress#257]
### Expected behavior
Products and categories to be able to be displayed. Subcategories fall under their respective categories

### Actual behavior
Flat display of items under one menu heading with no subdorectories

### Steps to reproduce behavior

1.
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by stevesilk1010** [comment]
@tophatcc, were you able to get the BC4WP categories to synch up?  If so, what did you do in the plugin or BC to make it work.   I also had that happen to me and started from scratch and NO cateegories or products synced up.

**Comment by tyla-taylor** [comment]
This was addressed in v4.22.0.
