### ISSUE TITLE
On Product Page Gallery: get global swipe variable so I can hook into it to add custom code.

### ISSUE THREAD

**Issue by captivation** [bigcommerce/bigcommerce-for-wordpress#258]
I'm reviewing the documentation here, https://swiperjs.com/swiper-api#events

I'm trying to add logic to add Next and Previous buttons to the product slider. I found that you have the styling in place, but don't include options (that I could find) to hook them in.

Can you provide me a way to hook into the javascript option instance for the Swiper instance for the product slider?

Or, add options to include those?

**Comment by tyla-taylor** [comment]
You can target an instance by getting the wrapper and then adjusting your options. See this link: https://swiperjs.com/swiper-api#initialize-swiper
