### ISSUE TITLE
Product card images not resizing & overflowing containers

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#26]
Sporadically, images in product cards do not resize resulting in this:

<img width="1274" alt="screen shot 2018-07-17 at 09 20 09" src="https://user-images.githubusercontent.com/22817625/42805082-c3b61bcc-89a2-11e8-8abc-70513b627977.png">

Seems to be to do with the order of scripts kicking in.

Do you know when we might expect this to be fixed please? :)

Thanks a lot

:)

**Comment by topher1kenobe** [comment]
@5874 is this still an issue?  If so, can you provide a link to a page where it's happening?  Thanks!

**Comment by topher1kenobe** [comment]
Closed due to lack of communication
