### ISSUE TITLE
Product Images not showing up on Checkout

### ISSUE THREAD

**Issue by bc-hnbarr** [bigcommerce/bigcommerce-for-wordpress#261]
Issue found on store: https://gocarbon.co/ 
### Steps to reproduce behavior
1. Add any item to cart
2. go to checkout page

### Screenshot/Video (if applicable)
<img width="1129" alt="Screen Shot 2021-03-29 at 11 04 09 AM" src="https://user-images.githubusercontent.com/75996329/112866098-04c1fb00-907f-11eb-87b3-5271e3c2a710.png">
<img width="1073" alt="Screen Shot 2021-03-29 at 11 03 11 AM" src="https://user-images.githubusercontent.com/75996329/112866099-055a9180-907f-11eb-8e31-3eea3b1e97e4.png">

![Example Image](http://placehold.it/300x200)

**Comment by yuenvision** [comment]
Resolved by checkout team at BC
