### ISSUE TITLE
Add alert to pagination setting when Divi is active

### ISSUE THREAD

**Issue by topher1kenobe** [bigcommerce/bigcommerce-for-wordpress#262]
### Expected behavior
When I set the number of products to appear in the store archive, the archive should respect that number and make that many appear.

### Actual behavior
Divi uses its own setting for number of items in an archive, so the WordPress setting is ignored. The average store owner doesn't know this, and is frustrated that the setting in the Customizer isn't working.

### Steps to reproduce behavior

1. Install Divi
2. Try to change the number of products appearing on the storefront archive page using the default tool in the Customizer.

### Workaround or possible solution
1. Test for the Divi setting in the options table
2. Test to see if the Divi plugin or theme are active
3. Either make the customizer field affect that field, OR make a nice red warning that the store owner needs to go into the Divi settings to make the change.

**Comment by amckemie** [comment]
@topher1kenobe What is the experience like to do this: "store owner needs to go into the Divi settings to make the change"? Wondering if that's possible, if we can just add this to BC4WP documentation.

**Comment by topher1kenobe** [comment]
Yeah, specifically Divi/Theme Options/General/ We could make a link directly to it.  I think documenting it is great, but people are going to first get frustrated, second post online or ask support, and only read the docs when pointed there.  I'd like to preempt that process by linking to something or saying something IF the need is there.

**Comment by tyla-taylor** [comment]
Addressed in v4.31
