### ISSUE TITLE
Number of Items in Cart

### ISSUE THREAD

**Issue by M-R-Graham** [bigcommerce/bigcommerce-for-wordpress#265]
### Expected behavior
After a person has checked out, and then clicks Continue Shopping, the cart should be emptied and the icon should not display a number.

### Actual behavior
After a person has checked out and then clicks Return to Shopping, the cart number icon shows the same number of items in the cart as before checkout. The only way to "zero this out" or remove the icon, is to add another item to the cart, which resets the icon number.

### Steps to reproduce behavior

1. Add item to cart, checkout.
2. Click Return to Shopping
3. See icon, it still shows item number indicating items in cart.
4. Refreshing does not fix, refreshing cart does not fix. Only adding an item to the cart resets the icon number.

### Screenshot/Video (if applicable)

https://www.loom.com/share/8dc52037a01a4521910d0839e85af175

![Example Image](http://placehold.it/300x200)

**Comment by sarahswiftotter** [comment]
Yes, I've seen this happening too.

**Comment by yuenvision** [comment]
The plugin adds the cart count to `.bigcommerce-cart__item-count`   [here](https://github.com/moderntribe/bigcommerce/blob/1bf5e7495c301c5af13f05659fece30ec9dfe548/assets/js/src/public/cart/cart-menu-item.js#L15) which we expect to be rendered on page load, however on the Nordic site the class is rendered after page load causing a race condition which results in the count not being updated.

[Rendered HTML ](http://p.tri.be/TGYTWz)
[Computed HTML](http://p.tri.be/5hrwsm)

Note: It appears that the site has de-enqueued the `wp_setup_nav_menu_item` hook defined in [Container/Cart.php](https://github.com/moderntribe/bigcommerce/blob/1bf5e7495c301c5af13f05659fece30ec9dfe548/src/BigCommerce/Container/Cart.php#L42)
