### ISSUE TITLE
BigCommerce's login doesn't respect the redirect setting that WordPress login uses

### ISSUE THREAD

**Issue by slewisma** [bigcommerce/bigcommerce-for-wordpress#269]
### Expected behavior
If I pass a safe redirect parameter to the login page, the user should be redirected to that URL on successful login. I need to do this from buttons we put on product pages to "Login to see Pricing". We want to bring them right back to the product they were viewing after they login this way. We need to use the BigCommerce login because they may need to register if they don't already have an account. Otherwise we would just avoid your login and use the WordPress login instead. 

### Actual behavior

When I set the redirect the way that I would with WordPress' login, it is passed through properly but then the BigCommerce login overrides it and sends the user to their profile page on successful login. 

### Steps to reproduce behavior

1. Setup a redirect filter (see https://developer.wordpress.org/reference/hooks/login_redirect/ )
2. Try logging in via the BigCommerce login page / form
3. See if the redirect works. In my case it does not, no matter what priority I set for the filter. Instead I always end up on the user's BigCommerce profile page.

### Workaround or possible solution

I have not found the code that is overriding the redirect. I have confirmed that the redirect filter gets set and survives going to the login page so something is changing it after that happens. Either changing the BC4WP plugin behavior so that the redirect to the profile page only happens when no other redirect filter is set or equipping it with its own redirect parameter of some sort would solve the issue. My preference would be the former so that normal WordPress redirect filtering can be used.

**Comment by bc-hnbarr** [comment]
Hi @slewisma, When you use the WordPress login, it does create a BC user as well. Have you tried logging in via the WP login page/form?

**Comment by slewisma** [comment]
If I login at .../wp-admin the redirect to the profile still happens so I don't think it matters which login form/page we use. BC is doing the redirect to profile regardless and I can't seem to override it with a filter hook.

**Comment by bc-hnbarr** [comment]
@slewisma -- Thank you for that! We are trying to narrow it down now! Could you try to manually add the "redirect_to" parameter to the url directly rather than using the filter, and let us know if the issue persists.

**Comment by slewisma** [comment]
I've tried it as URL parameter too. Same result. Not 100% convinced there isn't something in our site doing this other than BC4WP so I'm searching the code of all plugins and the theme today to see if I can find any other cause.

**Comment by yuenvision** [comment]
Will investigate for v4.14.0

**Comment by tyla-taylor** [comment]
Addressed in v4.14.0
