### ISSUE TITLE
Flatsome Theme Version: 3.13.0 mini cart doesn't display with bc4wp plugin.

### ISSUE THREAD

**Issue by cbennetvet** [bigcommerce/bigcommerce-for-wordpress#271]
### Expected behavior

Flatsome Version: 3.13.0 mini cart should show using the bc4wp plugin.

### Actual behavior

Flatsome Version: 3.13.0 mini cart doesn't work at all.

### Steps to reproduce behavior

1. install latest version of theme 3.13.*

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by tyla-taylor** [comment]
Addressed in v4.18.
