### ISSUE TITLE
Update file version numbers when files change

### ISSUE THREAD

**Issue by acasperw** [bigcommerce/bigcommerce-for-wordpress#274]
https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/c23c0330bb02789d38303681a8e007853d367371/templates/public/components/cart/cart.php#L13

This file was updated to include the` $coupon_code` however its version was left at @version 1.0.0

**Comment by yuenvision** [comment]
Thanks for noting this. We'll get that updated and add it to our code review process to ensure these version numbers are updated in the future.
