### ISSUE TITLE
$coupon_code is not available in cart-footer.php

### ISSUE THREAD

**Issue by acasperw** [bigcommerce/bigcommerce-for-wordpress#275]
I wanted to move the coupon section from sitting above in the cart.php wrapper, to the cart footer in a side by side layout with the cart summary, however, when i try to `<? echo $coupon_code; ?>` here, nothing is outputted 

https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/c23c0330bb02789d38303681a8e007853d367371/templates/public/components/cart/cart-footer.php#L8

**Comment by acasperw** [comment]
Is there some other way this is available within this template that i am missing?

**Comment by yuenvision** [comment]
Will investigate for v4.14.0

**Comment by yuenvision** [comment]
Hi, @acasperw,
The `$coupon_code` var is no longer available in the cart-footer.php template. We'll remove it from the template description and update the template version number. 

If you want to add the coupon_code var to the cart-footer template, here is how to do it:

```
add_filter( 'bigcommerce/template=components/cart/cart-footer.php/data', function ( $data, $template, $options ) {
    if ( get_option( \BigCommerce\Customizer\Sections\Cart::ENABLE_COUPON_CODE, false ) === 'yes' ) {
        $component = \BigCommerce\Templates\Cart_Coupon_Code::factory( [
            \BigCommerce\Templates\Cart_Coupon_Code::COUPONS => $data['cart']['coupons'],
        ] );
        
        $data[ \BigCommerce\Templates\Cart::COUPON_CODE ] = $component->render();
    }

    return $data;
}, 10, 3 );
```
