### ISSUE TITLE
$cart is available in cart-footer.php but not documented

### ISSUE THREAD

**Issue by acasperw** [bigcommerce/bigcommerce-for-wordpress#276]
`@var array  $cart` should be added to `cart-footer.php`, as it is available , but not immediately clear to an external developer 

https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/c23c0330bb02789d38303681a8e007853d367371/templates/public/components/cart/cart-footer.php#L6

**Comment by tyla-taylor** [comment]
Addressed in v4.17
