### ISSUE TITLE
Shared Modifier Options Break the Product

### ISSUE THREAD

**Issue by sarahswiftotter** [bigcommerce/bigcommerce-for-wordpress#277]
The Shared Modifier Options worked until the latest version of 4.12.0. 
<img width="1150" alt="ModifierOptionon4411" src="https://user-images.githubusercontent.com/66274180/120231938-11e29e00-c218-11eb-87c5-f8168b9cc83d.png">

When you go to add a product to your cart which has a modifier option, the Add to Cart button is grayed out. You can not add the product to your cart.

<img width="1068" alt="ModifiedOptionon4120" src="https://user-images.githubusercontent.com/66274180/120231953-1ad36f80-c218-11eb-9885-e12dd187d2bf.png">

Prior to this, on 4.11.0, you could select the option, and click the Add to Cart button.

The only way to fix is it roll back to 4.11.0. I tried deleting the options, adding them back in, etc. Nothing works.

This is a major issue, because we have several products where they must select an option.

**Comment by tr-sean** [comment]
Apologies for the useless reply, but yes...we faced the same issue. Had to roll back to 4.11.0 as well.

**Comment by tr-sean** [comment]
Any update and/or response on this would be nice, considering the plugin is partially broken in 4.12.0.

**Comment by tyla-taylor** [comment]
This was addressed in v4.13.0 release.

**Comment by tr-sean** [comment]
Can confirm this is fixed in 4.13.0. Thank you.

**Comment by sarahswiftotter** [comment]
This isn't fixed in 4.14.0
<img width="1199" alt="Screen Shot 2021-07-19 at 8 54 45 PM" src="https://user-images.githubusercontent.com/66274180/126250436-731ef398-6b49-4c0a-88c5-d688510a60a6.png">
<img width="1177" alt="Screen Shot 2021-07-19 at 8 54 23 PM" src="https://user-images.githubusercontent.com/66274180/126250441-45766e14-6b10-426e-97cb-85b974246f86.png">
