### ISSUE TITLE
Shipping Calculator Doesn't Work for International Calculations

### ISSUE THREAD

**Issue by sarahswiftotter** [bigcommerce/bigcommerce-for-wordpress#278]
As a customer, when I see the Calculate Shipping option, I would assume this would work for an international address if the company ships to that.

When I select International Shipping, it actually shows as $0, which seems to the customer as if I'm offering it at no cost. That is an incorrect assumption. 

1. Add a product to your cart. 
2. Click Calculate Shipping.
3. Choose International Shipping. It will show $0.
<img width="479" alt="Screen Shot 2021-05-31 at 2 08 01 PM" src="https://user-images.githubusercontent.com/66274180/120232735-c29d6d00-c219-11eb-9e63-354bec44bb56.png">

The only way for a workaround is to disable the shipping calculator. I feel like it would be a useful calculator, but because of the international calculation bug, we can't use it until that's fixed.

You can see also based on my screenshots that I do have International Shipping on the BigCommerce admin side configured.
<img width="789" alt="Screen Shot 2021-05-31 at 2 23 26 PM" src="https://user-images.githubusercontent.com/66274180/120233661-f5486500-c21b-11eb-99d2-e3dccc245613.png">
<img width="768" alt="Screen Shot 2021-05-31 at 2 24 01 PM" src="https://user-images.githubusercontent.com/66274180/120233663-f6799200-c21b-11eb-80f3-e60b1bbb5744.png">

**Comment by yuenvision** [comment]
Will investigate for v4.14.0

**Comment by yuenvision** [comment]
Hi, @sarahswiftotter, digging into this issue, there are many reasons that you could see a $0 International rate quote in the calculator. Do you have a current store that exhibits this issue right now that we can look into?

**Comment by tyla-taylor** [comment]
Addressed in v4.31
