### ISSUE TITLE
Bulk Pricing rules in checkout

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#28]
Hello there :)

As we are currently unable to add more than one of a product to the cart (no quantity field on the single product page yet), we are testing bulk pricing in the basket.

It would seem that the event attached to typing in a new quantity works well.

However, using the increment arrows within the quantity field in the basket does not consistently work. It appears that the event attached to the arrows only uses the last assigned bulk price rule, rather than looking up the relevant price for the current quantity.

I'm sure this will be fixed when the quantity field is added to the single product page but just wanted to flag as we're really needing this to work at the moment! :)

Thanks a lot! :)

**Comment by karen-white** [comment]
@5874 Sorry for the late response on this. Testing seems to confirm that this works now that the qty field has been added to the product page. I'm going to close out for now, but please reopen if you're still seeing the issue.
