### ISSUE TITLE
Reviews on BigCommerce Headless custom template.

### ISSUE THREAD

**Issue by itsjeffreyab97** [bigcommerce/bigcommerce-for-wordpress#280]
I am trying to get reviews showing on a custom template I am building. I can get some functionality like submitting reviews to BigCommerce. 

I can not get the number of reviews, star rating and reviews to populate for the correct product. 

https://juggernaustg.wpengine.com/profile/juggernaut-case-apple-iphone-12-impct-phone-case/

**Comment by madeline-graham** [comment]
Hi @itsjeffreyab97!

I used native WP comments for reviews, and https://wordpress.org/plugins/stars-rating/ < this plugin to implement a star rating and average star rating system! Not sure if that's helpful, I don't know exactly what is supposed to work out of the box.

Madeline

**Comment by bc-hnbarr** [comment]
Hi @itsjeffreyab97, here's another plugin that may be helpful: https://github.com/becomevocal/bc4wp-turn-on-reviews-for-all

**Comment by itsjeffreyab97** [comment]
@madeline-graham @bc-hnbarr Thank you for your help! I found / created a solution that works very well. I think I will be implementing this on all of my BigCommerce Headless sites. 

https://juggernaustg.wpengine.com/profile/juggernaut-case-apple-iphone-12-impct-phone-case/

**Comment by bc-hnbarr** [comment]
Oh nice, what was the solution you went with? It could be helpful to others if you wouldn't mind sharing! :)

**Comment by bc-hnbarr** [comment]
> @madeline-graham @bc-hnbarr Thank you for your help! I found / created a solution that works very well. I think I will be implementing this on all of my BigCommerce Headless sites.
> 
> https://juggernaustg.wpengine.com/profile/juggernaut-case-apple-iphone-12-impct-phone-case/

Oh nice! Glad to hear that! What was the solution you went with? It could be helpful to others if you wouldn't mind sharing! :)
