### ISSUE TITLE
Intermittent failure to load embedded checkout in Firefox

### ISSUE THREAD

**Issue by BenButterfield** [bigcommerce/bigcommerce-for-wordpress#281]
### Expected behavior

In Firefox, add a product to the cart, go to checkout and see embedded checkout when it is enabled.

### Actual behavior

When checkout is visited, the spinner appears but then a JS error occurs and the checkout screen is blank: https://gyazo.com/515024c27dd639a491daf783d363cee3

This was tested by multiple Slack channel members on Friday and the issue was found. Today, the issue did not occur for me until about 19:15 UK time, but is present now.

### Steps to reproduce behavior

1. Head to tomfoolerylondon.co.uk in Firefox
2. Add a product to the cart
3. Go to checkout
4. Intermittently, you will see this: https://gyazo.com/515024c27dd639a491daf783d363cee3

### Screenshot/Video (if applicable)

https://gyazo.com/515024c27dd639a491daf783d363cee3

### Workaround or possible solution

I have not found a workaround or possible solution.

**Comment by tyla-taylor** [comment]
Hi @BenButterfield, are you still experiencing issues with embedded checkout not loading? Thanks.

**Comment by tyla-taylor** [comment]
This looks to be an error coming from within the Checkout SDK itself. This will need to be addressed with the AUS team that handles the SDK at BigCommerce.
