### ISSUE TITLE
Password Reset Doesn't Work After Account Created in BigCommerce Redirected Checkout Page

### ISSUE THREAD

**Issue by madeline-graham** [bigcommerce/bigcommerce-for-wordpress#286]
### Expected behavior
When a customer creates an account from the BigCommerce checkout page, then returns to the WP front end, they should be able to use the password reset functionality and reset their password.

### Actual behavior
When a customer creates an account on the BigCommerce checkout page and then tries to reset their password from the WP front end, they are not seen as a recognized user.

### Steps to reproduce behavior

1. Go to redirected checkout without being logged in.
2. Click Sign in Now and then click Create an Account.
3. Create an account.
4. After checkout, click Continue Shopping.
5. Go to Login and attempt to reset the password before logging in.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

### Workaround or possible solution
We have currently removed ability to create an account from the checkout page. This is not ideal!

**Comment by tyla-taylor** [comment]
Addressed in v4.17
