### ISSUE TITLE
Load More on Reviews not working

### ISSUE THREAD

**Issue by theanswer026** [bigcommerce/bigcommerce-for-wordpress#288]
### Expected behavior
More reviews will be loaded when you click load more

### Actual behavior
Giving this error:
There was an error processing your request. Please try again.

### Steps to reproduce behavior

1. Add Reviews section on wordpress via shortcode on product page
2. View Reviews
3. Click "Load More"

### Screenshot/Video (if applicable)

https://www.screencast.com/t/rLztXBi4Fd7

**Comment by tyla-taylor** [comment]
Upon further investigation, this appears to be an issue with the BC Reviews API response.

**Comment by kcfgl** [comment]
@tyla-taylor Do you have a resolution here? The issue is still happening. I have contacted BC support many times without any movement from Tier 2 support or the company responsible for managing the plugin. Do you have a workaround by any chance?  Thanks!
