### ISSUE TITLE
Search by SKU

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#29]
Currently a user can search for a product by SKU on BC.

Do you know when we might expect this functionality within the WP plugin?

We have a client specifically asking for this functionality from WP as their customers tend to search for their products by SKU.

We can probably implement a solution ourselves but would rather not invest time in a feature that will be solved with an imminent release.

Thank you! :)

**Comment by karen-white** [comment]
@5874 Thanks for the suggestion! We'll keep this in mind as a feature request.

**Comment by tyla-taylor** [comment]
Added the ability to search by SKU in v2.0.0
Added new sort options on Product Archive: by SKU and by Inventory Count in v4.4.0
