### ISSUE TITLE
Is there a Search / Sort / Filter feature that can be added via shortcode?

### ISSUE THREAD

**Issue by theanswer026** [bigcommerce/bigcommerce-for-wordpress#290]
### Steps to reproduce behavior

1.
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by kaylima** [comment]
Hello! 

Yes, there are shortcodes for:

search - A search string to match against product titles, BigCommerce product IDs, or SKUs
order - Whether to sort products in "ASC" or "DESC" order
orderby - Which field to use for sorting. Accepts any field that WP_Query accepts (e.g., title, date)

For documentation on all short codes, please [go here](https://github.com/bigcommerce/bigcommerce-for-wordpress#shortcodes).
