### ISSUE TITLE
WordPress 5.8 - No matching template error

### ISSUE THREAD

**Issue by tr-sean** [bigcommerce/bigcommerce-for-wordpress#291]
Upon updating to WordPress 5.8 this afternoon, none of the product pages worked any longer. I am using the template override for our design and on every product page, we are seeing the "No Matching Template" error. To test, I disabled the template override's to just use the default BC templates and still receiving the same error.

### Expected behavior
To be able to see the product page design.

### Actual behavior
Getting the "No Matching Template" error on every product page.

### Steps to reproduce behavior

1. Upgrade to WordPress 5.8
2. View product page

### Workaround or possible solution
Downgrade to WordPress 5.7.2

**Comment by topher1kenobe** [comment]
I've confirmed it on a clean install with the Kadence theme, no custom templates.

**Comment by drahija-gli** [comment]
Confirming the issue here as well. Currently working on a site that's not in production, but noticed the same behavior.

**Comment by ovogit** [comment]
Confirming this issue as well. Had to rollback to 5.7 until this gets resolved. The only thing that changed on my sites was a wordpress version update to 5.8 from 5.7.

**Comment by snoroozi** [comment]
What's the status on this? Holding off on wp 5.8 until I here it works with bc4wp, as it's my main production site.

**Comment by snoroozi** [comment]
Anyone home?

**Comment by bc-hnbarr** [comment]
Hi everyone! We’re plan to release v4.14.1 soon, to be compatible with the latest version of WordPress 5.8 as the PCLs and PDPs are broken. We’re aiming for this version to be released by end of day today, so keep a lookout on the changelog, or this repo for v4.14.1. Thank you!

**Comment by tr-sean** [comment]
Can confirm the update has fixed the template issue. Thanks, guys!

**Comment by snoroozi** [comment]
I'm running the update with 5.8 with no issues on production for past few
days.

**Comment by tyla-taylor** [comment]
Issue addressed in v4.14.1
