### ISSUE TITLE
Product brands not being assigned

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#30]
Whilst some products have their brand assigned correctly within WP, most do not.

The brands themselves are pulled through to WP but products are not correctly assigned to them.

For example, we have a brand with 221 products assigned to it in BC. In WP, the brand exists but has 0 products assigned to it. The same goes for many other brands with products associated in BC but not in WP.

Any ideas?? 

:)

**Comment by topher1kenobe** [comment]
It looks like this may have been fixed in recent plugin versions, could you let us know if you're still seeing it?

**Comment by topher1kenobe** [comment]
Closing.
