### ISSUE TITLE
Transient bccustomervisibleterms Option persisted with WP_Error

### ISSUE THREAD

**Issue by gclift** [bigcommerce/bigcommerce-for-wordpress#304]
### Expected behavior
If an error exists in the \BigCommerce\Taxonomies\Product_Category\Group_Filtered_Terms::set_transient function, the transient should not be set. There are dozens of possible reasons the "Invalid Taxonomy" WP_Error is added to the $visible_terms and caching the WP_Error object in the bccustomervisibleterms option makes the sites unusable. 

### Actual behavior
If an "Invalid Taxonomy" WP_Error object is held in the $visible_terms variable, the plugin is adding the serialized WP_Error object into the bccustomervisibleterms option.

### Steps to reproduce the behavior

1. Cause an Invalid Taxonomy WP_Error for a bigcommerce_category taxonomy

### Example of value being persisted
```
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`)
VALUES
	(895, '_transient_bccustomervisibleterms1', 'O:8:\"WP_Error\":3:{s:6:\"errors\";a:1:{s:16:\"invalid_taxonomy\";a:1:{i:0;s:17:\"Invalid taxonomy.\";}}s:10:\"error_data\";a:0:{}s:18:\"\0*\0additional_data\";a:0:{}}', 'no');
```

### Workaround or a possible solution
Delete the _transient_bccustomervisibleterms%d (replace %d with user id) row from the wp_options table.

**Comment by tyla-taylor** [comment]
Address in v4.20.0
