### ISSUE TITLE
Product inventory not updated if changed from BigCommerce

### ISSUE THREAD

**Issue by usamaibrahim93** [bigcommerce/bigcommerce-for-wordpress#305]
### Expected behavior
With the webhooks enabled in BC4WP, the product inventory level in WordPress should be getting updated if the inventory is updated in BigCommerce (assuming inventory is being tracked on variant level)

### Actual behavior
Variant inventory updates are not being reflected at all on WP.

### Steps to reproduce behavior

1. Create a product with variants in BigCommerce and keep the inventory tracking to variant level. Sync the product to WordPress.
2. Now update the inventory level of any of the variants in BigCommerce and watch for inventory level in WordPress. It won't get updated.

**Comment by tyla-taylor** [comment]
Addressed in v4.20.0
