### ISSUE TITLE
Product images not always updating when product variants are selected

### ISSUE THREAD

**Issue by chrism-uh-k-AW** [bigcommerce/bigcommerce-for-wordpress#308]
### Expected behavior
Product with variants created in BigCommerce.  Image added in Options & SKUs section.  Show a different image rule created. Product Sync run. User selects product variants on the front-end.  Product image displayed is updated to the image assigned in BigCommerce SKU/Show a different image BigCommerce rule for this product variant/SKU.

### Actual behavior
Product image does not change.

### Steps to reproduce behavior

1. Create a product in BigCommerce with product variants (e.g., length and color).
2. Add SKUs with image in Options & SKUs section.
3. Create a Show a different image rule.
4. Run Product Sync in WP.
5. Select product variants on the front-end.

With similar products (products with variants, SKU with image added, Show a different image rule) this sometimes reproduces the behavior - [totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-simplex-fiber-optic-patch-cable/](http://totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-simplex-fiber-optic-patch-cable/)

Other times works as expected - [totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-duplex-fiber-optic-patch-cable/](https://totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-simplex-fiber-optic-patch-cable/)

I deactivated all plugins and tried with different themes (Shoptimizer and Twenty Twenty) with the same results.  I submitted an issue at BigCommerce for WordPress community and they asked I submit it here. 
### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by frg-tech** [comment]
Hi,

This seems related to the issue I'm having so I thought I'd add on here. In my case I am using the Wordpress plugin for "Simple Blogging" vs the "Full Featured Store" option. This is just to display a "Product of the Day" with our daily blog post.

 
What I have found is that pictures do not show at all for a product if it has **ANY** variant images attached. As soon as I remove all variant images, I am able to see the base images.


So for now I've had to go back and remove all variant images for products I want to display on my Wordpress site. This breaks functionality and has created a good bit of unnecessary work.

 Reproduction is straightforward

1. Add image to a product variant in BigCommerce
2. Sync to Wordpress
3. Add product to a post using **BigCommerce Products Block**
 ![POD_no_image](https://user-images.githubusercontent.com/84391379/137970245-adc2d5e6-8d4e-470a-8faa-5ecdddb05041.jpg)

Removing variant images returns block to expected behavior. (Other than the ability to have variant specific images of course)

**Comment by sz-mn** [comment]
I'm having the same issue as @chrism-uh-k-AW.  

We also have an issue where the product image does not change when variants are selected.  The only image that shows up is the thumbnail image.

Here is how the variants are set up:
![variants](https://user-images.githubusercontent.com/92826517/137990377-8ca1eb71-6a23-40a9-920f-1b8da670f985.jpg)

Here's a video of the issue happening.  You can see the URL changing as I select different variants and the price changes where applicable.  The image just doesn't change to what is uploaded for that variant. - https://share.vidyard.com/watch/guRPhM2E856ajMjSA5k6V3?

I'd appreciate any help I can get so we can get our website working properly!

**Comment by frg-tech** [comment]
So now I am finding products where the images aren't showing even thought I have no variant images attached. I'll try to investigate further as to why, but here is what I have so far.

Here is the product in BC
![BC4WP_Missing-Images](https://user-images.githubusercontent.com/84391379/141514540-3770835a-32f0-4058-9375-1a4efc913994.jpg)

Here is the variant portion of the product without images.
![BC4WP_Missing-Images-2](https://user-images.githubusercontent.com/84391379/141514636-33f10500-f631-4abf-8b38-844a0784a748.jpg)

Here are the images in the Media Library on WP, indicating they were transferred properly to WP.
![BC4WP_Missing-Images-3](https://user-images.githubusercontent.com/84391379/141514738-d9062932-7c75-4e2c-a2ac-402273636055.jpg)

...and lastly, the product listing on WP.
![BC4WP_Missing-Images-4](https://user-images.githubusercontent.com/84391379/141514789-cd3c01cf-08a8-4695-9a58-d95a3c7875ad.jpg)

I'll report back if I find anything. 
Also, please let me know if this should be its' own issue and I'll report it.

Thanks

**Comment by chrism-uh-k-AW** [comment]
@frg-tech @sz-mn, looks like the issue was addressed in the 4.20.0 release on 11/9.  According to the changelog:

- Fixed product images switch when the user selects the variant. The corresponding image of the variant will be displayed
- Fixed the inventory updates via webhook. The inventory level should be updated when it is changed on the BC side whether a product or variant tracking is enabled.

I confirmed on our site the images are now changing when product variants are selected.  Thanks to the developers here!   

Although our inventory count is not updated when the product variant is selected.  According to the change log this was corrected, however on our site inventory counts are not updated when product variants are selected.  For example: [totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-simplex-fiber-optic-patch-cable/](totalcablesolutions.com/products/fiber-optic-cables-panels-os2-9-125-singlemode-simplex-fiber-optic-patch-cable/)

**Comment by sz-mn** [comment]
Thank you to everyone who helped get this resolved!  Our site is working correctly as well now.

**Comment by chrism-uh-k-AW** [comment]
@sz-mn, do you have "track inventory by options" turned on for products in BigCommerce?  If so, is the inventory count updated when a user selects product options?  On our site, the inventory count displayed on the product page is not updated when product options are selected.

**Comment by sz-mn** [comment]
@chrism-uh-k-AW, we don't.  Most of our products are made to order so we don't have inventory tied to our site.

**Comment by tyla-taylor** [comment]
Addressed in v4.20.0
