### ISSUE TITLE
Persistent error being generated from core plugin files

### ISSUE THREAD

**Issue by usamaibrahim93** [bigcommerce/bigcommerce-for-wordpress#318]
### Expected behavior
We are using BC4WP version 4.19.1 on WordPress 5.8.1 and PHP 7.4.25

### Actual behavior
Our error logs are being flooded with the same warning over and over again.

### Screenshot/Video (if applicable)
![image](https://user-images.githubusercontent.com/43200423/142446671-2a124a7e-19f4-48e8-a15b-8039a311bcb4.png)

**Comment by tyla-taylor** [comment]
Addressed in v4.22.0
