### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function 

### ISSUE THREAD

**Issue by fredi54** [bigcommerce/bigcommerce-for-wordpress#32]
### Expected behavior
Open website and access backend.

### Actual behavior

Installed plug in and added API information and got error message.

Fatal error: Uncaught Error: Call to undefined function BigCommerce\Import\Runner\wp_unschedule_hook() in /home/bannerworld/public_html/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Runner/Cron_Scheduler.php:21 Stack trace: #0 /home/bannerworld/public_html/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Runner/Cron_Monitor.php(43): BigCommerce\Import\Runner\Cron_Scheduler->schedule_next_import() #1 /home/bannerworld/public_html/wp-content/plugins/bigcommerce/src/BigCommerce/Container/Import.php(51): BigCommerce\Import\Runner\Cron_Monitor->check_for_scheduled_crons() #2 /home/bannerworld/public_html/wp-includes/class-wp-hook.php(296): BigCommerce\Container\Import->BigCommerce\Container\{closure}() #3 /home/bannerworld/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 /home/bannerworld/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/bannerworld/public_html/wp-settings.php(448): do_action('init') #6 /home/bannerworld/public_html/wp-config.php(92): in /home/bannerworld/public_html/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Runner/Cron_Scheduler.php on line 21

### Steps to reproduce behavior

1. http://bannerworld.printsafe.net
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by karen-white** [comment]
This should now be fixed. Closing out this issue, but please feel free to reopen if you're still running into the error.
