### ISSUE TITLE
Meta Title and Description not showing on category pages

### ISSUE THREAD

**Issue by AktivStudios** [bigcommerce/bigcommerce-for-wordpress#328]
### Expected behavior
The meta title, description are not showing for category pages. We are using a Timber-based theme. 

### Actual behavior
Category pages don't import category metadata. The post data doesn't display the BigCommerce category data even though these sections are filled in within the BigCommerce admin.

### Steps to reproduce the behavior

1. I did a var_dump on the returned BigCommerce data and the fields for meta title and description are blank. The terms data also shows nothing for categories.

**Comment by snoroozi** [comment]
You'll get better seo with yoast as a workaround...

**Comment by yuenvision** [comment]
Yes, @snoroozi is correct. Page meta values in the BC admin are really intended for Stencil platform customizations, but our plugin is not scoped to import that data via the Catalog import and print it to your WordPress templates. 

From a headless perspective, that is better managed within your WordPress CMS and Yoast is a fine path for handling that.
