### ISSUE TITLE
Transfer Cart To Main Bigcommerce Hosted Store

### ISSUE THREAD

**Issue by snoroozi** [bigcommerce/bigcommerce-for-wordpress#329]
### Expected behavior
Add link from wp to bc site and cart items should be transferred

### Actual behavior
Cart is empty on bc site.

### Steps to reproduce behavior

1. If we initiate a checkout on hosted bigcommerce checkout (which is my setup).  Then later if customer switches to the BC hosted site the cart contents are there on that site as well.
2. If I add a simple link from my wp to bc site, then customer starts with a clean cart.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

### Workaround or possible solution
What I would like to do is to be able to provide a link so the customer can switch from our wp hosted site to our bc hosted site and keep the contents of their cart.  Reason being is that our wp version of the site is simply a subset of products from our main bc hosted site.  There are complex reasons why we have this setup, but my ultimate goal is to convert those customers to using our main bc hosted site which has more offerings.  Due to our vertical I can not point ads to my main bc site due to content violations.   

Our email provider, omnisend, has a landing page signup form, that redirects users after subscription to whatever site you want them to.  So here I would like to add a link that switches the customer to our main bc site and retain cart contents.  There is not opportunity for js or anything to do something like your checkout button does.

Anyway, I hope there is some workaround, maybe a url parameter that can transfer the cart.

**Comment by amckemie** [comment]
We are investigating this issue in our upcoming sprint, starting 3/7

**Comment by yuenvision** [comment]
@snoroozi The feature you're describing is called Persistent Cart. At present, the Persistent Cart feature is not supported by the BC4WP plugin. This is listed in the [Persistent Cart FAQ](https://support.bigcommerce.com/s/article/Persistent-Cart?language=en_US#faq). 

We'll investigate a bit further to see if the Checkout API will allow us to support this feature, though transcending carts between different Channels may not be possible. If it is, it would still require that your store subscription meet the necessary [requirements](https://support.bigcommerce.com/s/article/Persistent-Cart?language=en_US) of Plus, Pro, or Enterprise to enable Persistent Cart. 

For now, I'm going to close this issue, but we will continue to investigate to see if we can add this feature.
