### ISSUE TITLE
Product Images changing based on colour option selection

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#33]
Hello!

Currently, when selecting a colour option on a product, the image does not update to reflect the selection as it does on BC.

When might we expect to see this functionality please?

:)

**Comment by karen-white** [comment]
@5874 Still something we'd like to add in the future. Thanks for adding your suggestion to help us frame the priority.

**Comment by AktivStudios** [comment]
Is this feature supported yet?

**Comment by tyla-taylor** [comment]
Addressed in v4.12.0
