### ISSUE TITLE
Image Zoom Bug

### ISSUE THREAD

**Issue by Chromaside** [bigcommerce/bigcommerce-for-wordpress#336]
Having issues with the image zoom feature in Wordpress. 

### Expected behavior
Image zooms in on roll-ver

### Actual behavior
Image zoom frame appears for a split second on initial roll-over. No frame appears after first glitch. Problem goes away if I shrink the image container from 512px to >300px. 

No obvious console errors

Product page for example: https://worknplayclothing.ca/products/carhartt-rugged-flex-fitted-mesh-back-cap/

### Steps to reproduce behavior

1. However image, see frame appear then dissapear
2. Use inspector in image frame (.swiper-slide) and reduce max-width to see image zoom work correctly

**Comment by alexdelgado** [comment]
Hi @Chromaside - looks like the issue is that you have `max-width: 510px;` set on `.bc-product-gallery__image-slide img` in `/themes/work-n-play-clothing/style.css?ver=4.14.8`. If you remove the `max-width` the image zoom works as expected.
