### ISSUE TITLE
[Bug for Register New Account] Address attribute fields added by BigCommerce do not appear on the signup form.

### ISSUE THREAD

**Issue by WebcrazyDylan** [bigcommerce/bigcommerce-for-wordpress#339]
### Expected behavior
The address attribute field added by BigCommerce should appear on our WordPress website just as it appears on our native website.

### Actual behavior
Address attribute fields added by BigCommerce do not appear on the signup form.

### Steps to reproduce behavior

1.  BigCommerce Admin Panel for adding address attribute field
     Login with BigCommerce Admin Panel > Advanced Settings > Address Fields tab > Create a New Field
![Step 1](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061637/1_BC-Add-Account-addressFields.png)

2. you can see new address attribute field on your native website when you see register form
![Step 2](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061632/2_BC-Native-StoreFront-SignupForm.png)

3. However, the added address attribute field is not visible in the storefront implemented with WordPress.
![Step 3](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061634/3_BG4WP-WordPress-StoreFront-SignupForm.png)

### Screenshot/Video (if applicable)

![BigCommerce Admin Panel for adding address attribute field](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061637/1_BC-Add-Account-addressFields.png)

![You can see new address attribute field on your native website](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061632/2_BC-Native-StoreFront-SignupForm.png)

![Added address attribute field is not visible in the storefront implemented with WordPress](https://renu-wp-b2c-media-uat.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/5/2022/03/25061634/3_BG4WP-WordPress-StoreFront-SignupForm.png)

### Workaround or possible solution
It should work normally like the BigCommerce native storefront.

**Comment by yuenvision** [comment]
This isn't so much a bug as it is that the feature and setting isn't supported by the plugin... yet. As such, this is more of a feature request. 

I've written a ticket for us to look into this feature and add support for the plugin to pull in those custom fields defined by the BC admin. There is an API we can lean on for that data. We'll also need to surface these custom fields and values in the My Account section. We'll dig into it in the next sprint.

**Comment by tyla-taylor** [comment]
After looking into this issue, we are not able to support this feature because the API doesn't surface the custom fields until a new customer registration uses the new field that has been created. 

We also are unable to control the order of these fields.
