### ISSUE TITLE
Is the Plugin Compatible with Varnish?

### ISSUE THREAD

**Issue by snoroozi** [bigcommerce/bigcommerce-for-wordpress#340]
### Expected behavior
To work with varnish

### Actual behavior
seems to be working, but want to be sure it's supported

### Steps to reproduce behavior

1.  Please just put in documentation if varnish is supported out of the box or not, and what if any exclusions need set.
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by yuenvision** [comment]
We will conduct some testing this sprint and pass along documentation/recommendations to BC to publish

**Comment by yuenvision** [comment]
@snoroozi our initial tests with various configurations of Varnish indicate that it can disable wp_cron, which will also disable the product importer. If you are able to set up a [server-side cron](https://developer.bigcommerce.com/bigcommerce-for-wordpress/ZG9jOjQ1MjA3MTQ2-creating-reliable-cron-jobs) to bypass wp_cron, that may be a path forward. 

All other features within the plugin appear to work as-expected with Varnish running. 

If you see that your importer will not pass through Step 1 of the process, you can verify if wp_cron is working or not by testing with [WP Control](https://wordpress.org/plugins/wp-crontrol/).
