### ISSUE TITLE
Sync stalled on step 1, wont restart after aborting, and log doesn't have any information

### ISSUE THREAD

**Issue by ll-r-magner** [bigcommerce/bigcommerce-for-wordpress#342]
### Expected behavior
Sync to execute

### Actual behavior
Stalling on step 1, used the abort sync button in diag, still stalling. Have not changed any code on our site. 
Plugin logging shows the sync starting and thats it.

### Steps to reproduce behavior

1. We have no idea.
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by yuenvision** [comment]
We are presently investigating this issue and have been able to reproduce it on a single instance. Can you please provide diagnostics output and error logs?

**Comment by yuenvision** [comment]
This sounds like your wp_cron may not be running on your instance. Can you please install [WP Control](https://wordpress.org/plugins/wp-crontrol/#description) and verify that the cron tasks are successfully running?
