### ISSUE TITLE
Synchronize Password is not checked when customer synced over from BC via customer webhook

### ISSUE THREAD

**Issue by vaskargit** [bigcommerce/bigcommerce-for-wordpress#344]
### Expected behavior
When a customer is synced from BC via customer webhook, the synchronize password option should be selected. So the customer can login to the site using the same password.

### Actual behavior
Currently synchronize password is not checked when synced over BC, so the customer has to set the password using forget password. 

### Steps to reproduce behavior

1. Create a new customer on the bigcommerce and then synced that to wordpress
2. Try to login with the password set on the bigcommerce when creating the customer.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by yuenvision** [comment]
We will investigate this in the current sprint.

**Comment by tyla-taylor** [comment]
Addressed in version 4.28
