### ISSUE TITLE
BigCommerce - Can't write a review on wordpress front end

### ISSUE THREAD

**Issue by launchandscale** [bigcommerce/bigcommerce-for-wordpress#345]
Hello!

We've enabled our wordpress store to be able to have non-customers write reviews manually. On the big commerce side, it works, but on WordPress front-end, we're not manually write a review.

You can watch the first 60-seconds of this video to see the issue:

<img width="1067" alt="Screen Shot 2022-04-08 at 9 53 45 AM" src="https://user-images.githubusercontent.com/103264743/162449985-028b3029-637b-4565-be8f-491d8f1a3b1d.png">

**Comment by tyla-taylor** [comment]
Hi @launchandscale, the file you provided is a picture. Can you try resending the video and could you provide a link to the site where you are having the issue? Thank you!

**Comment by tyla-taylor** [comment]
Addressed in v4.31
