### ISSUE TITLE
Bigcommerce not syncing with Wordpress Site

### ISSUE THREAD

**Issue by CNCGroup** [bigcommerce/bigcommerce-for-wordpress#346]
We have an issue with our wordpress plugin, plugin is up to date but is only syncing 9 out of over 1700 products, spoken to Bigcommerce support on numerous occasions but aren't getting anywhere, get suggestions such as "Try in incognito" 

When the Sync runs it see's it as complete and returns no error code, simply says "9 Products Successfully Synced" If we go to the our Bigcommerce account all 1700 products are assigned to this channel, with 9 products that have synced we can't see any noticeable difference between them.

Interestingly if I try to renew API keys and enter them manually I get a whole bunch of errors, the only way was to use the "Log in to Bigcommerce" button to link the wordpress site with Bigcommerce.

Things we have tried so far:
Reinstall plugin (Bigcommerce insisted this had to be done)
Unassigned all products then reassigned in Bigcommerce to try force a sync
Tried every combination of having Webhooks enabled, classic import, batch sizes, sync frequency
Unassigned products from the channel so there is less products to sync.

Any help would be appreciated before I pull out what hair I have left, this has been on going for over 5 days and cost thousands in revenue.

**Comment by DEIJasonP** [comment]
I'm just here to add my +1 to this issue. We've been experiencing the same problem, though we're only getting 10 products synced out of 347. This seems to have started with the 4.26.1 update.

**Comment by CNCGroup** [comment]
Interesting, I've spoken to about 5 different support reps, tier 2 support reps gotten nowhere so far apart from answered the same questions over and over, not one person has said it's a global issue - had we known that we could have looked into the possibility of a plugin roll back

**Comment by yuenvision** [comment]
I've ticketed this issue on our end as a high-priority issue and we'll investigate this in the current sprint.

**Comment by DEIJasonP** [comment]
Thank you, Paul!

**Comment by DEIJasonP** [comment]
I'm happy to report that I just installed 4.27.1 and was able to sync all products without issue. Many thanks to the development team!

**Comment by tyla-taylor** [comment]
Thank you for reporting back @DEIJasonP. We will go ahead and close this issue out.
