### ISSUE TITLE
Search results only return one product per page

### ISSUE THREAD

**Issue by DEIJasonP** [bigcommerce/bigcommerce-for-wordpress#352]
### Expected behavior:
When using the search function within the site, multiple results should show per page.

### Actual behavior:
Only one product shows per page, even if there are several results. If there are any pages mixed in with the results, they show on the first page, directly after the first product. The second page of results is the second product result. The third page is the third product, and so on.

### Steps to reproduce behavior:

1. Visit https://deipowersports.com/
2. Click the magnifying glass in the top right corner.
3. Enter the word "wrap" and hit enter.
4. See a results page with 117 results. The first page has a Black Titanium 2"x50' roll as the first result followed by 9 site page results. The second page is a 2"x100' roll only. The third page is a 2"x15' roll only. And so on.

### Workaround or possible solution:
No workaround or possible solutions known at this time. It is unknown when this started.

**Comment by tyla-taylor** [comment]
@DEIJasonP this is likely related to the category is_visible flag, and we will ticket for an upcoming release.

**Comment by tyla-taylor** [comment]
Addressed in v4.29
