### ISSUE TITLE
Embedded checkout doesn't work when cart page is disabled

### ISSUE THREAD

**Issue by BCDamian** [bigcommerce/bigcommerce-for-wordpress#356]
### Expected behavior
The embedded checkout works on a store even if the cart page is disabled. 

### Actual behavior
The embedded checkout doesn't work on a store when the cart page is disabled (turns into a redirected checkout).

### Steps to reproduce behavior

1. Set up a working embedded checkout on a store
2. Disabled the cart page

### Workaround or possible solution
This was noted as intended behavior and the only way around the embedded checkout issue is to enable the cart.

**Comment by tyla-taylor** [comment]
Addressed in v4.30
