### ISSUE TITLE
Cart totals are not updating on quantity change

### ISSUE THREAD

**Issue by AlexKonoplyanko** [bigcommerce/bigcommerce-for-wordpress#359]
### Expected behavior
Cart item quantity change should update cart item total, cart subtotal/tax/total

### Actual behavior
Cart totals are not updating on quantity change

### Steps to reproduce behavior

Used latest BigCommerce for WordPress plugin version 4.28.0 and default Twenty Twenty-Two theme to reproduce that issue. 

1. Add some product to cart
2. Go to cart page
3. Change cart item quantity
4. As result sub-total, total and cart item total are not updating

### Screenshot/Video (if applicable)

https://drive.google.com/file/d/10mRfhHt0Q5hQJJqpibqk6kwmmpztgohP/view?usp=sharing

### Workaround or possible solution

Only page refresh updates total

**Comment by tyla-taylor** [comment]
Addressed in v4.31
