### ISSUE TITLE
Users that were registered via WordPress have no details and address info on WordPress/BigCommerce after update to version 4.28.0

### ISSUE THREAD

**Issue by AlexKonoplyanko** [bigcommerce/bigcommerce-for-wordpress#362]
### Expected behavior
Customer profile details and address should be stored on WordPress and BigCommerce side.

### Actual behavior
Customers that was registered on WordPress side have no details and no address on WordPress/BigCommerce

### Steps to reproduce behavior

1. Register customer on WordPress side
2. Login with that customer on WordPress side
3. As result no details are stored which was added while registering and no address information is stored.

https://prnt.sc/matnWe7_l5Gy
https://prnt.sc/_7zi_undKoaw
https://prnt.sc/axrfhTCGBAYj
https://prnt.sc/EZ9IAojsgx89

### Workaround or possible solution
Revert to 4.27.0 version, since that issue was caused by change in most recent release 4.28.0

Removal of that part caused that issue ->
https://prnt.sc/AKH8sPig_Wlv

**Comment by tyla-taylor** [comment]
Addressed in v4.32
