### ISSUE TITLE
WordPress won't sync with BigCommerce

### ISSUE THREAD

**Issue by stacyssensorysolutions** [bigcommerce/bigcommerce-for-wordpress#366]
### Expected behavior
WordPress will regularly sync with BigCommerce and automatically import new products and update any changes to older products.

### Actual behavior
The import is completely frozen, and nothing is being imported or updated.

### Steps to reproduce behavior

1. Go to the BigCommerce tab on the WordPress dashboard
2. See that the import loading wheel is frozen in place and isn't actually importing anything

### Screenshot/Video (if applicable)

https://prnt.sc/BcgZFcyJXTCv

### Workaround or possible solution
Unknown

**Comment by mohitrana324** [comment]
#bigcommerce import stuck
delete 'bigcommerce_current_import_status_log' key from wp_options table

**Comment by tyla-taylor** [comment]
Addressed in v4.32
