### ISSUE TITLE
store.kaplanclinic.com - Unable to view products not-tracking inventory within WP category

### ISSUE THREAD

**Issue by jake-denham** [bigcommerce/bigcommerce-for-wordpress#367]
### Expected behavior
Products that are not-tracking inventory within BigCommerce display as available at the storefront category pages within WordPress

### Actual behavior
Products that are not-tracking inventory are not visible within WordPress category pages

### Steps to reproduce behavior

1. Confirm product is not tracking inventory within BigCommerce such as https://store.kaplanclinic.com/products/tru-niagen-pro-500mg-30/
2. View category containing product within WordPress

### Screenshot/Video (if applicable)

[Image of Product not-tracking inventory](https://bit.ly/3bZ46qT)
[Image of product at WordPress storefront](https://bit.ly/3AvYIWv)
[Image of category containing product](https://bit.ly/3OXTbwo)

### Workaround or possible solution
Thread discussing this behavior: https://bigcommerce.slack.com/archives/C7XEZCSBF/p1656699600061159

**Comment by tyla-taylor** [comment]
Addressed in v4.32
