### ISSUE TITLE
siebert-inc.mybigcommerce.com - Renaming WordPress channel no longer allowing product syncs

### ISSUE THREAD

**Issue by PepeBCPSE** [bigcommerce/bigcommerce-for-wordpress#368]
**Expected behavior**
WordPress will regularly sync with BigCommerce and automatically import new products and update any changes to older products. 

Also, renaming channel for WordPress was completed by client before this import issue began. 
Presently under Channel Manager> in Bigcommerce, there is no Storefront domain listed for WordPress channel.

**Actual behavior**
The import is process does not complete, getting stuck at various steps.

**Steps to reproduce behavior**
Go to the BigCommerce tab on the WordPress dashboard
See that the import loading wheel is frozen in place and isn't actually importing anything

**Screenshot/Video (if applicable)**
![image](https://user-images.githubusercontent.com/91344405/178267424-4928d05d-2e60-4f21-9993-537a8af8e161.png)

**Workaround or possible solution:**
n/a

**Comment by tyla-taylor** [comment]
Addressed in v4.32
