### ISSUE TITLE
FACET WP compatibility issue with BC Pricing API

### ISSUE THREAD

**Issue by jamescscotlightdirect** [bigcommerce/bigcommerce-for-wordpress#371]
Facet WP no longer support compatbility with BC4WP as there has been too many issues over the years. This leaves the plugin with no solid facet solution any longer. If this plugin is going to continue it would be good for Modern Tribe to work on a Big Commerce Facet plugin that is updated with the main BC4WP plugin as going forward if further compatibility issues are faced e-commerce sites are going to find it very diiffult to keep going with the plugin. 

The pricing API is not triggered when a facet is selected unless you refresh the page or when you move to the second page. Is there a fix that could be put in place that would some how trigger the pricing API when a facet is selected?

Example below - Please select any facet and you will notice no pricing will load on the first page until the page is either refreshed or second page is selected. 

https://www.scotlightdirect.co.uk/products/categories/designer-ceiling-lights/

**Comment by yuenvision** [comment]
Faceted search is not presently supported in the plugin due to the complexity of pricing and the potential of scaled customer group pricing against catalog size. Adding faceted search capabilities is not on our roadmap at the time of this writing, so this would require custom development. 

We can help recommend agencies, to assist, if that is desired.

**Comment by jamescscotlightdirect** [comment]
Hello @yuenvision 

Thank you for your reply. From day one Topher and BC have always said that the only reason that there was not a facet solution in place or was on the development roadmap was that facetwp supported the plugin. Are they are aware that they no longer support this as they still promote this through the BC4WP website? I understand the customer pricing issue but disabling the price facet for logged in customers would be a solution as things like colour, size, brand, etc are just as important. An e-commerce plugin without a facet solution is a problem and yes we could develop something ourselves however we do see this as a very basic part of the package we currently pay for with BC.
