### ISSUE TITLE
Fallback pricing does not have tax inclusion/exclusion 

### ISSUE THREAD

**Issue by jamescscotlightdirect** [bigcommerce/bigcommerce-for-wordpress#375]
Hello, 

Not sure if this is a bug or feature request however it would be really great if a fix could be put in place as it would resolve the pricing delays loading on our website when we only have the API pricing enabled. 

The fallback price which is synced over to Wordpress does not have a tax inclusion or exclusion setting, however the API price does. This means that when both stored sync price and API price is enabled the page will firstly come up with the stored sync ex TAX VAT price and then switch to the API inc VAT price if this is your setting. 

For example this product https://www.scotlightdirect.co.uk/products/cohen-matt-black-7-light-semi-flush-with-opal-glass/
 
Price through from api is £91.81. This is correct and includes 20% VAT/TAX. 
 
When you view the page source below. You can see that the price it is syncing across is the ex VAT price <span class="bc-product__price">£76.51</span>
 
view-source:https://www.scotlightdirect.co.uk/products/cohen-matt-black-7-light-semi-flush-with-opal-glass/.
 
In terms of settings in the Big Commerce plugin currently under currency settings I have “price display” set to “Including tax”.

**Comment by yuenvision** [comment]
Expected to be addressed in v4.34.0

**Comment by tyla-taylor** [comment]
Addressed in v4.34.0
