### ISSUE TITLE
Syncing Customer Groups Issue

### ISSUE THREAD

**Issue by Dmitry-Komkov** [bigcommerce/bigcommerce-for-wordpress#378]
### Expected behavior
The product which is not visible/purchasable for a particular customer group should not be visible/purchasable after I select another customer group for a user in Bigcommerce

### Actual behavior
The products are visible/purchasable.
But. When you create a new user and assign him to any customer group, it works fine. But when you try to reassign it to another group it seems like the products data is cached somewhere and it keeps displaying wrong products.

### Steps to reproduce behavior

1. Change customer group for a user in Bigcommerce onto the one with different products list
2. Go to Wordpress -> Bigcommerce -> Flush User/Products Cache -> Sync All products
3. Try to go to a product page which should not be visible/purchasable
4. You can still see and add a product to a cart although the customer group is correct and actually it cannot see/buy that product

### Plugin Version
4.32.0

**Comment by yuenvision** [comment]
Expected to be addressed in v4.35.0

**Comment by tyla-taylor** [comment]
Addressed in v4.35.0
