### ISSUE TITLE
Redirecting to 404 or show some message if a product is not acceptable for a customer group

### ISSUE THREAD

**Issue by Dmitry-Komkov** [bigcommerce/bigcommerce-for-wordpress#379]
### Expected behavior
Redirect to 404 or show some noticeable message, for example, that "You cannot see/buy this product" or something else.

### Actual behavior
The product can be visited by any user and any customer group. It cannot be added to the cart (that is okay!) but can be visited though. When you try to open the page with a product which is not visible for your customer group, it can be opened. When you press add to cart button, it show a message that "Product not found" and it's reasonable. But it may confuse the users.

From the other hand, when you try to make the same steps on the Bigcommerce store, this product will just show you 404 page.

### Steps to reproduce behavior

1. Log in with a customer who is assigned to a customer group
2. Go to a product page which should not be visible for that customer. It will be opened.
3. Try to add that product to a cart.

### Plugin Version
4.32.0

**Comment by yuenvision** [comment]
Expected to be addressed in v4.35.0

**Comment by tyla-taylor** [comment]
Addressed in v4.35.0
