### ISSUE TITLE
Bulk product updates caps at 20 items, goes to 404 page.

### ISSUE THREAD

**Issue by DEIJasonP** [bigcommerce/bigcommerce-for-wordpress#380]
### Expected behavior
Using the bulk edit tools should allow one to select multiple products in one state, "draft" for example, and set them all to a new state, "published" for example.

### Actual behavior
Bulk editing multiple products to set to "published" only publishes 20 products at a time, then returns a 404 error page. This is with BC4WP v4.32.0 installed on WP 6.0.1.

### Steps to reproduce behavior
1. From the Admin dashboard, navigate to BigCommerce > Products.
2. Select all products currently in view with the select-all checkbox at the top left of the products list.
3. Select "Edit" from the Bulk Actions dropdown above the select-all checkbox.
4. Click "APPLY," then select "Published" from the Status dropdown, then click "UPDATE."
5. After waiting, the next page that loads will be a 404 error message.
6. Navigate "back" in the browser, then refresh the product screen. Note that the number of affected drafts will only have changed by 20.

### Workaround or possible solution
No known workarounds currently.

**Comment by yuenvision** [comment]
Expected to be addressed in v4.35.0
