### ISSUE TITLE
Remove cart item not working as expected

### ISSUE THREAD

**Issue by samsourav** [bigcommerce/bigcommerce-for-wordpress#386]
### Expected behavior
When adding multiple items to cart then remove functionality is working fine but for last item it is not working and stuck at that process.

![image](https://user-images.githubusercontent.com/55572326/188877785-5ffcc9aa-44c5-4dda-81ae-8e0c26511400.png)

### Actual behavior
Remove cart item should be working for all individual cart items.
![image](https://user-images.githubusercontent.com/55572326/188877969-835d5aab-09de-4380-a248-5bc879ee6340.png)

### Steps to reproduce behavior
1. Visit site : [https://wp.bidetsplus.com/](https://wp.bidetsplus.com/)
2. Add multiple item in cart (Make sure to change variations on single product page before adding to cart)
3. On cart page try removing items one by one till last one.
4. You will see the last item is not being removed.

### Video

[Click here for Video](https://www.loom.com/share/69fd7fb3c24e45748d8e82322c955925)

**Comment by MlKilderkin** [comment]
Hello @samsourav 

We are not support AMP anymore
