### ISSUE TITLE
Edit and Add-Address is not working for AMP

### ISSUE THREAD

**Issue by samsourav** [bigcommerce/bigcommerce-for-wordpress#387]
### Expected behavior
On account address page, the buttons **Edit**, **Delete** and **Add New Address** should be functional. **Edit** and **Add New** Button should open a form to add or edit the address.

### Actual behavior
On account address page, the buttons **Edit**, **Delete** and **Add New Address** is not working for AMP.

### Steps to reproduce behavior

1. Visit Site and register [Click here to register](https://wp.bidetsplus.com/create-account/)
2. Make sure to fill address details while registering
3. Then navigate to address page from account page or [Click here to visit address page](https://wp.bidetsplus.com/addresses/)
4. Try adding, deleting or updating address

### Screenshot

![image](https://user-images.githubusercontent.com/55572326/189284162-ec039e56-1efb-4af5-981c-4c8c3e974cbb.png)

**Comment by MlKilderkin** [comment]
Hello @samsourav 

We are not support AMP templates anymore
