### ISSUE TITLE
Big Commerce CDN Image Size Issue

### ISSUE THREAD

**Issue by jamescscotlightdirect** [bigcommerce/bigcommerce-for-wordpress#393]
@MlKilderkin As discussed. 

"Fast Headless" option is always pulling images from Bigcommerce CDN. By default it takes standard size of images from product response: url_standard Same for standard import with Import images URLs only option enabled. 

Example - 

https://www.scotlightdirect.co.uk/products/nantes-polished-chrome-aluminium-5-light-pendant/

"Properly size images" 4.65s. 
https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.scotlightdirect.co.uk%2Fproducts%2Fnantes-polished-chrome-aluminium-5-light-pendant%2F

Example image that is being pulled for this product is the original large image 
https://cdn11.bigcommerce.com/s-9yu28o6y6f/products/9437/images/19244/NAN0568_2__72224.1664293521.1280.1280.jpg?c=1

Once compressed through Big Commerce plugin this is the image from the big commerce back end but this does not get sent to the front end and the plugin keeps pulling the original large image from the CDN. 
https://cdn11.bigcommerce.com/s-9yu28o6y6f/products/9437/images/19244/NAN0568_2__72224.1664293521.386.513.jpg?c=1&_gl=1*11xufzl*_ga*MTMwODQ1NzA2LjE2NDk1NjYzMTI.*_ga_WS2VZYPC6G*MTY2NDg3MTk5Mi4yNTIuMS4xNjY0ODcxOTk4LjU0LjAuMA..&_ga=2.36164448.1910490887.1664784828-130845706.1649566312

**Comment by MlKilderkin** [comment]
Thank you @jamescscotlightdirect We will take a look and try to handle that

**Comment by jamescscotlightdirect** [comment]
@MlKilderkin great thank you
