### ISSUE TITLE
PHP 8.0 errors with Mini-Cart and Cart powered by BC4WP

### ISSUE THREAD

**Issue by ll-r-magner** [bigcommerce/bigcommerce-for-wordpress#399]
### Expected behavior
Updating wordpress to PHP 8.0, expected nothing to break outside of my custom code. 

### Actual behavior
Updated to PHP 8.0 and fixed all errors and warnings inside custom code. Bigcommerce Mini Cart and Cart Page are not functioning. 
  - Mini cart always showing as empty.
  - Cart "remove" button not functioning
  - Once cart refreshes after "remove" button was pressed it shows empty cart even though there are more products in cart left. 

### Steps to reproduce behavior

1. Updated wordpress php to version 8.0 from 7.4.
2. Astra parent theme
3. Using BC4WP plugin to run our mini-cart and cart

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

### Workaround or possible solution
We can maintain the site on PHP 7.4 until January 24th 2023. Then we will have no choice but to upgrade to 8.0.

**Comment by ll-r-magner** [comment]
Disregard, im sorry for assuming it was the plugin. I was using Kinsta wordpress debugger mode and it was causing conflicts with cart functionality. All is well. Cheers.

**Comment by chanceaclark** [comment]
Thanks @ll-r-magner, I'll go ahead and close this!
