### ISSUE TITLE
Search in product widget block is not working when Fast Headless import is on

### ISSUE THREAD

**Issue by bc-tatiana** [bigcommerce/bigcommerce-for-wordpress#403]
### Expected behavior
Products appear in the search results when searching for items in the product widget block when creating a new blog post.

### Actual behavior
No products are returned in the search results if Fast Headless import was used to sync products. The problem appeared around a year ago.

### Steps to reproduce behavior

1. Set up WordPress and sync products using the Fast Headless import option.
2. Go to Posts and create a new post.
3. Add the "BigCommerce products" widget to the post and attempt to edit the product list.
4. In the search bar, enter a search query to look up available products, press enter, and click "Search"

### Screenshot/Video (if applicable)
https://drive.google.com/file/d/1mMwB1P4Fk_rx7nEDctSqA5IkSa81PegV/view?usp=sharing

### Workaround or possible solution
Select products from the list/categories manually.

**Comment by parrotessentials** [comment]
Hi. Is there an update on this issue? Is anyone actually working on this? Many thanks.
