### ISSUE TITLE
Shortcodes with search are not escaped

### ISSUE THREAD

**Issue by carsonreinke** [bigcommerce/bigcommerce-for-wordpress#41]
### Expected behavior

Shortcode using `search` includes a `[`/`]` and returns results properly.

### Actual behavior

Shortcode is not being processed properly.

### Steps to reproduce behavior

Within the WordPress Admin page:
1. Press "Add Products" button
2. Do a search using term `[Sample]`
3. Save and publish page
4. View page

### Screenshot/Video (if applicable)

![screen shot 2018-07-23 at 4 41 31 pm](https://user-images.githubusercontent.com/378481/43101816-4f1c7316-8e97-11e8-872c-31128bb39a66.png)

### Workaround or possible solution

I would imagine escaping the shortcode value, but my attempt at doing that did not succeed and it is possible that your own shortcode escaping might be needed.

**Comment by karen-white** [comment]
Sorry for the delayed response on this. This issue has now been resolved 👍
