### ISSUE TITLE
Embedded Checkout Error

### ISSUE THREAD

**Issue by jamescscotlightdirect** [bigcommerce/bigcommerce-for-wordpress#417]
Hello @MlKilderkin, 

Hope you are well. We are having an issue with the embedded checkout not working on our site now and we have had to disable it. My dev who originally set up the site has said everything is the same but getting the below errors. I tried to raise a support ticket with big commerce but the support is just extremely poor now.

It's really hard to narrow down where this error is coming from. We managed to get it actually working for a bit, but it still spat out an error:

"Something's gone wrong
Your cart couldn't be retrieved. Please <a href='/'>click here</a> to continue shopping.
Error code: FBF400F19BAFFB62C922B7BEE9E5F3B09841F4CA"

When you dismissed that error it did work, but most of the time we are just getting a 403 forbidden response and I'm not sure why as looking at the setup everything should be OK. 

"resizable-iframe-creator.ts:29          GET https://checkout.scotlightdirect.co.uk/embedded-checkout 403
resizable-iframe-creator.ts:61 Uncaught (in promise) NotEmbeddableError: Cannot start a checkout session with an empty cart
    at a (resizable-iframe-creator.ts:61:25)"

Have you guys seen this before or could point us in a direction to look at as we are stuck?

Thanks

James

**Comment by MlKilderkin** [comment]
Hello @jamescscotlightdirect 

We acknowledged this request and will try to find the problem on plugin end. I'll let you know if we find anything here
Unfortunately, it can be also a problem from checkout itself and we can't handle it since we just display it on plugin side

**Comment by MlKilderkin** [comment]
Hello @jamescscotlightdirect 

We made some investigation and didn't find anything on plugin side. It looks like an issue with some Bigcommerce configs. We had similar problem before on one of the test environments. We have 403 error for embedded checkout and could not resolve it until we reach out Bigcommerce support.
Please let us know if you need something else and we'll try to help you

Thank you
