### ISSUE TITLE
Conflit with Theme Blog Grid layout and BigComm Plugin

### ISSUE THREAD

**Issue by stoneroadmedia** [bigcommerce/bigcommerce-for-wordpress#43]
### Expected behavior
I can see my main pages and other pages of website with plugin enabled.

### Actual behavior
When we add a blog grid we get a conflict with plugin that kills most of all pages on the website.  If we use the same blog section as list or author or excerpt it works fine.  My assumption is the Grid format is conflicting with the Grid format in the new BigComm plugin.

We are using Enfold Them with all plugins up to date.  We disabled all plugs and vested each one for the issue.

Error message at the top of the page when Grid view is enabled for blog posts: (cut and paste from view source)

<b>Fatal error</b>: Call to undefined function   avia_wc_clear_catalog_ordering_args_filters()   in <b>/nas/content/staging/thril/wp-content/themes/enfold/config-templatebuilder/avia-shortcodes/postslider/postslider.php</b> on   line <b>828</b><br />
--

### Steps to reproduce behavior

1. Add blog display section in page layout and enable Grid view
2.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by stoneroadmedia** [comment]
How are you getting the:

Sort by Shop by Brands to show up?

Steve



Steve Smolenski III
Owner, Chief Technology Officer, Co-CEO
Stone Road Media
(724)-875-0159
http://www.stoneroadmedia.com
________________________________

**Comment by becomevocal** [comment]
@stoneroadmedia you can use the customizer to edit what filters show up. Here are my settings:

<img width="1440" alt="screen shot 2018-11-20 at 11 32 15 am" src="https://user-images.githubusercontent.com/2677921/48791749-1083a280-ecb8-11e8-8f22-d41ed6fcc69b.png">
