### ISSUE TITLE
"Added ability for shoppers to submit Product Reviews on product pages"

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#44]
In the latest release, the comments include

"Added ability for shoppers to submit Product Reviews on product pages"

Is this just through wordpress comments or are they syncing with BC?

Are reviews on BC being synced and can they be read on the product page?

**Comment by topher1kenobe** [comment]
Reviews are bi-directional, so you could create a review on either end and it would appear in the right spot on both ends.
