### ISSUE TITLE
BigCommerce <= 5.0.7 - Unauthenticated Sensitive Information Exposure

### ISSUE THREAD

**Issue by 2gen** [bigcommerce/bigcommerce-for-wordpress#455]
https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/bigcommerce/bigcommerce-506-unauthenticated-sensitive-information-exposure

>The BigCommerce For WordPress plugin for WordPress is vulnerable to Sensitive Information Exposure in all versions up to, and including, 5.0.7. This makes it possible for unauthenticated attackers to extract sensitive data.

Anyone know what sensitive information is currently exposed?

Also any indication when this will be patched?

**Comment by chanceaclark** [comment]
Pretty sure we fixed this in version `5.0.7`. Not sure why the websites are not reporting it fixed
