### ISSUE TITLE
Bugs in cart

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#46]
- Products not being removed (visually). 

- Cart link still shows previous number of items in cart once items are deleted.

Please see video below

https://5874.wistia.com/medias/8wpk3m1qn5

(This video also highlights the overflowing images bug ( #26 ) I mentioned 9 days ago....)

**Comment by karen-white** [comment]
@5874 Following up here. Fixed in [0.12.0](https://github.com/bigcommerce/bigcommerce-for-wordpress/releases/tag/0.12.0)
