### ISSUE TITLE
Wordpress account passwords out of sync

### ISSUE THREAD

**Issue by igornes** [bigcommerce/bigcommerce-for-wordpress#47]
### Expected behavior
A user should be able to log in to WordPress store account after the user resets a password with WordPress 

### Actual behavior

The user cannot log in unless the BigCommerce store is manually updated with the same password as WordPress store

### Steps to reproduce behavior

preconditions:
A User has an existing account with BigCommerce store
User comes visits Wordpress  store
User  select products and adds to shopping cart
User  click login
Creates an account with the same email that is attached to BigCommerce Account
The user selects a new password 
Saves the account
Wordpress brings the existing account from BigCommerce to show.
User logs out
User tries to log in to WordPress store with the new WordPress password
Password error
The User resets password
The user still cannot log in
Admin logs to the big commerce store and manually updates password to match with the WordPress password. 
The user can log in now.

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by civicpath** [comment]
This issue appears to be resolved and can be closed. 

The current plugin version as of this writing is 1.10.
