### ISSUE TITLE
Proceed to Checkout from the sopping cart page generates 404 error

### ISSUE THREAD

**Issue by igornes** [bigcommerce/bigcommerce-for-wordpress#48]
### Expected behavior
Open the checkout page when clicking on the Proceed to Checkout button from the cart page

### Actual behavior
Wordpress generates  404 error

### Steps to reproduce behavior

1. Enable Anyone can register option in the WordPress site
2. Add products to the shopping cart
3. Create ad new account with Wordpress/BigCommerce Account Profile page or sign-in with existing account
4. Open the Cart page
5. Click the  Proceed to Checkout button.
6  you get  the  404 error page with the URlL like this:
wordpressdomain.com/login/token/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2bXNzdHNtcXI0eWd0djhpazIyYzNyN2h1eHJ1dmsiLCJpYXQiOjE1MzI4OTkzODQsImp0aSI6IjM0MWVjMTkxNjc4YjIyMGY1MTczYzIxYzYzNmExOTc1M2ZmODAxNTRlNGRmYjBlODllMzVjOTJjNGZiYmM2NjQiLCJvcGVyYXRpb24iOiJjdXN0b21lcl9sb2dpbiIsInN0b3JlX2hhc2giOiJ3M2w3dzN4YjUyIiwiY3VzdG9tZXJfaWQiOjEsInJlZGlyZWN0X3RvIjoiaHR0cHM6XC9cL3N0b3JlLXczbDd3M3hiNTIubXliaWdjb21tZXJjZS5jb21cL2NhcnQucGhwP2FjdGlvbj1sb2FkSW5DaGVja291dCZpZD03ZTI4Y2QyMy04YmI1LTRhNTYtYWJkYS1kZmEwZmI1YTc3M2UmdG9rZW49Y2FjMDc1ODk2NTU0MTk2MmJiYzkzZWZhZGFiMTViZjE5ZmY2YzYzZjkyNTFkYWRjMjNkNmU4MjliNDhhZDE0NiJ9.tKY2wJnyFASWZzzax2bqNHinwBWBnoxhTcSTiswn5gs

 

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by karen-white** [comment]
Closing this out @igornes , but please reopen if you're still experiencing the issue.

**Comment by 0dp** [comment]
I am experiencing this same issue. The two things comes to my mind.
1. I am on a local environment using my hosts file
2. I do not have a SSL certificate
