### ISSUE TITLE
Update product price on option select

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#49]
On a single product page, the prices do not update when options are selected. Instead, the single product page shows the price as £x - £y and the user only sees the actual price once they get to the cart.

We could really do with this being fixed asap for a client that's waiting to go live.

Thank you!!

(@topher1kenobe  @karen-white)

**Comment by tyla-taylor** [comment]
Added ability for product prices to update dynamically to reflect the price of the selected variant in v1.2.0
