### ISSUE TITLE
Unavailable products not being respected and not failing elegantly

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#50]
A product with rules defining the product as unavailable with a certain combination is not respected in WP.

Here's how a product set up like that shows on BC:

<img width="783" alt="screen shot 2018-07-30 at 11 05 03" src="https://user-images.githubusercontent.com/22817625/43391521-c5df5878-93e8-11e8-9ebd-afe745000acf.png">

(for reference, here's a combination of options that does allow purchasing)

<img width="777" alt="screen shot 2018-07-30 at 11 05 10" src="https://user-images.githubusercontent.com/22817625/43391549-d68cdd1c-93e8-11e8-9885-c803317c3374.png">

That same product in WP is displayed like this:

<img width="506" alt="screen shot 2018-07-30 at 11 08 48" src="https://user-images.githubusercontent.com/22817625/43391612-0773a7ee-93e9-11e8-9663-933459c557c5.png">

And the add to cart button is still available when the "unavailable" combination is selected.

When the add to cart button is clicked, the product is added to the cart but with default option selections:

<img width="1193" alt="screen shot 2018-07-30 at 11 09 01" src="https://user-images.githubusercontent.com/22817625/43391656-2edbc1ea-93e9-11e8-8567-4e15a61a68ab.png">

I understand that rules are being phased out, but in the mean time, while a client can still use them in BC, unless a migration from rules to options is being offered (is it??) we need to support them in the plugin. And if we can't support them, we certainly can't be adding incorrect products to the cart instead of failing elegantly.

We have a client waiting to go live that needs this fixing asap.... Thank you!! :) :)

**Comment by tyla-taylor** [comment]
Feature added in v1.2
