### ISSUE TITLE
Bulk Pricing Table

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#51]
When might we expect to be able to show the bulk pricing rules for a product?

We are having to implement a custom solution for a live client (more duplication of data entry) while this is unavailable in the plugin.

Thank you!

@karen-white @topher1kenobe

**Comment by lewcrewco** [comment]
Can I get an update on this too? My client is fully wholesale and relies on bulk pricing for all their items.

**Comment by karen-white** [comment]
@lewcrewco This is still in the feature request stage, but thanks for chiming in to help us frame the priority. We'll keep you posted if this moves into development.

**Comment by yuenvision** [comment]
Then plugin supports bulk pricing rules in the cart and checkout process, as well as qty pricing, but there is not a great way to fetch and display a table of those rules. 

The best option would be to display them in a table in the product description from BC's admin or as a post override in WP.
