### ISSUE TITLE
Pricing for Groups not working

### ISSUE THREAD

**Issue by ovsokolov** [bigcommerce/bigcommerce-for-wordpress#53]
### Expected behavior
We have store wide discounts for groups. Expect customer to see same price in the store and in wowrdpress

### Actual behavior
Show prices without group discount

### Steps to reproduce behavior

1. Create customer in biggcomerce
2.Assign customer to group 
3.Create discount to the group
4.Login to Wordpress with the same user id as created n step 1
5.No discount in wordpress. Shows regular price

### Screenshot/Video (if applicable)

![Example Image](http://placehold.it/300x200)

**Comment by civicpath** [comment]
As of version 1.1.0, the Wordpress plugin 
1) Displays the list price on the products overview page
2) Displays the list price on the individual product "Quick View" modal
3) Displays the list price on the individual product page
4) **Displays the correct discounted group price once added to the cart** 

If the need is urgent, add some text like "**Add to Cart to see your special pricing**" on the product page template.  Looks like they have the underpinnings working fine - it's just not pulling in the right display values.

**Comment by penguinmedia91** [comment]
It would be really great to get the Customer Grouping stuff to work properly in the WP plugin as it's impossible to work with wholesale clients without this. Any update on the timeline?

**Comment by tyla-taylor** [comment]
Addressed in v2.1.0
