### ISSUE TITLE
Product rules not being respected

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#58]
The plugin is not currently respecting product rules set up in Big Commerce. At best, it is failing with a confusing cart error message, at worst it is adding entirely different product options to the cart and not informing the user!

Here are two examples:

EXAMPLE 1.

Product A has two possible options to choose from and is set up in BC with the following rule:

<img width="698" alt="screen shot 2018-08-08 at 13 48 31" src="https://user-images.githubusercontent.com/22817625/43837959-00c496bc-9b12-11e8-8e95-bae90f72c2e6.png">

So, in theory, if a user chooses "30 Metre" and "OM1", purchasing should be disabled.

On the front end of BC, this happens when selecting those options (the add to basket button is removed, which is correct):

<img width="792" alt="screen shot 2018-08-08 at 13 47 02" src="https://user-images.githubusercontent.com/22817625/43838055-3a9fad04-9b12-11e8-8990-3021331be373.png">

On the WordPress front end, this happens when selecting those same options (nothing):

<img width="814" alt="screen shot 2018-08-08 at 13 52 36" src="https://user-images.githubusercontent.com/22817625/43838097-54a94822-9b12-11e8-93b5-2f9da99f96d0.png">

When clicking add to cart, it would appear that the product, with those options is successfully added (the message even says so):

<img width="1146" alt="screen shot 2018-08-08 at 13 47 20" src="https://user-images.githubusercontent.com/22817625/43838265-c9aa3866-9b12-11e8-876f-f60be5e55a6d.png">

HOWEVER! If we look more closely at the line item, we can see that the product has been added as 0.5 Metre. This is a show stopper. The customer is very unlikely to notice this, which is obviously really bad. But even if they do, there is no clear direction on how to add the product with the available options (they can't).

EXAMPLE 2.

Product B has one option and is set up in BC with the following rule:

<img width="701" alt="screen shot 2018-08-08 at 13 59 42" src="https://user-images.githubusercontent.com/22817625/43838502-6d933126-9b13-11e8-8f29-93c8b4f83830.png">

BC front end (woo! Add to cart button removed when selecting 30 metre!):

<img width="786" alt="screen shot 2018-08-08 at 14 00 52" src="https://user-images.githubusercontent.com/22817625/43838539-973aa752-9b13-11e8-8273-afaa66cf2d03.png">

Wordpress Front end (boooo):

<img width="732" alt="screen shot 2018-08-08 at 14 02 27" src="https://user-images.githubusercontent.com/22817625/43838584-b528e30a-9b13-11e8-8d36-adc66a4b4d09.png">

This time, when clicking add to cart with the option selected that should be disabled, we get this on the cart page:

<img width="1164" alt="screen shot 2018-08-08 at 13 46 33" src="https://user-images.githubusercontent.com/22817625/43838620-cac1670a-9b13-11e8-971e-108ec7252cf1.png">

Whilst this is a lot better than adding completely different options, it is not really satisfactory for the customer. The user should not be able to add the product to the cart with the "disable purchasing" rule in place on that option.

We reeeeeeeeally need this fixed asap for a live client. Pleeeeeeease!!! 

;)

**Comment by civicpath** [comment]
Hoping to bump this issue. We're still experiencing the same behavior as of version 1.1.0. 

Any BigCommerce product option that is referenced by a Product's RULES will be hidden from the Wordpress product view. Of course if any product options are required AND hidden, the product cannot be purchased. 

However, BigCommerce products that have multiples SKUs will display those product options and price changes (but not images) correctly. 

If I remember correctly, this is consistent with the Amazon Channel behavior. The Amazon channel will only bring over options where changes affect the SKU. The Amazon channel will not sync products that rely on RULES to dynamically modify option based pricing or availability.

**Comment by civicpath** [comment]
Back to the OP... in this scenario, you'd have to move the option logic out of RULES and into SKUs. 

To disable purchases for some option combinations, you would make that a SKU and set it to ZERO stock. The store wide -> Advanced Settings -> Inventory would need to also configured to  the "When an option is out of stock settings would need to be set to "Hide the option" or "Mark as out of stock".

All of this is workable for stores selling mostly stock widgets. For stores selling custom/made-to-order items, it's going to be a real challenge.

**Comment by yuenvision** [comment]
Issue handled with product config settings in BC admin
