### ISSUE TITLE
Product Sync Not Working

### ISSUE THREAD

**Issue by smashbeatmedia** [bigcommerce/bigcommerce-for-wordpress#59]
For some reason product sync is not working for me. I installed the plugin & set up the api exactly as in the documentation but it just gets hung up on "Import in progress." for hours with not progress. I tried this a few time an 2 different installs (one completely clean just to make sure it wasnt some kind of confliction). Can anyone provide insight on why I am not able to import products to Wordpress & utilize this plugin. (site is set up on WPengine transferable install) Thanks in advance!

**Comment by karen-white** [comment]
Closing this issue for now. If anyone is seeing the same issue as of version 1.3.0, please open a new issue or contact our support team: support.bigcommerce.com
