### ISSUE TITLE
add product link at cart page product name or image

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/bigcommerce-for-wordpress#6]
I suggest team to add product link at cart page product name or image
![screen shot 2018-06-13 at 10 13 22](https://user-images.githubusercontent.com/10583985/41330311-73b8be9c-6ef2-11e8-9c25-ac8aeb5dc3ba.png)

Thanks
Rawi Rai
bigmadness.com

**Comment by karen-white** [comment]
@bigmadness This feature was added in version 0.10.0.
