### ISSUE TITLE
Bigcommerce for wordpress plugin confliction - Elementor Pro

### ISSUE THREAD

**Issue by smashbeatmedia** [bigcommerce/bigcommerce-for-wordpress#60]
Figured I would open this in a new thread in hopes that maybe someone else here faced a similar problem. Whenever the Bigcommerce for wordpress plugin is activated something must be conflicting with Elementor Pro because any time I try to launch my page builder it throws an http 500 error. The error is not from the server as confirmed by my host and is only present when the plugin is activated. When Bigcommerce for wordpress is deactivated everything functions as it should. Any ideas?

**Comment by topher1kenobe** [comment]
Hey folks, we're working with Elementor on this, you can watch here: https://github.com/pojome/elementor/issues/6420

**Comment by topher1kenobe** [comment]
Resolved by Elementor.
