### ISSUE TITLE
New Version (0.11.0) breaks current installs

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#63]
We have installed the latest pull request and are super excited for quantities!!

However there are no quantities and worse, the new version disables purchasing of any products with options...

Here are two examples:

Example 1 (0.10.0):

<img width="1200" alt="screen shot 2018-08-28 at 09 15 04" src="https://user-images.githubusercontent.com/22817625/44709981-f2384d00-aaa2-11e8-9426-d515778a740b.png">

Please note enabled Add to Cart button

(0.11.0):

<img width="1219" alt="screen shot 2018-08-28 at 09 15 27" src="https://user-images.githubusercontent.com/22817625/44710009-054b1d00-aaa3-11e8-8449-13809f5d6750.png">

Please note the lack of quantity field and the now disabled Add to Cart button. The button stays disabled regardless of options selected.

Example 2 (0.10.0):

<img width="1231" alt="screen shot 2018-08-28 at 09 17 11" src="https://user-images.githubusercontent.com/22817625/44710094-30357100-aaa3-11e8-9a78-64cfa7c2032f.png">

(0.11.0):

<img width="1179" alt="screen shot 2018-08-28 at 09 17 20" src="https://user-images.githubusercontent.com/22817625/44710104-3592bb80-aaa3-11e8-8b16-9215246ba53b.png">

Any ideas @topher1kenobe, @karen-white?

**Comment by topher1kenobe** [comment]
@5874 Is this one resolved?
