### ISSUE TITLE
BC Customer Group should map to WP User Roles

### ISSUE THREAD

**Issue by masonn** [bigcommerce/bigcommerce-for-wordpress#66]
### Expected behavior
If a 'wholesale' customer group is created on BigCommerce, and a user assigned to it, when that user signs into Wordpress, Wordpress should be able to query that Customer Group, or the Customer Group should map to a Wordpress User Role

### Actual behavior
All users are created as Customer User Role

### Steps to reproduce behavior

1. Create a Customer Group on BigCommerce, called Wholesale/wholesale
2. Assign a user to that group
3. Log into Wordpress as that user
4. var_dump current_user->roles, observe it says 'customer'

**Comment by penguinmedia91** [comment]
I agree. This needs to be in place for wholesale clients.

**Comment by yuenvision** [comment]
Feature added in v3.13.0
