### ISSUE TITLE
API Connection

### ISSUE THREAD

**Issue by jfinly** [bigcommerce/bigcommerce-for-wordpress#70]
### Expected behavior
API from WP to BC

### Actual behavior
Using provided API key & path information from BC, the api cant not connect to BC

### Steps to reproduce behavior

1.upload plugin
2.input api credentials
3.save changes

### Screenshot/Video (if applicable)
![screen shot 2018-09-24 at 10 28 27 am](https://user-images.githubusercontent.com/31748680/45965075-bb435180-bfe4-11e8-85fc-6f823f9118c3.png)

![Example Image](http://placehold.it/300x200)

**Comment by karen-white** [comment]
@jfinly We've now updated to plugin to connect to the BC API automatically, without needing to paste in credentials. The upgrade process will be to deactivate and delete the old plugin, and then download the latest version from the WordPress.org plugin directory. Could you let us know if you still see the issue on the new version?

**Comment by karen-white** [comment]
Closing this for now--if you're still seeing the issue though on the latest release, please reopen 👍
