### ISSUE TITLE
Order by Price does not work

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#72]
Ordering (sorting) by price does not work. 

To reproduce: 

Order by price.

Note the prices and the order in which they appear.

<img width="1269" alt="screen shot 2018-09-26 at 11 07 43" src="https://user-images.githubusercontent.com/22817625/46080622-53cb0480-c192-11e8-8c74-d1adf3bd0c51.png">

**Comment by topher1kenobe** [comment]
Fixed
