### ISSUE TITLE
Error on "Cart" page redirect after adding product to cart

### ISSUE THREAD

**Issue by textivia** [bigcommerce/bigcommerce-for-wordpress#76]
### Expected behavior
Add item to cart, proceed with checkout.

### Actual behavior
Add item to cart, page redirects to cart page, red box with warning of "There was an error adding this product to your cart. It might be out of stock or unavailable."

### Steps to reproduce behavior

1. Visit /products/ page.
2. Add item to cart (via quick view or single product post)
3. Cart page shows error.

### Screenshot/Video (if applicable)

https://www.dropbox.com/s/j0e1aqhsod60w4j/Screenshot%202018-10-23%2010.34.24.png?dl=0

<img width="1116" alt="screenshot 2018-10-23 10 34 24" src="https://user-images.githubusercontent.com/786141/47368511-c656d380-d6af-11e8-9b3f-d205840c8957.png">

### Setup:
Wordpress Multisite.
API credentials fresh, and pulling products correctly.

**Comment by karen-white** [comment]
Hey @textivia , it's been a little while since we've heard from you. I'm going to close this out for now, but if you're still seeing the issue after installing version 1.3.0, please reopen.
