### ISSUE TITLE
Some Categories not coming through in Add Products

### ISSUE THREAD

**Issue by lucid9design** [bigcommerce/bigcommerce-for-wordpress#78]
After selecting Add Products on a page, the Categories dropdown should display all categories in BigCommerce.

Not all of the categories are showing.

Clearing cache and Product Synch does not bring through all of the Categories.

See on https://www.lemurianconnection.com/mslp/all-products.  The Books and CDs categories are not coming through.

**Comment by mardukian** [comment]
Is there any update on this one? It's still happening in an environment we're working on. Is there a workaround at all while we're waiting for the implementation?

**Comment by lucid9design** [comment]
Hello… just checking in to see if I missed a notification, per the following email thread?

Lisa

Elizabeth Diane ("Lisa"), Designer
Cell: 360 789 2526
http://lucid9design.com <http://lucid9design.com/wordpress/>

Inspired Graphic Art
Sustainable Building Design
Website Creation

PURIUM Health Products
http://mypurium.com/IAmRadiantHealth
ask about your free $50 super food gift card

**Comment by karen-white** [comment]
Hey @lucid9design @mardukian Apologies that the thread hasn't been updated. We're no longer seeing this issue on our end after the latest release. Could you confirm that you're on version 1.3.0 of the plugin?

**Comment by mardukian** [comment]
Hi @karen-white yep, we're running Version 1.3.0 of the Bigcommerce plugin and version 5.0 of Wordpress. We have more than sixty categories and subcategories set up in BigCommerce but only twenty have come over to Wordpress.

**Comment by mardukian** [comment]
Just investigated further @karen-white - Under appearance->menus->Product Categories they are coming up, but when I'm trying to use the embed modal on a page it only gives me a selection of the categories, not all of them

**Comment by lucid9design** [comment]
I did upgrade to 1.3.0.  
I was told that I would be informed after the upgrade/release.  I found out about it in the forum.

Lisa

Elizabeth Diane ("Lisa"), Designer
Cell: 360 789 2526
http://lucid9design.com <http://lucid9design.com/wordpress/>

Inspired Graphic Art
Sustainable Building Design
Website Creation

PURIUM Health Products
http://mypurium.com/IAmRadiantHealth
ask about your free $50 super food gift card

**Comment by karen-white** [comment]
Hey @lucid9design , apologies--we sent out an email to everyone in the beta who opted in to receive updates, but I should have updated this thread as well.

@mardukian Thanks for the additional info--we'll look into the issue! Could I ask how many are top level vs sub-categories, and if all cats are visible and have products in them?

**Comment by lucid9design** [comment]
Thanks, Karen.  I understand now.  Yes, it is helpful to update the thread as this is how I receive the email for my client.

**Comment by mardukian** [comment]
hi @karen-white  We’ve found a work around, we use ACF and it seems to pull the taxonomy correctly so we’re just feeding it into places to make the shortcode where necessary.

We have 27 top level categories, 26 of the top level categories have products in them.
4 of those categories have sub categories. We have 60 sub categories, all of which have products in them.
Now that I’m using ACF I can see that these categories have been created and brought over to WooCommerce its just that they aren’t showing up in the modal pop up when creating shortcodes.

**Comment by karen-white** [comment]
Thanks for the info and the workaround @mardukian ! We'll keep investigating it as an Edit Product modal display issue.

**Comment by karen-white** [comment]
Hi @lucid9design ,
I don't have an update to share at the moment, but the team is still working on resolution to a similar issue. Could you please confirm that the Books and CDs categories have visible products in them? If you are able to share the URL to the BigCommerce store so we can take a look at the way products and categories are set up on that side, it would help the investigation greatly.

**Comment by lucid9design** [comment]
I appreciate the status update.  
Original site with CD category displayed correctly:  http://www.mslpublishing.com/categories/CDs/
Original site with Books category displayed correctly:  http://www.mslpublishing.com/categories/Books/?sort=featured&page=1
I’ll stay tuned and hope to hear a resolution soon.  Thanks!!

**Comment by karen-white** [comment]
Hi @lucid9design , we're now seeing this issue resolved on our end, testing with plugin version 3.2. Could you let us know if you're still seeing the issue on your end? thank you!

**Comment by lucid9design** [comment]
I really appreciate you contacting me, Karen.
I had been updating BC4WP plugins, and am now trying to install v 3.2, but I am getting an error in creating my channel.  See the screen shot. I am using a new channel name store.mslpublishing.com rather than the default that you see in the screenshot.  
Can you help with this so I can finish the update and see if it works?  
Thanks, Lisa

**Comment by karen-white** [comment]
@lucid9design Hi Lisa, I'm not seeing the screenshot--could you try reattaching? thanks!

**Comment by lucid9design** [comment]
Yes, I’m attaching it again…

**Comment by karen-white** [comment]
@lucid9design Here's how it's coming through in the GitHub thread. Could you try attaching the image directly to your GitHub comment?
![image](https://user-images.githubusercontent.com/31664136/60304552-65972f00-98ff-11e9-8c46-5bf584a4f9cc.png)

**Comment by lucid9design** [comment]
![Screen Shot 2019-06-27 at 2 53 42 PM](https://user-images.githubusercontent.com/41274986/60305419-53ae8f80-98f1-11e9-8336-8f3748a9a8b7.png)

**Comment by karen-white** [comment]
@lucid9design Thanks, Lisa. Can you take me through the steps that you took to get to that point? Did you uninstall/reinstall the plugin or just update from your plugin settings? It would also be good to get the URL of your BigCommerce store.

**Comment by topher1kenobe** [comment]
Original issue resolved.
