### ISSUE TITLE
cart icon is not showingnumber of items 

### ISSUE THREAD

**Issue by georgeshemtov** [bigcommerce/bigcommerce-for-wordpress#8]
I have followed the instructions to integrate the "Bigcommerce for Wordpress" plugin in my site. I have added the API Credentials in wordpress and connected it then improted the products from Bigcommerce store and currently it displaying on tests page
please check this URL https://thepeopleschemist.com/tests-page/ 

I'm able to add the product item onclick ADD TO CART button and it is redirecting on cart page as well
but mainly I need is to have the add to cart click add item to the cart icon, Currently CART ICON (In the header menu) is not showing the number of items.

Please Help Me As Soon As Possible!

**Comment by karen-white** [comment]
@georgeshemtov  We're tracking the feature request for the add-to-cart flow you requested on #45 . I'm going to go ahead and close this to keep those feature requests consolidated.
