### ISSUE TITLE
0.13.0 - "An error occurred creating your channel"

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#80]
### Expected behavior
Ability to use the plugin

### Actual behavior
Inability to use the plugin

### Steps to reproduce behavior

1. Upgrade the plugin
2. Go to the "Welcome" screen

### Screenshot/Video (if applicable)

<img width="928" alt="screenshot 2018-10-31 at 15 49 16" src="https://user-images.githubusercontent.com/22817625/47800959-1cb5b900-dd25-11e8-9af3-9462f1af63e7.png">

This renders the plugin useless. Any ideas?

**Comment by karen-white** [comment]
@5874 Happy to report that we've fixed this in 1.1.0. Closing for now, but please reopen if you're still seeing the issue.

**Comment by jecalderon** [comment]
I have this dead issue ..I  have Word PRess 5  in a Windows Server 2012 with al the myQL  COnnecting to the BigCOmmerce but the Connection Channel goes bad

**Comment by jecalderon** [comment]
> Manually going through the database and deleting everything related to BC prompted the "welcome screen" to connect an account instead of the channel page.
> 
> Am unable to test further due to not having owner logins but the necessity to delete data from the database when upgrading needs to be either handled by the plugin or documented in the readme.

manually?  You mean going to mySQL and rerase what?
