### ISSUE TITLE
0.13.0 && 0.14.0 sync limit 

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#84]
When syncing the latest version of the plugin, it appears to only import 100 products despite there being considerably more than that in the BC store.

100 seems to be a suspiciously round number to be a coincidence.

Can anyone offer any insight on this and how to sync the rest of the products?

Thank you

**Comment by karen-white** [comment]
@5874 Fixed in 1.1.0. Closing this out.
