### ISSUE TITLE
quick view click

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/bigcommerce-for-wordpress#9]
I suggest to remove full image click for quick view.

**Comment by scottxtensive** [comment]
We were also able to add a link in via the $product parameter. This would clearly be much more easily achieved with a toggle inside the customiser view.

> <div class="bc-product-card">
>   <a href="<?php echo site_url();?>/products<?php echo $product->custom_url->url;?>">
> 		<?php echo $image; ?>
>   </a>
> 	<div class="bc-product__meta">
> 		<?php
> 		echo $title;
> 		echo $brand;
> 		echo $price;
> 		?>
> 	</div>
> 	<?php if ( ! empty( $form ) ) { ?>
> 		<div class="bc-product__actions" data-js="bc-product-group-actions">
> 			<?php echo $form; ?>
> 		</div>
> 	<?php } ?>
> </div>

**Comment by amckemie** [comment]
This issue has been resolved through a feature addition in a newer BC4WP release.
