### ISSUE TITLE
Vanilla Install (0.14.0) will not work without updating permalink structure

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#90]
Vanilla install. WPBC plugin the only plugin.

After initial install, the shop will not work without updating the permalinks. 

There is no notice for the user.

We came up with a solution in a our add on plugin that forces the permalink structure through the init action:

```
		global $wp_rewrite;

		$wp_rewrite->set_permalink_structure( '/%postname%/' );
```

Hope that helps.

**Comment by civicpath** [comment]
Possibly resolved as of v1.1.0

The WPBC plugin will work using the default/plain Permalink structure:

All Products 
https://WP_URL/?post_type=bigcommerce_product

Individual Product
https://WP_URL/?bigcommerce_product=SKU


Looks like you have to manually create a menu item manually for the "All Products" page.
