### ISSUE TITLE
Optional Google Analytics?

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#91]
Having the analytics code from BC forced in to the WP site by the plugin (src/BigCommerce/Import/Processors/Store_settings.php:104) has caused issues with our analytics. Any chance of making that optional? Or at least sticking a filter in there so we can choose to omit it?

Some docs of that would be cool. We couldn't figure out how the extra analytics was getting in there until we went digging and found the preg_match.

:)

**Comment by sweethoneycode** [comment]
What kind of issues did this cause in your analytics?
