### ISSUE TITLE
0.14.0 Unable to add any products to cart after upgrade

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#93]
Following upgrading to 0.14.0 we are no longer able to add any products to the cart.

<img width="1269" alt="screenshot 2018-11-08 at 10 37 42" src="https://user-images.githubusercontent.com/22817625/48193520-885dde80-e342-11e8-93a5-5d65fc14b6d1.png">

Can anyone at all help with any of the 0.13.0/0.14.0 issues **please**?

ps. Note the basket count in the top right...

**Comment by 5874** [comment]
@becomevocal Was that hot fix applied to 1.0?

**Comment by becomevocal** [comment]
It was, however I want to circle back and ask what you mean by basic auth... are you talking about gating the site or something else?
