### ISSUE TITLE
AMP

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#94]
Are there any recommendations or docs for implementing AMP please?

We are using the Wordpress AMP plugin (https://wordpress.org/plugins/amp/) and while other template files can be copied in to a sub directory of the theme (defined in functions.php), the shop (archive) page does not get used when copied in to the same sub directory.

How can we implement AMP for BCWP pages please?

Thanks a lot :)

**Comment by becomevocal** [comment]
WordCamp US is December 7th - 9th so that's our target. To stay comfortable I'd prefer clients are updated a few weeks after each release so we can polish bleeding edge features, so 'by EOY' is a better timeline IMO.
