### ISSUE TITLE
Add to cart form shows for products that are out of stock.

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#98]
### Expected behavior
User can not add products to cart that are out of stock.

### Actual behavior
Users can click "Add to cart" on all products regardless of stock level.

### Workaround or possible solution
Hide the add to cart form if product is out of stock.

**Comment by kish2011** [comment]
Yes facing this issues on the product page. In the checkout page, it says *There was an error adding this product to your cart. It might be out of stock or unavailable.*

**Comment by yuenvision** [comment]
If BC admin is set such that Inventory is tracked, then BC respects stock levels and will not allow Add To Cart to be clicked and a message is surfaced to the customer; If it is not tracked, then BC ignores stock levels WRT to add to cart, but the API continues to send the inventory count behind the scenes.
