### ISSUE TITLE
v1 - Does not sync all products....

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#99]
Installed the new version, manually removed rows from wp_options (current upgrade process), connected account & channel and sync'd products. There are 256 products in that shop. 114 imported and now it is stuck with 142 remaining. There is still no cancel sync button and no documentation on how to cancel a sync.

This seems to be a regular problem with every recent release at the moment... 

What do we need to do to get the plugin to successfully sync all products?

Can somebody please get back to us on this one?

@karen-white (Why can we not tag Topher anymore? He's the WP advocate right?)

**Comment by 5874** [comment]
#84 #39 #59

**Comment by 5874** [comment]
I deactivated the plugin, hoping that would remove any BC related data in the db. It did not (can that be an option please?). So I manually removed tables and entries that were BC specific. I reactivated and resync'd. It is now duplicating all the products. I can not stop it. Once it has finished duplicating everything I will attempt to delete everything again and resync again.

If anyone can help, please can you this time??

Thank you!!

**Comment by 5874** [comment]
<img width="462" alt="screenshot 2018-11-12 at 12 09 03" src="https://user-images.githubusercontent.com/22817625/48346665-c9702e80-e673-11e8-8039-7a6814df5589.png">

The plugin is now stuck on this.....

I am going to manually go through and delete absolutely everything relating to the bc plugin and reinstalling again.

ps. The sync appears to be taking a LOT longer with recent versions. It just took 30mins+ to sync 256 plugins (which it duplicated). Is there a reason for that?

**Comment by 5874** [comment]
After deleting all the products, emptying the bin, deactivating the plugin, dropping all bc specific tables, removing bc related rows in wp_options, reactivating the plugin, connecting account & channel and clicking sync, the plugin is now importing all products in to the trash......

<img width="447" alt="screenshot 2018-11-12 at 13 17 30" src="https://user-images.githubusercontent.com/22817625/48349914-7e5b1900-e67d-11e8-9135-859e672d884c.png">

This probably warrants it's own issue. I'll create it.

**Comment by becomevocal** [comment]
@5874 do you have access to an API account with channel and listing scopes? I feel like this is centered around listings not being created for each product.

**Comment by 5874** [comment]
We have the API account we have always used. We have seen no documentation telling us we needed to do anything different. But we also are using the new channel connection, not entering API details. Is there something we are supposed to be doing that is not documented (I've read everything there is to read about the plugin today - The docs on bc.com are now outdated with regards to templates by the way)

**Comment by becomevocal** [comment]
Ok, that should have channels and listing scopes. What should be happening with the most recent version of the plugin is:
1) Listings are downloaded for the channel to determine if any products should not show on the WP site that we're previously shown
2) New products are imported and listings created in an 'active' status

The next step is checking if you have a channel and listings for the site, to ensure this process is being followed. Here's the postman collection for those APIs so you are jumpstarted into this process: https://www.getpostman.com/collections/5d3e39bba3b7d9a1900e

I'd recommend hitting the GET Channels endpoint to find out what your WordPress site channel_id is and then GET Listings endpoint to see it there are listings populated.

**Comment by 5874** [comment]
Channels Endpoint:

`{
    "status": 403,
    "title": "You don't have a required scope to access the endpoint",
    "type": "https://developer.bigcommerce.com/api#api-status-codes",
    "errors": {}
}`

But this is using our original API creds, not what the channel connector gets because we can't use the latest version at all, not even in dev.

**Comment by karen-white** [comment]
@5874 On your store, we've turned on the ability for you to manually add the Channel Listings and Channel Settings scopes when you create API credentials. Could you try creating a new API account with the channels scopes?

**Comment by annuweb** [comment]
I have facing issue into your plugins : BigCommerce Wordpress

This plugis is under development . I have found some issue.
1) when I add product , It's increase counter . But not show products like mini cart on hover like woocommerce .
2) when I add product , Then it redirect to site cart page. I have need to back from cart to add another
product.

3) when I remove products from cart page is not decrease cart counter number.

For this. I have created video for you . Please check this.

**Comment by 5874** [comment]
@karen-white As previously mentioned, we are unable to use this plugin and this was days ago. We're going to stick with version 0.12.0 for the foreseeable future.

**Comment by karen-white** [comment]
@5874 Fixed in 1.1.0. Closing this out, but let us know if you're still seeing issues with the new version.

**Comment by 5874** [comment]
@karen-white As you know, the most recent version is unusable for live sites trying to upgrade from 0.12.0 so we've no idea!
